# Use root/example as user/password credentials
version: '3.1'

services:
  website:
    image: acnespecialisten:1.0
    environment:
      DB_URL: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 80:80

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: lok13rum
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - acne-datavolume:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  acne-datavolume:
