<?php exit; /* intern LYNX-arbetsfil – ej webb-serverad, läs i editor/git */ ?>
# LYNX AI QUESTIONS — frågelistor per sida (kolumnfil)

> **AI QUESTIONS-kolumnens datafil** (filkarta i `lynx-data.php`). Innehåller LYNX-vyn "AI Overview Ranking" per sida: **SCORE** = frågans vikt (högst först) · **OPTIMIZED** = hur väl sidan besvarar frågan (Very Good > GOOD > OK > POOR > VERY POOR; "–" = ingen status). Officiell kolumndefinition: *"How well this page answers common user questions for the topic based on Google SERP."* Tolkningsmodell: playbook **§1.5** (H1–H7). Används i §7 steg 4a (rewrite) + Fas 2 (FAQ). Format: score · fråga · status. Fyll på per sida när ägaren skickar; notera FÖRE-status inför mätning (§10).

## Sid-listor (mottagna 2 jul 2026, LAST UPDATE 02 JUL)

*acne-ansikte.php (mottagen 2 jul 15:12 — ON-TOPIC lista i kontrast till homepage/H7: zon-frågorna ÄR sidans ämne; ägarbesked: "rimliga frågor, kika på när vi når den fasen" → Fas 2-kandidat #1; listan fortsätter förbi rad 27, slutet ej synligt):* 21 Varför får man finnar på käklinjen? **POOR** · 10 Vad betyder finnar på käklinjen? **POOR** · 10 Varför får jag finnar vid käklinjen? **–** · 9 Hur får man bort akne i pannan? OK · 7 Vad betyder det när man har akne i käklinjen? OK · 7 Vart sitter stress finnar? **POOR** · 6 Vad betyder finnar på käkbenen? **POOR** · 6 Hur får man bort akne på pannan? OK · 5 Vart sitter hormonell akne? OK · 5 Hur får man bort akne i ansiktet? OK · 4 Vad betyder finnar på halsen? OK · 3 Kan östrogen ge akne? OK · 3 Hur får man bort akne på näsan? OK · 3 Varför får man finnar på brösten? OK · 3 Vad betyder det om man får finnar i pannan? OK · 3 Varför får jag finnar på käken? OK · 2 Vad ska man göra mot akne i käklinjen? OK · 2 Varför får jag små finnar? OK · 2 Vad betyder finnar på käken? OK · 2 Vad betyder finnar i pannan? OK · 2 Kan magnesium ge finnar? **POOR** · 1 Varför får jag akne i pannan? OK · 1 Varför får folk finnar på halsen? OK · 1 Varför får man finnar på käkbenen? OK · 1 Hur blir man av med finnar i ansiktet? OK · 1 Hur vet jag om min akne är hormonell? OK · 1 Hur får man bort akne i pannan? **GOOD** (avklippt) *(Topp-gap: käklinje-klustret — score 21+10+10+7+6+2 ≈ 56 poäng samlat på POOR/– trots att sidan HAR käklinje-zonsektion → svaret finns inte i frågans "varför/vad betyder"-FORM (H2). Magnesium-frågan = off-topic-POOR (H6, samma fråga som mogen-hy) — åtgärdas EJ.)*

*HOMEPAGE `/` (mottagen 2 jul 15:05; sid-badge POOR — enda POOR-sidan; FÖRSTA sidan med VERY POOR-frågor; listan fortsätter förbi 27, slutet ej synligt):* 3 Vilken ansiktsbehandling är bäst mot akne? OK · 3 Är Acnespecialisten bra? **GOOD** · 3 Är det bra att göra portömning? POOR · 2 Vilken behandling är bäst mot akne? OK · 2 Kan man gå till hudläkare utan remiss? OK · 2 Hur gör man en portömning hemma? POOR · 2 Vad kostar portömning? **VERY POOR** · 2 Hur mycket kostar det att ta bort milier? **VERY POOR** · 2 Hur mycket kostar laserbehandling för acneärr? POOR · 1 Kan man ta bort fibrom själv? OK · 1 Kan man ta bort akne med laser? OK · 1 Vad gör en hudterapeut? OK · 1 Hur länge håller en portömning? **VERY POOR** · 1 Vilken ansiktsbehandling ger bäst resultat? OK · 1 Vad är MicroDermabrasion? POOR · 1 Kan IPL förvärra rosacea? OK · 1 Hur länge håller HydraFacial? **VERY POOR** · 1 Hur får man bort djupa acneärr? OK · 1 Vad kostar det att gå till en privat hudläkare? OK · 1 Vart söker man vård för acne? OK · 1 Vad kostar en hydrafacialbehandling? POOR · 1 Hur länge håller infuzion? **VERY POOR** · 1 Kan man söka hudläkare utan remiss? OK · 1 Vilken ansiktsbehandling är bäst mot porer? OK · 1 Hur rengör man ansiktet på djupet? OK · 1 Vilken behandling är bäst för ansiktet? – · 1 Vilken laser är bäst för acneärr? (avklippt) *(→ §1.5 H7: listan speglar startsidans landing-keywords, inte startsidans innehåll; alla VERY POOR = pris-/hållbarhetsfrågor vars ägarsidor är silosidor. Ägarbeslut 2 jul: startsidan ska INTE besvara silo-frågorna — den äger varumärkes-/förtroendefrågorna + ev. remiss-familjen.)*

*microneedling.php (LAST UPDATE 06 JUL — sidan EJ omskriven, ändå skiftad lista sedan 2 jul → SERP-drift, §1.5):* 24 Vad är microneedling bra för? OK · 14 Vad kostar en microneedling behandling? OK · 13 Är microneedling värt pengarna? OK · 8 Vilken behandling är bäst mot pigmentfläckar? OK · 7 Can microneedling bring out acne? OK · 7 Är det värt att göra microneedling? OK · 6 Kan man göra microneedling när man har akne? **GOOD** · 5 Är kemisk peeling bra? OK · 4 Finns det risker med microneedling? OK · 3 Vilken klinik är bäst på microneedling? OK · 3 Hur lång tid tar det innan man ser resultat av microneedling? OK · 3 Hur ser man ut efter en kemisk peeling? OK · 2 Does microneedling really work for acne? OK · 2 Hur länge håller resultatet av microneedling? OK
*(2 jul-diff: topp "Vad är microneedling bra för?" 25→24, fortf OK trots egen FAQ-titel = H1 bekräftad; enda GOOD "Kan man göra microneedling när man har akne?" kvar (9→6); flera frågor bytts in/ut (nya: klinik-bäst, hur-ser-man-ut-efter-peeling, does-it-work, hur-länge-håller) + scores skiftade — sidan orörd → drifterna kom från Google SERP, inte vår text. **Regeln bor i `lynx-models` §1.5 (SERP-drift).** 2 jul-listan i git-historik.)*

*portomning.php:* 23 Hur går en portömning till? OK · 20 Är det bra att göra portömning? OK · 13 Hur gör man en portömning hemma? OK · 12 Hur länge håller en portömning? OK · 11 Vad kostar portömning? OK · 6 Är det bra med portömning? **–** · 6 Vilken ansiktsbehandling är bäst mot porer? **GOOD** · 5 Hur gör man portömning hemma? OK · 4 Hur mycket kostar en portömning? OK · 3 Hur tömmer man porer? OK · 3 Hur rengör man ansiktet på djupet? **GOOD** · 3 Vad är bäst för att få bort pormaskar? OK · 3 Hur gör man en portömning? OK · 3 Är det bra att tömma pormaskar? OK

*acne-rygg.php:* 26 Hur får man bort akne på ryggen? **GOOD** · 22 Hur blir man av med akne på ryggen? **GOOD** · 12 Hur får jag bort akne på ryggen? **GOOD** · 10 Varför får jag så många finnar på ryggen? OK · 7 Varför får man ryggakne? OK · 7 Vad beror ryggakne på? OK · 6 Vad betyder finnar på ryggen? OK · 6 Varför finnar på ryggen? OK · 5 Hur blir man av med akneärr på ryggen? **GOOD** · 5 Hur får man bort acneärr på ryggen? OK · 4 Vart sitter hormonell akne? OK · 4 Varför får jag akne på ryggen? OK · 4 Kan man få finnar på ryggen av stress? OK · 4 Betyder ryggakne PCOS? OK

*mogen-hy.php (mottagen 13:03-leveransen 2 jul; 27 frågor; FÖRSTA sidan med POOR-frågor och första UTAN någon GOOD — sid-badge ändå OK):* 24 Vad betyder hy? OK · 14 Vad menas med mogen hy? OK · 14 Hur får man bättre hy i ansiktet? OK · 11 Vilken ålder är mogen hud? OK · 10 Kan 10-åringar få finnar? OK · 9 Vad betyder egentligen hy? OK · 7 Vilken ålder har man mogen hud? OK · 5 Kan magnesium ge finnar? **POOR** · 5 Vad är det bästa för mogen hud? OK · 5 Vid vilken ålder får man mogen hud? OK · 3 När anses man ha mogen hy? OK · 3 När anses man ha mogen hud? OK · 3 Vad är en hy? OK · 3 Varför har koreaner så fin hy? **POOR** · 3 Hur gammal är man när man har mogen hud? OK · 3 Vilken ålder räknas som mogen hud? OK · 2 Hur får man glansig hy? OK · 2 Hur får man bort dålig hy? OK · 2 Räknas 40 år gammal hud som mogen? OK · 2 Vad räknas som mogen hud? OK · 2 Vad orsakar dålig hud i ansiktet? OK · 2 Vilken ansiktskräm är bäst för äldre? OK · 2 Hur får jag fin hy? OK · 2 Kan en 14-åring använda retinol? OK · 1 När räknas huden som mogen? OK · 1 Vilken ålder blir huden slapp? OK · 1 Vad står HI för? **POOR** *(→ §1.5 H6: POOR-frågorna är off-topic för sidan — magnesium, koreansk hudvård, förkortningen "HI")*

*seborroisk-keratos.php:* 18 Kan man ta bort seborroisk keratos själv? **GOOD** · 15 Hur får man bort seborroisk keratos? **GOOD** · 9 Vem tar bort seborroisk keratos? OK · 8 Hur snabbt växer seborroisk keratos? OK · 7 Kan seborroisk keratos försvinna av sig själv? OK · 7 Kan man behandla seborroisk keratos? **GOOD** · 7 Kan seborroisk keratos bli cancer? **GOOD** · 6 Hur tar man bort seborroisk keratos? **GOOD** · 5 Hur blir man av med keratoser? OK · 5 Är det okej att skrapa bort seborroisk keratos? **GOOD** · 4 Kan man ta bort keratos hemma? OK · 4 Varför får man seborroisk keratos? OK · 4 Bör seb-keratos tas bort? OK · 3 Hur får man bort seborré? OK

## Sid-badges utan frågelista (be om detalj när sidan blir aktuell)
microdermabrasion AIQ GOOD→OK 30 jun→2 jul (försämrad — vilken fråga tappade GOOD? bevakningstråd §9) · behandla-pigmentflackar GOOD · seborroisk-keratos GOOD · postinflammatorisk-hyperpigmentering GOOD · microneedling-acne GOOD · varumarken/skin-tech GOOD · POOR-badges: homepage (enda på riktiga sidor) + utility (acne-myter, studentrabatt, hudguide, not-found, priser, kontakt, roaccutan, resultat-*).
