<?php exit; /* intern LYNX-arbetsfil – ej webb-serverad, läs i editor/git */ ?>
# LYNX Arbetslogg — ARKIV (avslutade & mätta §11-poster)

```
▣ MANIFEST
KIND          HISTORIK — append-only, aldrig retroaktivt uppdaterad. Inget här får styra beslut.
LADDA-NÄR     nästan aldrig. Forensik: "vad var hela resonemanget bakom beslut X?"
KANONISK-FÖR  ingenting. Fulltext för arkiverade §11-poster (arkiv-policy R1–R6, lynx-logg §11).
PEKAR-PÅ      lynx-logg = aktiva poster + enrads-referenser · regelfilerna bär det som ratificerats
```


> Hit flyttas §11-poster från `lynx-logg.php` när de är stängda: antingen ratificerade i regler/ersatta av nyare poster, eller (för sid-poster) när deras §11.1-rad är MÄTT (arkiv-policy R1–R6, `lynx-logg.php` §11). Kvar i lynx-logg blir en enrads-referens per arkiverad post. Ordning: senaste överst. Fulltext här är **HISTORIK — aldrig retroaktivt uppdaterad**; gällande sanning bor i regelfilerna och i lynx-START. *(Filnamnen rättade 7 juli — §11 flyttade från playbooken till lynx-logg vid splitten 6 juli. Stort arkiveringspass 8 juli: 23 poster enligt R2/R3 (em #2 delvis — dess microneedling-block-plan står kvar aktiv i lynx-logg), fil-optimeringspasset §9.0 steg 4.)*

> **⚠️ §-referenser i denna fil avser filstrukturen vid postens datum.** Sedan 8 juli bor **§8, §8.1, §9, §9.0, §9.1 och §12 i `lynx-backlog.php`** (ej lynx-START). §-KARTAN i `lynx-START.php` är resolvern. Historik uppdateras aldrig retroaktivt.


### 2026-07-06 #12 — FÖRE-SEMESTER-KONTROLL av alla ändrade sidor (ägar-beställd: "lämna sidan i rätt skick") → ALLT GRÖNT
Kontrollpass över de **20 ändrade innehållssidorna** (diff `main..staging`, exkl. `includes/lynx/`-arbetsfilerna). Syfte: verifiera att det vi gjort FUNGERAR + STÄMMER med riktlinjerna innan 3 v semester. Metod = mekanisk regression + §7.6 live + §6 fras-koll + §3 copy-paste-rest (INTE ny djup-§7.4b — den kördes redan per sida vid rewrite).
**Spår A — FUNGERAR (§13.C/§7.6, via staging-URL:er):** samtliga 20 renderar HTTP 200 + full HTML, **0 PHP-fel/warning/500/blankt.** Verifierade: pigmentflackar, rhinophyma-rosacea, solskadad-hy, bristningar, mogen-hy, oonskat-har, microdermabrasion, ipl, om-oss, hudforandringar (**ingen `$types_url`-warning → d3ce9162-fixen bekräftad live**), ipl-rosacea, acne-ansikte (intro-fixen "men den går att behandla" live), ytliga-blodkarl, behandla-pigmentflackar, acne, microneedling. Småfixar bekräftade: milier **495 kr** (inget gammalt 295), milierbehandling 495 (diff), fragor-svar + gratis-hudkonsultation = **endast Google Meet, FaceTime borta**, microneedlings 5 typos rättade.
**Spår B — RIKTLINJER:** (1) mekanisk svep på ADDED lines: **0 em-streck, 0 AI-vokab (§5), 0 summerings-tics** införda. (2) **§6 fras-koll (FÖRE→EFTER-grep av varje fler-ords-`$seo_keywords`-fras):** enda tappen = små de-dubbleringar ur BORTTAGNA marknads-/fyllnadsblock (ipl "ipl behandling" 12→9, solskadad "solskadad hud" 21→18, behandla-pigment "behandla pigmentfläckar" 6→4, m.fl.) — **head-termerna kvar i `$seo_title` + H1 + robust brödtext; 0 rankande fras tappad** (precis den de-dubblering §6 tillåter). (3) **§3 copy-paste-rest:** `$specialist_url_title` ämnesrätt på alla omskrivna sidor; pigmentflackars Åldersfläckar-kort länkar nu rätt (`/aldersflackar.php`, ead4451d landade); "din bokade tid" korrekt grammatik.
**Utestående (ägar-beslut, ej blocker):** de verifierade sidorna på staging (6 Fas 3 + pigmentflackar + småfixar) väntar **main-push bakom §10.0 GSC-gaten** — beslut om att pusha före/efter semester ligger hos ägaren. Dokumenterad §9-rest (ej introducerad av oss): "Akne Specialiserade Hudterapeuter"-särskrivningen (sajtbred sweep, timing-beslut).
*(Arkiverad 8 juli, R3: "väntar main-push bakom GSC-gaten" överspelades samma dag av #13; kontrollen ersatt av #13:s produktions-verifiering. Fras-koll-siffrorna ovan är forensik om KW-vakten larmar.)*

### 2026-07-06 #10 — FILSTRUKTUR SPLITTRAD (ägarbeslut "optimerat för AI — ladda bara det du behöver")
Gamla monolitiska `lynx-copy-playbook.php` (776 rader, skummades) delad per arbetsläge: **`lynx-START`** (nav/LÄGE/router/regler/backlog §8-9/claims §12), **`lynx-rewrite`** (hantverk: §1.1/1.3/1.4 + §2-§7 + §13), **`lynx-models`** (§1.2 SCORE + §1.5 AIQ + §10 mät + §11.1 bevakning), **`lynx-logg`** (denna, §11). Playbook-filen = kort vägvisar-stub. Radbalans verifierad (773 rader → 4 filer, 0 tappade/dubblerade; varje §-sektion i exakt 1 fil). Filkartan i `lynx-data` uppdaterad; "läs top-to-bottom"-formuleringar → "läs START + router". **Princip: data ≠ tolkning ≠ logg ≠ hantverk — separata filer; en session laddar bara sitt läge.** (SCORE-tolkningen bor tills vidare kvar i `lynx-score` för att inte splittra den från sin rådata; flaggat för ev. flytt till models.)

### 2026-07-06 #9 — ONLINE-VERIFIERING av modellslutsatserna (5 research-agenter + syntes; ägar-beställd "kolla upp online")
Verifierade LYNX/SCORE/E-E-A-T-slutsatserna mot publik SEO-kunskap (full data i `lynx-score.php` "EXTERN VERIFIERING"-blocket). **Bekräftat:** LYNX = bespoke (ingen publik motsvarighet; delaxlar = kända byggstenar); de-AI-metodiken VALIDERAD av 2 oberoende (AI-tells + Googles people-first); Ahrefs ~600k sidor = ingen negativ AI↔ranking. **Korrigerat:** (1) EEAT-60 = troligt hårdkodat golv/artefakt, INTE sidtyps-auktoritet (auktoritet är off-page/sajt-nivå; /varumarken/-lyftet = rikare off-page-signaler); (2) SCORE=medel(CQ,EEAT) nedgraderad från "bergsäker" till overifierbar prediktor (ej styrbar — EEAT-badge summerar inte ens sina egna subs); (3) YMYL: "utan läkare=lägre" → ÄMNESMATCHAD expertis (hudterapeut ÄR expert; Experience egen signal) → §5 i lynx-rewrite; (4) **RAMEN: spaken är SUBSTANS, AI COPY-flaggan är PROXY — Google straffar ej AI-text i sig** → §1 i lynx-rewrite; (5) em-streck aldrig ensam-flagga (bunt). de-AI-REGLERNA oförändrade i sak.

### 2026-07-06 #6 — SEO-VAKT + BANNER-SANERING (ägarbeslut: "målet är fixa LYNX utan att orsaka skada — justera; och fixa väggen")
**Bakgrund (kritisk granskning, punkt 1+6):** (a) mätloopen tittade bara på LYNX-proxyt, inte affären, och 6 jul-scanen visade att omskrivna sidor tappat KW mer än orörda (behandla-pigment −19 %, acne-ansikte −9 %, ytliga −8 % vs orörda ±0–4 % — ej konklusivt men fel riktning); (b) LÄGE-bannern hade vuxit till en ~2 500-teckens prosavägg som riskerar skumläsning.
**NYTT §10.0 SEO-VAKT (absolut):** (1) **GSC-gate före varje main-push** — nästa våg (mogen-hy/oonskat-har/microdermabrasion) hålls på staging tills ägarens GSC-koll på de 8 live-sidorna är grön; skada → §13.F-rollback + push-paus. (2) KW-vakt per scan med tröskel >10–15 % vs stillastående sajtmedian → utred vilka fraser som föll (grep §6-målfraser först). (3) CLICKS + WORDS obligatoriska i §7-baseline. (4) §13.G omskriven: kohort-regeln (död bokstav — 8 sidor live i blandade vågor) ersatt med "vågor + GSC-gate mellan vågorna". §7 steg 7 fick gate-markering; §9 fick GSC-beställningen (⛔-rad) + ytliga-nedbrytningen prioriterad i §1.2-beställningen (post-rewrite SCORE 74 = AI STYLE-spakens A/B-test).
**LÄGE-bannern sanerad:** prosavägg → 8-raders punktlista (mål/mätt/refresh-status/live+staging/nästa/beställningar/varningar) + **banner-regel**: bara statusbyten uppdateras i LÄGE, detaljer bor i §8/§9/§11/§11.1. Allt struket ur bannern verifierades finnas i sin källsektion före strykning.
**Öppen risk-not (ärlighet):** KW-mönstret kan vara brus/säsong — GSC-kollen avgör. Tills den är gjord fortsätter Fas 3-rewrites till STAGING som vanligt (inget stopp för själva skrivarbetet, bara för main-push).
*(Arkiverad 8 juli: §10.0 bor i lynx-models, banner-regeln i START LÄGE-fotnoten. GSC-gaten passerades senare på ägarbeslut (#13) — uppföljningen är öppen i §9 "GSC-KOLL". KW-siffrorna ovan = forensik om KW-vakten larmar.)*

### 2026-07-06 #5 — EXTERN BEST-PRACTICE-IMPORT (ägar-beställd: "ton, hur vi pratar om oss, kolla online, SEO i åtanke")
**Research:** Google Search Central (people-first/E-E-A-T-självskattning), Konsumentverket (skönhetsingrepp-regler + prisinformationslagen 7a §), KO:s före/efter-granskningar (19 kliniker fällda för vilseledande bilder; regeringsuppdrag juni 2026 = SKÄRPNING PÅ VÄG), klarspråkspraxis (du-tilltal, aktiva verb, svars-först). Avstämt mot §2–§6: det mesta var redan täckt (du-tilltal, aktiva verb, gloss, av-skamning, ärlighet, verifierbara siffror, silo/intent) — importen fyller LUCKORNA:
**NYTT §5 ⚖️ Juridik-block (absoluta krav — största gapet):** (1) aldrig riskfritt-intryck (utelämnad riskinfo = vilseledande; KO-praxis); (2) före/efter-bilder får inte vilseleda — gäller även texten runt resultat-widgets; (3) 18-årsgräns injektioner → injektionscopy silo-separerad från tonårs-/elevsidor; (4) priser = bokningssystemets, paket-"Spara" aldrig framställt som rea, överstruket/kampanj kräver 30-dagars lägsta pris (7a § PIL); (5) roaccutan.php-guard (konsumentreklam för receptläkemedel förbjuden — redaktionell + pivot).
**NYTT §4.2 (praxis, ej facit):** skamfritt säljande som princip (sälj på frihet, aldrig skam/rädsla/brådska; problematisera inte normal hud) · svars-först i FAQ (första meningen = svaret — förstärker §1.5 H2 + snippet-praxis) · författarskaps-trade-offen dokumenterad (klinik-E-E-A-T i stället för bylines: SHR/30 år/maskiner/widgets — aldrig påhittade personer) · riskinfo-är-copy-vänlig-principen (konkret imperativ = både lagkrav och LYNX-🔵). §3-checklistan fick riskfritt-/skam-frågan.
**Medvetet EJ importerat:** amerikansk brand-etik-vokabulär rakt av (våra validerade formuleringar som "reparera skadad hud" är facit-🔵 och behålls); "resultat varierar"-disclaimers som hedge-fraser (lagkravet uppfylls med konkret kontext i stället — §1.1-kompatibelt); byline-krav (medvetet vägval emot, se §4.2).
**Käll-URL:er:** developers.google.com/search/docs/fundamentals/creating-helpful-content · konsumentverket.se/marknadsratt-foretag/skonhetsingrepp-och-kosmetiska-produkter-regler-for-foretag · konsumentverket.se/for-foretag/prissattning-och-ta-betalt/prisinformationslagen · konsumentverket.se/pressmeddelande/fore-och-efterbilder-vilseleder-om-plastikkirurgi · regeringen.se/pressmeddelanden/2026/06/konsumentverket-foreslar-atgarder-mot-marknadsforing-av-skonhetsingrepp.
*(Arkiverad 8 juli: käll-URL:erna kopierade till lynx-rewrite §5-juridikblocket 7 juli — de får aldrig bo enbart i arkivet.)*

### 2026-07-06 #4 — HELPLANS-GRANSKNING (ägar-beställd: "best practice, mer naturlig mänsklig formulering, annat?")
**Äkta motsägelser mot facit — FIXADE:** (1) **§4.1 Reassurance-beat-keepern rekommenderade ordagrant den fras som fällde acne-ansiktes intro** ("Det viktiga att komma ihåg är att huden kan behandlas" = §1.1-importans-filler). Omskriven: säg trösten RAKT ("Akne i ansiktet går att behandla") — innehållet är keepern, inslagningen är tellen. (2) **CTA-guidningen drog åt två håll:** §3/§4 krävde "resa"-form medan §13.N sa "skriv rakt" — och facit visar rak kort CTA = 🔵 (om-oss). Harmoniserat i §3 + §4: namngiven vinst krävs, "resa"-metaforen är valfri variation. (3) **§2 skylt-observation tillagd:** kort rumslig skylt ("Nedan tittar vi närmare…") satt i 🟢-block, "Här går vi igenom [X] och [Y]"-katalogform i 🟠-introt — föredra den korta rumsliga i intron.
**Stale state — SYNKAT (samma felklass som 2 jul-fyndet):** mogen-hy låg kvar som ÖPPEN rad i Fas 3b trots omskriven 2 jul (dubblettrad, struken med förklaring) · §9.1 Tier 3 sa "ipl-rosacea → staging" (är LIVE) och listade oonskat-har/mogen-hy/microdermabrasion som ogjorda (alla → staging) · §8-raderna fick MÄTT-status (acne-ansikte, om-oss) · §10:s "bröt 39-taket"-rad fick gamla-skalan-brasklapp · §7 steg 1 fick "notera analysdatum per vy".
**Vakter tillagda:** pigmentflackar PAUSAD-markering på alla tre ställen (§9 Fas 3-raden, §9.1 Tier 1 #2, ny §9-bevakningsrad) så ingen session startar KW244-sidan innan mysteriet är löst; §8.1-beslutslucka för om-oss noterad i §9 (beslut väntar 4:e gap-punkten + badge).
**Granskat utan åtgärd:** §5/§6 (inga motsägelser; ramarna håller mot all ny facit-data) · §1.3-rubriken (EFTER-datan stödjer) · §13 (konsekvent) · §4-öppningsbanken (alla mallar konsistenta med §1.1 nyckel 5 — empati-mallarna används i BLOCK, inte intron; §2-varningen täcker) · widget-/Fas 2-besluten (oförändrade).
*(Arkiverad 8 juli: pigmentflackar-PAUSEN är HÄVD sedan 6 juli em — läs inte vakten ovan som gällande. om-oss-beslutsluckan är öppen i §9.)*

### 2026-07-06 #3 — MODELLSYNK efter EFTER-mätningarna (ägar-beställd: "kan vi uppdatera våra modeller?")
**Uppgraderat till belagt (≥2 sidor, §1.3-regeln):** (1) **§1.1 nyckel 1 = kausal + replikerad** — 10 omskrivna flaggade block → 9 st 🔵/🟢, 1 st 🟠; EFTER-bevis-noten i §1.1 utbyggd. (2) **Stabilitet: orörda block behåller exakt tier över refresh** (~10 block, 2 sidor) → gamla facit gäller för orörda block (kösidorna behöver INTE nya facit), betygsflytt attribuerbar till textändring — inskrivet i §1.1 + §11.1-mätregeln. (3) **Vyerna refreshar oberoende** (om-oss: färsk AI Copy + april-SCORE; ytliga: tvärtom) → "kolla datum PER VY" tillagt i §11.1-mätregeln + §1.2 punkt 8. (4) **§1.2:** gamla formeln 7/7; AI STYLE-spannet 25↔30 → **20↔30** (om-oss 20 = ny lägsta; ⚠️-raden + spak-kartan synkade).
**Registrerat som HYPOTES (1 sida — ej regel, §0-disciplinen):** intro-/bannerblock-varningen i §2 — acne-ansiktes intro enda missen (🟠): empati-mening + importans-fras + meta-skylt ackumulerar trots konkret krok, medan ren skylt nådde 🟢. Operativ tumregel tills mer data: i intro-block låt krok + skylt bära, importans-fraser bort, empati-lagret till senare block. Testas mot mogen-hy-/oonskat-har-introna vid deras refresh.
**Medvetet OEJ ändrat:** §1.4-gråzonen (inga nya gränsfall — båda mätta sidorna långt under 1,5); §1.3-rubriken (EFTER-datan motsäger inget; bedömar-predikterna träffade); §1.5 (ingen ny AIQ-data). om-oss räknas in i §1.4-statistiken först vid badge-bekräftelse.
*(Arkiverad 8 juli: intro-hypotesen bor i lynx-rewrite rad 72 inkl. testplan; §1.4-gråzonen nedgraderades senare samma dag av modellanalysen 2 juli em #4.)*

### 2026-07-02 kväll #8 — Lynx-filerna flyttade till `includes/lynx/` (ägarbeslut) + mogen-hy staging-verifierad
Alla 7 lynx-filer flyttade med `git mv` till **`includes/lynx/`** (fortfarande under includes, ägarens önskan när filerna blev många); interna sökvägsreferenser uppdaterade (bara playbook + examples hade fullständiga sökvägar; korta filnamnsreferenser fungerar oförändrat då filerna är samlokaliserade). Inga kodfiler refererar lynx-filerna. **mogen-hy staging-verifierad** per §7.6/§13.E: HTTP 200 + ny fras i svaret (3:e pollen, ~1 min deploy-lag) + "mogen hy" ×77 renderat → §12-claimen tömd, §9-checkboxen ikryssad.

### 2026-07-02 em #6 — Filstruktur per kolumn (ägar-beställd) + acne-ansikte-frågelistan + homepage-AIQ-beslutet
**Filrefaktor (ägaren: "en fil för varje kolumn så att hela projektet inte blir för stort och att vi kan läsa in de sektioner som behövs"):** skapade **`lynx-questions.php`** (AIQ-frågelistor, 7 sidor), **`lynx-score.php`** (alla SCORE-nedbrytningar, färska + gamla skalan), **`lynx-gaps.php`** (gap-texter; besluten kvar i §8.1); `lynx-data.php` = NAV-FIL med filkarta + Pages-inventeringar/sidregister/kolumn-definitioner/beställningssedel; `lynx-examples.php` = AI COPY-kolumnens fil (oförändrat innehåll). Flyttade sektioner ersatta med pekare; operativa referenser i playbooken synkade (§0, facit-flödet, §7.2, §1.2, §1.5, §11-intro, LÄGE). Äldre §11-poster pekar på gamla platser = historik, filkartan reder ut.
**acne-ansikte AI Overview-lista mottagen (15:12, 27+ frågor → lynx-questions):** ON-TOPIC i kontrast till homepage (H7-kontrastpar!) — zon-frågorna ÄR sidans ämne. Topp-gap: **käklinje-klustret ~56 samlade poäng på POOR/–** trots att sidan har käklinje-sektion → H2 (svaret finns inte i varför-/vad-betyder-form). Fas 2-kandidat #1 (§9) — men FRYST tills mätningen är klar (§13.G). Magnesium-frågan POOR = samma off-topic som mogen-hy (H6 ✓ andra belägget).
**Homepage-AIQ-beslut (ägaren + H7 eniga):** startsidan ska INTE besvara silo-frågorna i sin lista — den äger varumärkes-/förtroendefrågorna + ev. remiss-familjen; silosidorna äger resten. VERY POOR-frågorna (pris/hållbarhet) = billiga FAQ-vinster på respektive SILOSIDA i Fas 2.

### 2026-07-02 em #5 — Officiella kolumn-definitioner mottagna (11 tooltips) → gissningar ersatta
**Inkommet (11 dumpar 15:00, save-first → tabell i lynx-data):** LYNX egna tooltip-texter för VALUE, PAGE TYPE, GAPS, AI COPY, AI QUESTIONS, P.PRICE, EG SCORE, KW, WORDS, CLICKS, STATUS (SCORE-tooltippen saknades — beställd). **Modellkonsekvenser:** (1) **AI COPY sidnivå = "Estimated level of AI-generated content on this page"** — helsides-skattning av kontinuerlig nivå, EJ definierad som aggregat av block-betyg → §1.4:s medel/median = proxys; gråzonen är strukturell, inte databrist (inskrivet i §1.4). (2) **AI QUESTIONS "based on Google SERP"** — §1.5-modellens SERP-bas BEKRÄFTAD; skalan har även Very Poor/Very Good. (3) **GAPS = "compared to top-ranking competitors"** — konkurrent-relativa → GAPS-förändringar får inte attribueras till oss utan gap-texterna (bevakningstråden uppdaterad). (4) **P.PRICE = uppfattat prisläge vs marknaden** ("Lower = cheaper") → ipl-rosacea HIGHEST = uppfattas dyrast i segmentet (ägar-diskussion; §13.I uppdaterad). (5) **EG SCORE** = ny engagemangs-kolumn (visits/time/interactions), hittills tom — bevaka. (6) VALUE = internt relativt; KW = keywords med sidan som landing page; CLICKS = GSC-klick.

### 2026-07-02 em #4 — MODELLANALYS (ägar-beställd före sidarbetet): §1.4 korrigerad, §1.2 stärkt, §1.3 out-of-sample-validerad
**Uppdrag:** "kör en analys av våra modeller och se om den nya informationen lärt oss något." Full analys i `lynx-examples.php` (sektion "MODELLANALYS 2026-07-02"). Fyra resultat:
**(A) §1.4 KORRIGERAD — dagens "medel 11/11" höll inte:** omräkningen av de 6 äldre sidorna (öppen §9-TODO, nu gjord) fällde medel på 3 (acne.php 1,75→pred 🟠, badge 🔵 · behandla-pigment 2,3→🟠, badge 🔴 · hudforandringar 2,08→🟠, badge 🔴). Ställning: **medel 14/17 = median 14/17 på DISJUNKTA missmängder** — 1 jul-sessionen (förkastade snittet) och 2 jul-sessionen (uppgraderade till snittet) hade båda rätt på sin data och generaliserade för snabbt. **Killer: hudforandringar 2,08→🔴 vs solskadad 2,09→🟠** ⇒ badgen ej ren funktion av tier-mixen; alternativ (typvärde, andels-tröskel, ordviktning, exkl. omdömen, ceiling) testade och fällda. §1.4 nedgraderad till arbetsmodell med **gråzon 1,9–2,4**; block-fix-räkningar = estimat; avgörande test BESTÄLLT (§9: färsk same-scan badge + komplett blocklista inkl. FAQ-svar).
**(B) §1.2 stärkt:** bristningar-breakdownen (78 dgr gammal) passar multiplikativa formeln exakt (52×50×25/3640 = 17,9 ≈ 18) → **6/6 på gamla analyser**, medan färska passar medel(CQ,EEAT) → versionsbytes-hypotesen stärkt. Testprotokollet står.
**(C) §1.3 v5 out-of-sample-validerad (blindtest 5):** 20 block ur de 6 nya MODERATE-faciten, 1 färsk bedömare, facit dolt → **55 % exakt / 90 % ±1 / binärt 15/20** — generaliserar (semi-holdout-farhågan 38 % motbevisad). 2-stegsmissar = undergissad marknad/passiv på behandlingsblock, båda konfidens ≤55 → <65-flaggan fångar. Ingen regeländring.
**(D) §1.1-minimalpar (starkaste nyckel 3/5-belägget):** "självklara valet"-blocket i tre versioner — ytliga (utan siffra, lång) 🔴 · rhinophyma (utan siffra, kort) 🟠 · bristningar (med "30 års expertis" + fråge-öppning) 🔵. Nästan identisk öppning, siffran/konkretionen flyttar två steg.
**Bonus (ägar-uppgift):** felaktigt pris 295 kr → 495 kr för enstaka milier-borttagning fixat på milier.php + milierbehandling.php (grep över hela sajten: övriga 295 kr-träffar = vaxning ×3, elevbehandlingar brynform+färg, CryoPen-återbesök på hudforandringar — bedömda utanför scope "milier och andra extraktioner"; CryoPen-priset + milier-paketpriset 1295 kr flaggade till ägaren för verifiering).
*(Arkiverad 8 juli: milier-/CryoPen-prisverifieringen är en ÖPPEN ägar-tråd — flyttad till lynx-START §9 Bevaka 7 juli innan arkivering.)*

### 2026-07-02 em #3 — MODERATE-vågen facit-KOMPLETT (pigmentflackar + oonskat-har) + homepage-/redirect-frågorna lösta
**Inkommet (zoom-dump 14:20 + 9 dumpar 14:22, save-first):** (1) **Homepage-frågan LÖST:** `/` finns i LYNX (VAL 41 · SCORE 28 · GAPS 0/0 · **AI COPY SLIGHT — ej flaggad** · AIQ POOR · KW 298); `/behandlingar.php` = **redirect till /hudbehandlingar/** (ägarbesked; KW 0 → ingen åtgärd, redirect-rad i registret). §9-tråden stängd, §9.1 Tier 1 uppdaterad (homepage-vinst = SCORE+AIQ, ej flagg). (2) **Per-block-facit pigmentflackar.php** (22 apr; 8🔴/4🟠/5🔵/1🟢, n=18, medel 2,06→🟠 ✓) + **hudproblem/oonskat-har/** (29 apr; 5🔴/2🟠/4🔵/2🟢, n=13, medel 1,77→🟠 ✓) → lynx-examples. **MODERATE-vågen har nu facit för ALLA 7 sidor.** §1.4-medel nu **11/11** (median 14/17). Rewrite-ammo: pigmentflackar-typon "AcneSpecialistem" + 3× upprepad orsaks-definition; oonskat-har har 4 trasiga meningar live (mest trasig svenska hittills). Kort-mönstret bekräftat 3:e gången: behandlingskortets ÖPPNING avgör (mekanism 🔵 vs marknad 🔴). Först 🟢 HUMAN på FAQ-rad (oonskat-har).

### 2026-07-02 em #2 — STOR-leverans: 4 MODERATE-facit + HELSAJTS-inventering + sidregister; §1.4 → MEDEL; microneedling påbörjad→ÅTERRULLAD
**Microneedling (Fas 3b):** rewriten påbörjades men ÅTERRULLADES på ägarbeslut (statistiken skulle sammanställas först; `git checkout`, claim tömd). **Bevarad block-plan (återanvänd vid omstart):** (1) banner: tankstreck→komma + NY kur-mening för §8.1-gapet ("Bäst resultat ger en microneedling kur på 3 eller 5 behandlingar, eftersom kollagenet byggs upp gradvis mellan behandlingarna"); (2) desc-p1 🔴: mekanism-öppning, behåll 16-nålar/tusentals-kanaler/serum/alla-hudtyper, döda ", vilket möjliggör"; (3) desc-p2 🔵 lätt hand: "inklusive men inte begränsat till"→"till exempel" (translationese); (4) prep-p1 🔴: konsult-boilerplate→konkreta vi-handlingar; (5) prep-p2 🟠: aktiv imperativ ("Kom inte solbränd..."), importans+svans bort; (6) process-p2 🔴: "speciellt utformade"/"maximera"/strålande-svans bort, grammatikfel "slussas in kanalerna" rättas, rodnad-är-normalt behålls; (7) aftercare-p1 🔴: importans-öppningen (ren meta) bort, imperativ, 24-timmar/smink/smutsiga-händer kvar; (8) aftercare-p2 🟠: "undvika"→"Undvik", "bastu, och"→"bastu och", "av yttersta vikt"/"rekommenderas att" bort, SPF/milda-produkter/fuktbalans kvar; (9) brands: typo "markanden"→"marknaden"; (10) kort-grammatik: "våra resultatinriktade microneedlingbehandling"→"vår...", "bristningarnas utseendet"→"utseende"; (11) FAQ §1.5: topp-frågan "Vad är microneedling bra för?" (score 25, OK) — svaret kompletteras med pigmentfläckar/bristningar/aktiv acne (sidans egna behandlingar); FAQ-typo "micronnedling"→"microneedling" (typon BRYTER sökordsfrasen "microneedling resultat"). Aftercare-p3 🔵 med "microneedling kur" lämnas orörd.
**Leverans (21 dumpar, save-first §0):** (1) **Per-block-facit ×4** → lynx-examples: solskadad-hy 6🔴/1🟠/3🔵/1🟢 · rhinophyma 8🔴/2🟠/5🔵/1🟢 (2 live-grammatikhaverier, bl.a. trasig mening i Näsa-blocket) · microdermabrasion 5🔴/1🟠/3🔵/2🟢 · bristningar 6🔴/1🟠/5🔵/1🟢. MODERATE-vågen har nu facit för 5/7 — SAKNAS: pigmentflackar + oonskat-har. (2) **§1.4 UPPGRADERAD median→MEDEL** (nya datan avgjorde: medel 4/4, median 2/4 — totalt medel 9/9, median 12/15; avrundningsregeln preciserad: standardavrundning, ,5 uppåt). (3) **Helsajts-inventering** (5 dumpar): AICOPY-flaggorna OFÖRÄNDRADE → ingen refresh på de 8 omskrivna än; **sidregister byggt** (ägar-beställt: alla LYNX-sidor ska gås igenom) — i-LYNX-lista + saknas-lista + i-LYNX-men-ej-i-repot i lynx-data; **scope: allt under /studentrabatt/ = drafts, exkluderas** (ägarbesked). (4) Nya bevakningstrådar (§9): homepage-raden/rad 15, powerlite-photonova (i LYNX, ej i repot), hifu (ny, ej i LYNX än), om-oss gap-popupens 4:e punkt. (5) bristningar SCORE 18-breakdown (78 dgr gammal) + om-oss gap-texter (remiss/vårdkö, hudläkar-skillnad, prisinfo) → lynx-data.
**Modell-observationer (nya facit, ej kodifierade — §1.3:s ≥2-sidor-regel):** "det självklara valet"-block MED 30-års-siffra + fråge-öppning = 🔵 (bristningar) vs UTAN siffra = 🟠 (rhinophyma) → siffran/pivoten gör skillnaden (stödjer nyckel 3/5). FAQ-rader kan bära EGNA betyg (🔵 ×3 sidor — första gången). Artefakt-block betygsätts ("0 2" = 🔵 på solskadad).
*(Arkiverad 8 juli — DELVIS: block-planen står KVAR AKTIV i `lynx-logg.php` (aktiv spec för nästa sidarbete, refereras av LÄGE + §9 Fas 3b). Endast leverans/inventering/modell-observationer är stängda.)*

### 2026-07-02 em — mogen-hy KOMPLETT: facit bekräftat + AI Overview-lista (27 frågor) → §1.4 första missen + medel-hypotes + §1.5 H6
**Inkommet (3 dumpar 13:03, save-first):** (1) **Slutet av blocklistan** (scrollbar i botten — inget saknades): facitet VAR komplett, sista blocket = obetygsatt FAQ-titel. → §1.4-mismatchen STÅR: median 🔵 vs sidnivå 🟠 = modellens FÖRSTA miss (**10/11**). **Medel-hypotes registrerad** (viktat medel avrundat mot värre → 🟠 ✓ på mogen-hy, träffar även de 4 nya facit-sidorna) — omräkning av de 6 äldre = §9-TODO. (2) **AI Overview Ranking mogen-hy (27 frågor)** → lynx-data: första sidan med POOR-frågor (3 st, alla off-topic) och första utan GOOD → **ny §1.5 H6** (POOR = inget svar alls, inte dåligt svar; off-topic-POOR åtgärdas ej — silovakt §5); äkta gap = "Vad betyder hy?" (score 24, OK).

### 2026-07-02 — mogen-hy-facit + AICOPY-Pages-lista mottagen (tredje leveransen idag; ENDAST SPARAD, inget agerat — låg usage i sessionen)
**Inkommet (6 skärmdumpar, save-first §0):** (1) **Per-block-facit /mogen-hy.php** (22 apr-text) → `lynx-examples.php`: synligt 5🔴/1🟠/5🔵/3🟢 (n=14) — **⚠️ möjligen TRUNKERAT** (dumparna slutar mitt i FAQ-listan) → **be ägaren om resten innan §1.4-statistiken röres**; median på synliga block = 🔵 men sidnivå = 🟠 → FÖRSTA möjliga §1.4-mismatchen, PRELIMINÄR tills komplett facit. Rewrite-ammo: 2 grammatikfel + 2 typos live. (2) **Pages-tabell AICOPY-filter (13 rader)** → `lynx-data.php`: ingen refresh på omskrivna sidor (§11.1-bevakningen fortsatt öppen); GAPS rensade på ytliga-blodkarl + ipl-rosacea; microdermabrasion AIQ GOOD→OK. **Åtgärd nästa session:** mogen-hy in i facit-kön (§9), komplett blocklista beställd.
*(Arkiverad 8 juli: helt ersatt av KOMPLETT-posten samma dag — trunkeringsvarningen avskriven.)*

### 2026-07-02 — Konsistens-audit (ägar-beställd, 2 oberoende granskare): 18 fynd → 10 äkta fixade, 8 avfärdade
**Kontext:** ägaren misstänkte interna logiska fel efter många iterationer. Två granskare svepte hela filen med olika linser.
**Status-linsen (8 fynd, 5 äkta):** pigmentflackar KW238→244 (3 ställen; lynx-data = källa) · §9 Fas 1-raden för hudforandringar hade missats i morgonens state-synk ("→ staging" trots LIVE — samma felklass igen!) · §11.1-raden fick debug-rad-not · §8.1 sebo-status uppdaterad (OBS: 2 jul-scanen visar GAPS 0/0 — LYNX flaggar inte längre gap-punkterna; besluten kvarstår frivilliga) · Fas 3 "parallellt"→"löpande" (§0.1-vokabulär).
**Modell-linsen (10 fynd, 5 äkta):** §1.2-brödtexten sa fortfarande "VALIDERAD" + imperativ ("Bryt 39 = höj AI STYLE") trots OMPRÖVAS → rubrik mjukad till 30 jun-modell + HISTORIK-divider infogad över hela brödtexten · "Fyra nycklar" var fem → rättat + nyckel 1 fick tolknings-pekare till nyckel 5 · §1.3 regel 3 sa "SIGNIFICANT." blankt före gradienten → "SIGNIFICANT som default — gradienten avgör" · §1.4 "AI STYLE-taket" → "-komponenten (§1.2 OMPRÖVAS)". Avfärdade: block- vs sidnivå-"paradoxen" (§1.4 förklarar den uttryckligen), tak-vs-spak (olika begrepp), median-flagga vs no-regression-SCORE (olika dimensioner), m.fl.
**Lärdom (generell princip, ej mikroregel):** iterativa påbyggnader lämnar gamla IMPERATIV kvar när nya data underkänner premissen — vid varje modellrevision: greppa filen efter modellens nyckelfraser och tagga/uppdatera ALLA förekomster (samma princip som state-synk-regeln från i morse, nu bevisad två gånger samma dag).
*(Arkiverad 8 juli: state-synk-principen flyttad till lynx-START §0 den 7 juli — den får aldrig bo enbart i arkivet.)*

### 2026-07-02 — Blindtest 4 (ägar-beställt test av förbättrade modeller): AI-modellen mätbart bättre + gradienten skärpt
**Upplägg:** 2 färska bedömare med v5+gradient-rubriken; 37 regressions-block (identiska med test 3) + 16 semi-holdout (ociterade block från de 4 nya sidorna). **Resultat: regression 57–62 % exakt (upp från 35–43 % med v4), ±1 89–92 %; 4 av 5 gamla tvåstegsmissar FIXADE** (meta-scaffolding, mild-importans, fluff-svans, kort+marknad; EXTREME-räkningen kvarstår hos 1 av 2). Semi-holdout: 38 % exakt / 88 % ±1. **Ny systematisk miss hittad + fixad direkt:** gradienten förlät fluff så fort konkretion fanns någonstans — facit räknar över HELA blocket → §1.3-gradienten skärpt (staplade öppningsfraser / fluff i båda ändar / lång+svans → 🔴; demografisk skal räddas aldrig). **SCORE-modellen kan inte testas lokalt** (bara LYNX producerar breakdowns) — falsifierbart protokoll registrerat i §1.2, testas mot nästa färska nedbrytningar ägaren skickar. Äkta out-of-sample-validering = första nya facit-sidan. Full data: `lynx-examples.php`.

### 2026-07-02 — AI QUESTIONS-detalj mottagen (4 sidor) → NY §1.5-modell (hypotes)
**Inkommet (4 skärmdumpar, sparade i lynx-data FÖRST):** "AI Overview Ranking" för micro/porto/acne-rygg/sebo — 14 frågor per sida med SCORE-viktning + OPTIMIZED-status (beställningssedel punkt 3 → 🟡). **Ny §1.5** med H1–H5: FAQ-titel räcker inte för GOOD (micro score-25-frågan är sidans FAQ-titel men bara OK); svaret måste matcha frågans form (acne-ryggs hur-varianter GOOD, orsaksfrågor OK); grannfrågor → ägarsida + länk (§5); hemma-frågor = återkommande topp → ärlig "ingen hemmakur" + klinikpivot; YMYL-angränsande kan nå GOOD i kosmetisk ram (sebo cancer-frågan). **Operativ följd: FAQ-svar = trippelspak (AI QUESTIONS + median §1.4 + AI STYLE) → Fas 2:s värde höjs ytterligare; Fas 3b-sidorna har nu sina frågelistor som svars-spec.** TOC kompletterad (§1.3–§1.5 saknades).

### 2026-07-02 — Modellöversyn på POSITIV-datan (ägar-beställd): §1.1 nyckel 5, §1.3-gradient, §1.4 additions-spak
**Kontext:** korpusen var negativ-tung (facit mest från SIGNIFICANT-sidor vi skrev om); de 4 nya faciten är SLIGHT-tunga (23🔵/9🟢 av 53 block) = första systematiska bilden av vad som HÅLLER block gröna.
**Uppdaterat (allt belagt på ≥2 sidor):** (1) **§1.1 nyckel 5:** en enstaka fyllnads-/importansfras fäller inte — ackumuleringen fäller; fyllnadsfras + konkretion direkt i mening 1–2 = 🔵; konkreta processblock tål flera marknadsord (portomning); CTA-pivot-räddningen gäller även behandlingskort (3 sidor); FAQ-svar kan nå 🟢; 🔵↔🟢 = brus utan operativ betydelse. (2) **§1.3 regel 3 → gradient:** importansfras + konkretion direkt = SLIGHT · + svans = MODERATE · + generiskt = SIGNIFICANT ("räkna fyllnad vs konkretion, inte frasen"). (3) **§1.4 additions-spaken:** medianen flyttas även genom att LÄGGA TILL korta konkreta block (FAQ-svar/pris/maskin-rader) → **Fas 2 är också en AI COPY-flagg-spak**, inte bara AI QUESTIONS (§13.N-vakt: äkta innehåll, ej padding). (4) **§1.2 +2 observationer:** konkret procedur-copy skårar högt på nya skalan (sebo CQ85/AI50, porto subs 95–98); möjligt att AI STYLE inte längre ingår i Overall (medel(CQ,EEAT) passar 2/3 exakt) — skulle krympa de-AI:s SCORE-payoff; avgörs med fler breakdowns.
**Ej ändrat:** §1.2-formeln (fortsatt OMPRÖVAS — ingen ny formel på 4 punkter), ±1-bandregeln, facit-först, §13-skydden. Noterat men EJ kodifierat (1 sida): antites i kort konkret block fäller inte (portomning 🟢-blocket).
**Strategisk följd:** rewrite-jobbet på 🔵-sidor (Fas 3b) = kirurgi på 2–4 🔴-block + typos, INTE genomskrivning — sidornas struktur skyddar redan medianen.

### 2026-07-02 — STOR facit-leverans (4 sidor) + färska SCORE-analyser → §1.2 OMPRÖVAS, §1.4 nu 10/10
**Inkommet (15 skärmdumpar; allt sparat i lynx-data + lynx-examples FÖRST per §0):** per-block-facit för **microneedling** (22 apr: 4🔴/2🟠/7🔵/3🟢), **portomning** (24 jun: 2🟠/5🔵/2🟢), **acne-rygg** (25 apr: 3🔴/1🟠/11🔵/1🟢), **seborroisk-keratos** (25 apr: 2🔴/2🟠/5🔵/3🟢) + färska SCORE-nedbrytningar (micro 50, porto 60, sebo **74 med AI STYLE 50**) + acne-rygg SCORE 0 = ALLA komponenter 0 + gap-texter (micro ×2, acne-rygg ×2, exosomer-gapet).
**Modellfynd:** (1) **SCORE 0 = trasig/tom analys** → omkörning krävs innan bedömning. (2) **"39-taket" brutet utan våra ändringar** → ny LYNX-version/skala trolig; 30 jun-baselines EJ jämförbara — mät färsk-mot-färsk (§11.1-varning tillagd). (3) AI STYLE 0 på färska = troligen obereäknad; sebo 50 = första uppmätta >30. (4) Aggregering ändrad/oklar (EEAT-badge 60 ≠ sub-medel; Overall ≈ medel(CQ,EEAT) passar 2,5/3) → **§1.2 markerad OMPRÖVAS; ingen ny formel förrän fler färska breakdowns.** (5) **§1.4 median: 4 nya träffar → 10/10** — vår starkaste modell. *(HISTORIK: 10/11 sedan mogen-hy-missen 2 jul em → medel-hypotes, §1.4.)* (6) §1.1/§1.3-stöd i nya facit: sebo lång-definition-utan-mekanism = 🔴 (ytliga-mönstret ✓); acne-rygg kort+marknad utan pivot = 🔴 (v5 regel 2 ✓); **ny nyans: "flera olika faktorer"-öppning fäller INTE när konkretiseringen kommer direkt i mening 2** (acne-rygg 🔵 — noterad, ej regeländring än, §1.3:s ≥2-sidor-regel).
**Beslut (ägarens, 2 jul):** micro + porto togs först (högst VALUE i default-sortering), acne-rygg + sebo också klara; **denna session = data + modellöversyn, sidfixarna görs i SEPARAT session** → **Fas 3b-kö skapad i §9** (4 sidor med rewrite-ammo: 5 live-typos/grammatikfel + §8.1-gapbeslut). **Exosomer-TODO** tillagd i §9 (gated på klinikens lansering). Fler sidor aviserade från ägaren.
*(Arkiverad 8 juli: fyndet "SCORE 0 = trasig analys" är SENARE KORRIGERAT — ägarbesked 7 juli: 0/blank = pågående omanalys som sätter sig själv, be inte om omkörning. Gällande formulering i lynx-score #0.)*

### 2026-07-02 — Optimeringarna genomförda (a–e) + blindtest 3 → §1.3 v5
**Gjort (ägarens grönt ljus på alla fem förslagen):** (a) **§7.4b** adversariell verifiering standardiserad (bantad: 1 bedömare räcker, se nedan); (b) **arkiv-policy** i §11 + `lynx-log-arkiv.php` skapad; 5 ratificerade/ersatta §11-poster arkiverade (~8,5 kB — playbooken krymper vidare mot ~55–60 kB när mätrundan stänger sid-posterna); (c) **facit-kö** inskriven i §9.1; (d) **blindtest 3** kört (nedan); (e) **Fas 2-attribueringsvakt** i §9.
**Blindtest 3 (Fable 5 + v4-rubrik, ofuskat):** 37 block ur korpusen (fulltext ur git pre-rewrite `b017daf2`; 1🟥/13🔴/8🟠/10🔵/5🟢), MEDVETET hårdladdat med kända fällor; 3 oberoende bedömare fick bara rubrik + text. **Resultat: 13–16/37 exakt (35–43 %), 31–33/37 ±1 (84–89 %); bedömarna nästan identiska → hög reproducerbarhet, missarna = systematiska v4-luckor** (alla redan i §1.1 men ej transkriberade till §1.3): meta-scaffolding-öppning, fluff-svans på kort block, kort+marknad utan pivot, mild importans i konkret instruktionsblock (ska INTE lyfta), EXTREME-stuffing ej räknad, kort+siffra/namn→HUMAN saknades. → **§1.3 uppdaterad till v5 = synkad med §1.1** (ingen per-sida-tuning; §1.3:s egen ≥2-sidor-regel uppfylld). Beslutsregeln oförändrad: ±1-band, facit-först, konfidens <65 = hämta facit. Full data: `lynx-examples.php`.

### 2026-07-02 — Process-review (modellbyte till Fable 5) + state-synk: main-pushen var redan gjord
**Kontext:** ägaren bad om en översyn av LYNX-processen efter byte till Fable 5.
**Fynd + fix (gjort):** playbookens state-markörer var osynkade — §11-loggen sa "main pushad + produktion verifierad (1 jul)" medan LÄGE-bannern, §8, §9 och §11.1-tabellraderna fortfarande sa "väntar main-push". Git-verifierat 2 jul: origin/main = PR #236 → **alla 8 sidor LIVE**; enda commit kvar på staging = d3ce9162 (hudforandringar död debug-rad). Synkade LÄGE + §8 + §9 + §11.1-raderna. Rotorsak: sessionen som loggade main-pushen uppdaterade §11 + §11.1-rubriken men inte raderna/bannern. **Princip framåt: när ett tillstånd ändras, greppa filen efter den gamla frasen (t.ex. "väntar main-push") och synka ALLA förekomster** — bannern/tabellen är det en ny session litar på.
**Process-bedömning (Fable 5): inga regeländringar.** Skyddsreglerna (§13) och facit-först behålls — de kodar verkliga incidenter, inte modellsvaghet; flaskhalsen just nu är LYNX-refresh-data, inte modellkapacitet. Rör inte §1.1–§1.4/§1.2 före första mätningen (omätta hypoteser, §10).
**Föreslaget (väntar grönt ljus, ej gjort):** (a) standardisera adversariell workflow-verifiering (ipl-rosacea-upplägget, fångade 4 äkta fynd) som frivilligt §7-steg för autonomt gjorda sidor; (b) arkiv-policy: när en §11.1-rad är MÄTT och stängd flyttas dess §11-poster till en `lynx-log-arkiv.php` (playbooken är ~82 kB och läses top-to-bottom varje session; arkivera först EFTER mätning — FÖRE-data + prediktioner behövs i mät-loopen); (c) facit-kö: ägaren klistrar in per-block-facit för 2–3 Tier 1-sidor i förväg så sessioner inte blockeras på väntan; (d) frivilligt blindtest-rebaseline av §1.3-prediktorn med Fable 5 mot lynx-examples-korpusen (kan skärpa ±1-bandet; facit-först gäller oavsett); (e) attribuerings-disciplin: håll Fas 2-schema borta från de 8 mätsidorna tills refreshen är mätt (§13.G/H).
*(Arkiverad 8 juli: alla fem förslagen a–e genomförda samma dag. State-synk-principen bor nu i lynx-START §0.)*

### 2026-07-01 — Ägaren pushade MAIN → produktion LIVE (mätstart) + produktions-verifiering
**Milstolpe:** ägaren pushade `main` → alla omskrivna sidor är nu LIVE på produktion (`acnespecialisten.se`). **Mätklockan startar nu** (§10 / §11.1) — nästa steg är LYNX-refresh, sen mät FÖRE→EFTER.
**Produktions-verifiering (8 sidor):** 7/8 rena — HTTP 200, renderat, PHP ok, nytt innehåll live (acne, acne-ansikte, ytliga-blodkarl, behandla-pigmentflackar, om-oss, ipl-rosacea, hudbehandlingar/ipl).
**1 bugg fångad + fixad:** `hudproblem/hudforandringar/index.php` läckte en synlig `Warning: Undefined variable $types_url` (rad 777 = död `<!--<?php echo $types_url ?>-->`-debugrad → hela raden borttagen). **Pre-existerande** (git -S visar gammal commit `06d18987`, ej vår de-AI/H1-rewrite). Fix på staging → **väntar ägarens nästa main-push** för att rensa på produktion.
*(Arkiverad 8 juli, R3: ersatt av 6 juli #13-milstolpen (wave 2 → main, produktions-verifierad). $types_url-fixen bekräftad live på produktion i #12/#13 — "väntar nästa main-push" ovan är överspelat.)*

### 2026-07-01 — Beslut: kör 1 Claude i taget (parallellt övergivet)
**Gjort:** efter dagens parallell-test (planerare + ipl-rosacea-exekutor i samma arbetsträd) beslutade ägaren att **köra en instans i taget**. Skrev om **§0.1** (parallellt → 1 i taget; motivering: delade processfiler §11/§12/lynx-data/lynx-examples/§8–§9 krockar oavsett sid-isolering) och **§12** (parallell-lås → in-progress-markör; check-and-ask kvar men vänt: "du ska vara ensam — upptäcker du annat → fråga ägaren"). Tog bort worktree-/parallell-maskineriet + "flytta logg ur filen"-förslaget (onödigt när 1 i taget). TOC + §-referenser (rad 24/26) + §0.2-snutten uppdaterade.
**Not:** dagens parallell-kollision löstes utan dataförlust — exekutorns commits (149de875 + 3aa45a31) ovanpå planerarens (a1c5e471); planeraren committade scoped, exekutorn stagade explicit. Bevis på att det GÅR men är onödigt kört.

### 2026-07-01 — Plan-review medan exekutor kör (planerare/exekutor-split)
**Kontext:** ägaren kör en **parallell exekutor-terminal på `ipl-rosacea.php`** och bad planeraren se över plan + modeller. Vi trodde LYNX-setupen klar (igår lunch) men den utvecklas vidare → planen är iterativ (nu inskrivet i START HÄR).
**Gjort (låg risk, ägar-riktat):** (1) START HÄR: iterativ-plan-princip + **facit-flöde** (ägaren klistrar in facit → SPARA först i lynx-examples/lynx-data → agera sen) — en lucka ägaren påpekade. (2) §7 steg 2: save-first inskrivet. (3) §12: koordinerings-gap dokumenterat (ipl-rosacea claimades aldrig → claim-tabellen ej självhävdande).
**Föreslaget (väntar grönt ljus, ej gjort):** (a) hårda självkörbara DoD-grindar för AUTONOMA exekutorer — §13.O:s "visa ägaren varje steg" håller inte utan mänsklig blick, ersätt med kvittens i §11 (punkt-count före/efter, grep-bevis på målfraser, `php -l`, staging-200+ny-fras-grep); (b) flytta logg/claim ur den delade filen (merge-konflikt-risk när flera exekutorer kör); (c) standing dispatch-instruktion ägaren klistrar in när en exekutor startas; (d) frys modellbygge tills första LYNX-refreshen mätts; (e) dela playbook i exekutor-kontrakt + planerar-bilaga.
**Modell-status (viktigast):** **noll efter-mätningar än** — §1.1–§1.4 + §1.2 är alla baseline-reverse-engineerade hypoteser, §10-mät-loopen har aldrig körts. 7 sidor väntar på main-push + refresh. Skala inte exekvering på oäkta validering; acne.php = det avgörande A/B-testet.
*(Uppföljning 2 jul: (a) blev §13.E autonom-kvittens, (c) blev §0.2, (b) löstes via 1-i-taget + arkiv-policy, (d) gäller fortfarande, (e) avslogs — se process-review-posten i playbooken.)*

### 2026-07-01 — `ytliga-blodkarl.php` — försök #1 RULLAT TILLBAKA (tog bort för mycket)
**Vad hände:** Påbörjade ett block-svep och skrev om hela stycken (tog bort flera stycken, slog ihop meningar) i Vad/Varför/Vem — ägaren stoppade direkt: "för stora förändringar". `git checkout -- ytliga-blodkarl.php` återställde sidan till original; inget kvar i arbetsträdet på sidan (bara playbook). **Rotorsak:** tolkade "svep alla block" (§13.D) som licens att skriva om varje block i ett svep, i stället för små, målinriktade steg. **Kollade acne-ansikte (som ägaren bad om):** listorna där är faktiskt intakta live — 20 `<li>`, alla besvär-etiketter kvar (Panna/Kinder/Haka/Näsa/Käklinje/Hals, Hormoner/Stress/Preventivmedel/Yttre m.fl.); förra listförlusten fångades före commit. **Åtgärd:** §13.O + START HÄR-bullet omskrivna till den enkla principen (ta inte bort substans, längden fri, steg för steg). En först tillagd "RÖR-INTE-TEST"-mikroregel togs bort igen som för instängande + otydlig (§0/§5 — vi rutar inte in oss). Baseline (§11-tabellen) oförändrad — sidan aldrig deployad. **Nästa gång:** små målinriktade steg mot just de LYNX-AI-tells vi kartlagt (§1.1); visa ägaren varje steg; skydda sökord (§6).

### 2026-06-30 — Playbook-städning (avlägsna över-specificering)
**Gjort:** (1) Tog bort §6-regeln "komma efter sökfras matchar exakt-frasen sämre" — falsk SEO-grund + fastlåsande; ersatt med rytm-hänvisning (§3) + "behåll frasen i texten". (2) La in §0-vakt: bara generella principer hör hemma i filen, engångsiakttagelser är omdöme i stunden. (3) Slog ihop §3:s tre komma-punkter till en, med "enklaste fixen = stryk onödigt komma, omformulera bara vid behov". (4) Rättade motsägelsen "flaggade block" vs "alla block" på flera ställen (§0/§7/§13.D): **hela sidan är arbetslistan, inte LYNX:s flagg-lista** — det var den motsägelsen som lät en tidigare session fastna i "får bara röra flaggade block". (5) Skärpte uppdraget överst: mål = LYNX **helt grönt/korrekt**, varje textblock minst SLIGHT/HUMAN (rättade vilseledande "SIGNIFICANT → MODERATE"). **Varför:** ägaren var nöjd med acne-ansikte och fixen var bara att stryka extra komman utan omformulering — regeln var en överreaktion på ett engångsfall. Princip: vi rutar inte in oss (§5). Minnesfil [[comma-ai-tell]] uppdaterad i linje med detta.

### 2026-06-30 — `acne-ansikte.php` (SIGNIFICANT) — OMSKRIVEN, väntar LYNX-refresh
**Gjort:** Skrev om de **7 flaggade blocken** (banner + Vad/Varför/Orsaker/När/Var = SIGNIFICANT, Hur = MODERATE) → SLIGHT-mål, varierade öppningar, ingen upprepad ", och"-fog, befintliga claims/sökord bevarade. Regler reviderade: organism-namn/ingredienser factual OK (§5), komma-efter-sökfras mjukad till riktlinje (§6), "heuristiker inte stela lagar" (§5). **Cutibacterium acnes STANNAR** (godkänt befintligt — bakteriens namn). LYNX-vyn (3 nya bilder 30 jun) = **samma 10 block**, inga gömda extra. Logga före/efter i lynx-examples.php när LYNX uppdaterats.
**Status:** hela sidan omskriven och klar — se posten "2026-06-30 — acne-ansikte — omskriven (hela sidan klar)" i playbooken.
**Tidigare:** Provomskrivningarna nedan **rullades tillbaka till original** eftersom vi finslipade formel/ramar under tiden (täthet = substans inte kortare §13.N · sökordsbevarande §6 · helt block-svep §13.D). Görs om i ETT rent svep med färdig playbook. LYNX-baseline ovan gäller fortfarande. Att ta med i omskrivningen (lärdomar + checklista):
- Täthet = SUBSTANS, inte kortare text (§13.N). Bevara alla målfraser (§6).
- Block att svepa: banner-description (rad 27), alla ProblemTrivia `content` (rad 62, 70, 82, 101, 117, 141) **och** deras `extended_content`, avslutande CTA (rad 149).
- `extended_content` är bold-label-listor (rad 84–92, 103–109, 119–133, 143–147) → gör om till bunden prosa (§13.D).
- **Behåll** *Cutibacterium acnes* (rad ~72) — godkänt befintligt. Pris → "Från 1595 kr" (rad 220). Konkret image_alt (rad 21). CTA utan "…, så går vi igenom…".
- `$seo_keywords` (rad 10) lämnas orört (sökordslagring).
