<?php exit; /* intern LYNX-arbetsfil – ej webb-serverad, läs i editor/git */ ?>
# LYNX STATUS — var vi står just nu (ENDA STATUSCELLEN)

```
▣ MANIFEST
KIND          AKTIV — ändras varje session. Re-läs ALLTID; lita aldrig på minnet av den.
LADDA-NÄR     vid sessionsstart · efter varje statusbyte · före varje main-push · när LYNX-data kommer in
KANONISK-FÖR  LÄGE (var vi står) · §11.1 bevakningslistan: per-sida mätstatus · live-på-main · FÖRE-baselines · prediktioner
PEKAR-PÅ      lynx-START = router/invarianter/§-KARTA · lynx-backlog = TODO/claims · lynx-models = modellen · lynx-data = rådata per (sida × vy) · lynx-log = historik
```

> **Denna fil är den enda källan för STATUS (ägar-beslut 8 juli).** Den bröts ut ur `lynx-models` (som är `KIND: REGEL` och därför inte ska bära något som ändras varje session) och ur `lynx-START` (som ska vara en tunn dispatcher).
>
> **Lagen, från §0:** ett fakta = en cell; celler pekar, återger aldrig. **Säger någon annan fil något om en sidas status, är den fel — inte den här.** Hittar du en återgivning: ta bort den och peka hit.

---

> **🟢 LÄGE 2026-07-10** *(ny session: läs `lynx-START` först — router, spärr och invarianter. Denna fil säger var vi står; `lynx-backlog` §9 säger vad som är öppet.)*
> - **Mål:** LYNX grönt **utan att skada ranking/trafik**. **RAMEN (verifierad 6 jul):** spaken är SUBSTANS-kvalitet; AI COPY-flaggan är PROXY, Google straffar ej AI-text (lynx-rewrite §1). **SCORE ska INTE jagas** — tak ~75-77 på våra sidtyper, EEAT-badge låst 60 (lynx-score/models).
> - **🎯 Mätt: 6/6 — varje prediktion har träffat.** acne-ansikte 🔴→🔵 · behandla-pigmentflackar 🔴→🔵 (tvåstegs-hopp) · om-oss 🔵 (badge bekräftad 8 juli) · **mogen-hy · solskadad-hy · rhinophyma-rosacea alla 🟠→🔵 den 8 juli.** §1.1 nyckel 1 kausalbelagd. Kvar: pigmentflackar (omanalys).
> - **🧾 rhinophyma har nu ett KOMPLETT FÖRE→EFTER per-block-facit** (8 juli 18:11, V2-crawl grep-verifierad): 8🔴/2🟠/5🔵/1🟢 → **0🔴/2🟠/12🔵/2🟢**, medel 2,06→1,00. Facit + fyra lärdomar i `lynx-examples`. **Konkret empati läser HUMAN; 30-års-siffran kausalbelagd cross-page; definitionsprosa fastnar på 🟠.**
> - **🚨 AI STYLE-TESTET ÄR OBESVARAT, inte besvarat.** SCORE-popupen 8 juli 18:13 gav AI STYLE 70 — men **alla 13 delvärden är identiska med FÖRE** (tredje replikationen). Language 95 stod stilla trots språkfixar, Evidence 76 trots namngivna metoder ⇒ **SCORE-vyn har inte läst V2.** `"Analyzed just now"` är ingen färskhetsuppgift (`lynx-score` slutsats E; mätregel 6). **Diskriminator: när någon av de 12 delsiffrorna rör sig är crawlen ny — först då är AI STYLE ett EFTER.**
> - **✅ ALLA flagg-sidor LIVE PÅ MAIN.** Wave 2 (6 Fas 3 + pigmentflackar + småfixar: milier-pris, Google Meet, d3ce9162) **pushad till main 6 jul (ägarbeslut) → VERIFIERAD LIVE PÅ PRODUKTION**: alla 20 ändrade sidor HTTP 200, 0 PHP-fel, nytt innehåll bekräftat (logg #13 produktions-verifiering; staging-kontrollen arkiverad, `lynx-log-archive` 6 juli #12). §10.0 GSC-gaten passerad på ägarbeslut. **Kvar på dessa = passiv mät-uppföljning (LYNX-refresh + GSC), ej blockerande.**
> - **SEO-vakt §10.0 = SENARE process (ägarbeslut 6 jul):** GSC + Ahrefs görs som eget pass senare (LYNX-prioritet nu pga refresh-fördröjning). Gaten blockerar inte längre; main-push är ägarens beslut. KW-vakt löpande via LYNX-data kvarstår.
> - **pigmentflackar + rhinophyma re-scannade 7 jul (logg #14):** båda "Last update 06 Jul"-vyerna läste PRE-WAVE-2-texten (crawl daterad 2 jul 16:09–6 jul 16:08 via git) — 18/18 + 16/16 block identiska med gamla faciten (determinism #3+#4; typo-fixar flyttar inte betyg) → **V2-rewriterna fortfarande OMÄTTA; EFTER-facit väntar nästa refresh (crawl efter 6 jul 16:08).** SCORE: pigment 73 = medel(84,60) ✓; AI STYLE-FÖRE-baselines satta (pigment 55, rhino 70).
> - **✅ FIL-OPTIMERINGSPASSET §9.0 SLUTFÖRT 8 juli (steg 1–10 + slutgranskning).** Arkitekturen är ratificerad och permanentad i §0: lagen **"ett fakta = en cell, celler pekar — återger aldrig"**, KIND-taggar och `▣ MANIFEST` på alla filer. **Stubben och underlagsfilen raderade.** Kvar, parkerat i §9.3: `lynx-score` HISTORIK-prosan · filnamnskonventionen. **Statusdisciplin: kanonisk cell per statusklass, LÄGE = cache; synka för hand (§0.2).** *(Cachen är den kända sömmen — ägar-idén om EN statuscell ligger i §9.3.)*
> - **✅ CHECK-REVISIONEN STÄNGD 8 juli — löst genom radering (ägarbeslut).** `lynx-verktyg.php` med sina tre checkar är borta. De vaktade §9.0:s omstrukturering, som är gjord; sju mutationstestade fynd visade att de rapporterade grönt på ett filset där 97 % av innehållet var borta. **Bygg inga nya utan att läsa §9 först.** Regeln som blev kvar: *vaktar verktyget ett pass som är klart är det skuld, inte skydd* (§0.1).
> - **Kön är ÖPPEN, inte ordnad (ägarbeslut 8 juli).** §9 listar vad som går att göra; **ägaren väljer utifrån situationen**, du föreslår. Skriv aldrig in ett "nästa" åt honom — det blir ett imperativ som nästa session lyder utan att pröva. *(Öppet just nu: microneedling Fas 3b — ÅTERRULLAD 2×, läs REWRITE-SPEC:en i `lynx-examples` först · §5-brottet "smärtfritt" i 12 filer · övriga Fas 3b · Tier 1-SLIGHT.)*
> - **Öppna ägar-beställningar:** om-oss badge-rad · acne-ansikte FAQ-facitrest · **"Last update"-datum för de 7 flaggade** (§9 — avgör stale badge vs utebliven effekt) · (GSC/Ahrefs = eget senare pass) · boilerplate-sweep "Akne Specialiserade Hudterapeuter" (27 filer — timing-beslut).
> - **Flagg-gruppen oförändrad 8 juli 10:45 → 10 juli 08:42 (femte observationen):** 2 SIGNIFICANT + 5 MODERATE — **alla sju redan omskrivna och live.** Ingen oskriven sida är flaggad; kön i §9 är sidor vi valt, inte sidor LYNX kräver. *(10/7-dumpen: pigmentflackar saknas i MODERATE-blocket men SLIGHT-delen var trunkerad ⇒ badgen fortfarande oläst.)*
> - **Varningar/regler:** 1 Claude i taget (§0.1) · save-first i rätt kolumnfil (filkarta i `lynx-data`) · ny LYNX-skala → färsk-mot-färsk · **attribution kräver observerad delta, ej deploy-timing** · **LYNX uppdaterar per (sida × vy), aldrig i sajt-svep — datera varje cell, EFTER-data droppar in löpande** (§11.1 nedan) · Fas 3-facit REDAN sparat — be inte igen.
>
> *(Banner-regel 6 jul: LÄGE hålls som punktlista, max ~8 rader. Nya detaljer går till §8/§9/§11/§11.1 — här uppdateras bara STATUSBYTEN. Prosaväggen som stod här förut leder till skumläsning; `lynx-log-archive` 6 juli #6.)*

---

## 11.1 Bevakningslista — sidor som väntar på LYNX-refresh (mät-loopen, §10 steg 2)
LYNX skannar bara LIVE och refreshar med delay — **mätklockan startar när ägaren pushar `main`**, inte vid staging. Vi kan inte polla LYNX (ingen export/API); ägaren droppar ny skärmdump när LYNX uppdaterat, då mäter vi delta mot FÖRE-baseline + prediktion. Listan = vad vi väntar på, så inget glöms. **▶ Mätklockan går för alla rader nedan.** Wave 1 live 30 juni–1 juli, wave 2 live 6 juli — allt produktions-verifierat (logg #13), inklusive hudforandringar-warningen (d3ce9162).
**⚠️ MÄTREGLERNA (sex lager, konsoliderade 8 juli — alla sex gäller samtidigt):**
1. **Färsk-mot-färsk.** LYNX bytte version/skala kring 2 juli (39-taket brutet utan våra ändringar). Jämför ALDRIG en färsk analys mot en 30 juni-baseline — läs FÖRE-värdet som osäkert, väg per-block-AI COPY (stabil vy) tyngre än SCORE-deltan, be om färsk FÖRE där det går.
2. **Datera varje cell.** Vyerna refreshar OBEROENDE (**ägarbekräftat 8 juli:** *"score och ai copy uppdateras separat, så en sida kan få ena ändrad utan den andra"*): om-oss hade färsk AI Copy (5 juli) men april-gammal SCORE; ytliga-blodkärl omvänt (färsk SCORE 74, stale badge). Läs "Last update" (AI Copy-vyn) och "Analyzed X ago" (SCORE-popupen) **per vy** innan någon FÖRE→EFTER-slutsats.
3. **UPPDATERINGSENHETEN ÄR (SIDA × VY), inte sajten** (ägarbesked 7 juli; matris-belagt samma dag: fem sidor, fem olika kombinationer). En färsk vy på en sida säger INGET om andra vyer eller andra sidor. EFTER-data droppar in löpande, sida för sida → bevaka kontinuerligt i stället för att vänta på "en stor refresh".
4. **Attribuera FÖRE→EFTER ENDAST när vi faktiskt SER två analyser med OLIKA värden** (en gammal + en ny som skiljer sig). En "Analyzed just now" bevisar varken före eller efter vår ändring — den kan lika gärna vara gammal text omanalyserad. Anta ALDRIG att "nästa analys efter min main-push = EFTER min ändring".
5. **Blank/0 = cellen är mitt i sin uppdatering** (ägarbesked 7 juli), inte trasig. Den sätter sig själv (acne-rygg 0→69, sebo 0→74, acnearr 0→74, milierbehandling –→60 den 8 juli — alla utan omkörning). Logga aldrig 0 som baseline; be aldrig om omkörning; läs av nästa dump.
6. **`"Analyzed just now"` i SCORE-popupen daterar renderingen, INTE crawlen** (belagt 8 juli: rhinophyma, tre popups 6/7/8 juli, alla 13 delvärden bit-identiska, medan AI Copy-vyn samma dag läste V2-texten). **Tidsstämpeln är ingen färskhetsuppgift på någon vy.** Enda giltiga färskhetsbeviset är att **ett värde faktiskt rör sig** — eller, för AI Copy, att *"Last update"* ligger efter main-pushen OCH block-texten matchar filen (grep). Detta skärper mätregel 4 från "anta inte" till "vi vet att den ljuger".

**Positiv följd (belagt på 2 sidor):** orörda block behåller exakt tier över en refresh → per-block-jämförelser är brusfria även över LYNX-versionsbytet (§1.1). Därför är per-block-facit vår pålitligaste mätsignal, och gamla facit gäller för orörda block.

| Sida | Staging-push | Main-push (mätstart) | FÖRE-baseline | Prediktion (§10 steg 1) | Senaste LYNX-analys | Status |
|---|---|---|---|---|---|---|
| acne-ansikte.php | 2026-06-30 | **2026-06-30 (LIVE)** | SCORE "–", AI COPY SIGNIFICANT, KW57; block 6🔴/1🟠/2🔵/1🟢 (22 apr) | AI STYLE ↑, Depth/Evidence/sökord = | **05 jul 2026** | ✅ **MÄTT 6 juli: 🔴→🔵 SLIGHT** (block EFTER 0🔴/1🟠/6🔵/2🟢; logg #1). **Kvar innan raden stängs:** FAQ-facitresten + intro-blockets 🟠 (micro-fix-kandidat) |
| ytliga-blodkarl.php | 2026-07-01 | **2026-07-01 (LIVE)** | SCORE 22, AI COPY SIGNIFICANT, KW172 | AI STYLE ↑ (öppningar+summeringar bort), Evidence ↑ (namngivna maskiner), Depth/E-E-A-T/sökord = | SCORE färsk (6 jul-dump); AI Copy-vyn ? | live på main (PR #236); **6 jul: SCORE 22→74 FÄRSK men badge kvar 🔴 — AI Copy-datum beställt; väntar badge-refresh** |
| behandla-pigmentflackar.php | 2026-07-01 | **2026-07-01 (LIVE)** | AI COPY SIGNIFICANT, SCORE –, AIQ GOOD, KW16; block 25 apr: 8🔴/1🟥/3🔵/1🟢 (medel 2,38) | block-gissningar 🔴/🟠→🔵 (öppningar+svansar), Evidence ↑ (metoder), sökord = | **AI Copy-vyn "Last update: 07 Jul"** (färsk crawl av vår text) | ✅ **MÄTT 7 juli: 🔴→🔵 SLIGHT, tvåstegs-hopp** (per-block medel 2,38→1,38; §1.4-pred ✓; logg #14). Backport-lärdomar i lynx-examples EFTER-sektionen. **Kvar innan raden stängs:** micro-fix-kandidat 4 block (kemisk-kortet 🔴, micro-kortet 🔴, $about-2 + IPL-kortet 🟠 — frysningen hävd) + färsk SCORE |
| hudforandringar/index.php | 2026-07-01 | **2026-07-01 (LIVE)** | AI COPY SIGNIFICANT, SCORE 17, GAPS 3/2, KW8 | block-gissningar 🔴/🟠→🔵 (öppningar+svansar), Evidence ↑, sökord = | – | de-AI:ad + H1-sökord (sep. commit) → staging; live på main (PR #236), debug-rad-fixen d3ce9162 LIVE på produktion (logg #13); **väntar LYNX-refresh** |
| hudbehandlingar/ipl/ | 2026-07-01 | **2026-07-01 (LIVE)** | MODERATE, SCORE –, P.PRICE HIGH, KW19; per-block-facit 22 apr | 13× 🔴/🟠→SLIGHT/MOD; 3× 🔵/🟢 orörda | – | facit-guidad de-AI (Fas 3) → staging; live på main (PR #236); **väntar LYNX-refresh** |
| om-oss.php | 2026-07-01 | **2026-07-01 (LIVE)** | MODERATE, VAL 8, SCORE 17, KW3; block 22 apr: 3🔴/2🟠/6🔵/1🟢 | O01/O04 🟠 + O06/O07/O08 🔴 → SLIGHT/MOD; 🔵/🟢 orörda | **05 jul 2026 (AI Copy); SCORE-analys apr (79 dgr)** | ✅ **MÄTT 6 juli: 0 flaggade block** (EFTER 0🔴/0🟠/10🔵/1🟢 — alla 🔴→🔵; logg #2). ✅ **BADGE BEKRÄFTAD 🔵 SLIGHT (8 juli)** — beställningen från 6 juli besvarad. om-oss räknas nu in i §1.4 (EFTER-medel 0,91 → pred 🔵 ✓). **Kvar:** O01-bannern + FAQ-betygen |
| acne.php | 2026-07-01 | **2026-07-01 (LIVE)** | 🔵 SLIGHT sidnivå, SCORE 39 (Depth77/Ev11/**AISTYLE30**), KW116; block-facit 22 apr | AI STYLE ↑ + Evidence ↑ (sidnivå kvar SLIGHT §1.4); Depth/E-E-A-T = | – | 10 🔴-block omskrivna (husröst-ref lämnad) → staging; live på main (PR #236); **väntar LYNX-refresh** |
| ipl-rosacea.php | 2026-07-01 | **2026-07-01 (LIVE)** | MODERATE, SCORE 39 (CQ68/Ev46/EEAT85/**AISTYLE25**), P.PRICE HIGHEST, KW20; per-block-facit 29 apr | 7× 🔴/🟠→SLIGHT (median→SLIGHT §1.4); AI STYLE ↑↑, Depth/Evidence/E-E-A-T/sökord = | SCORE färsk (6 jul-dump); AI Copy-vyn ? | live på main (PR #236); **6 jul: SCORE 39→60 FÄRSK men badge kvar 🟠 — väntar badge-refresh** (kosmetisk title-attr-typo rad 64 `rosaceabehandlingr`→`rosaceabehandling` fixad) |
| mogen-hy.php | 2026-07-02 | **2026-07-06 (LIVE, logg #13)** | 🟠 MODERATE, SCORE – (gammal 12?), KW9; per-block-facit 22 apr KOMPLETT (5🔴/1🟠/5🔵/3🟢, medel 1,57); AIQ OK (27-frågelista i lynx-questions) | 6 omskrivna block → 🔵-band (bedömar-predikt 3×SLIGHT+3×MODERATE); block-medel →~1,0 → **sidnivå 🟠→🔵**; AI STYLE ↑, Language ↑ (5 språkfixar), Depth/sökord = | – | omskriven + §7.4b-verifierad (5 fynd åtgärdade) → staging 2 jul em; ✅ **MÄTT 8 juli: 🟠→🔵 SLIGHT** (FÖRE-medel 1,57, pred 🔵 ✓). Kvar innan raden stängs: färsk SCORE (–) |
| hudproblem/oonskat-har/ | 2026-07-03 | **2026-07-06 (LIVE, logg #13)** | 🟠 MODERATE; per-block-facit 29 apr (5🔴/2🟠/4🔵/2🟢, medel 1,77); AIQ-frågelista SAKNAS (be ägaren) | 7 omskrivna block → 🔵-band; block-medel →~1,0 → **sidnivå 🟠→🔵**; AI STYLE ↑, Language ↑ (typo/grammatik/alt-titles), Evidence ↑ (Splendor X + Soprano Ice namngivna), Depth/sökord = | – | omskriven + §7.4b-verifierad (3 agenter) → staging 3 jul (verifierad 200 + ny fras); **LIVE på main 6 juli — väntar LYNX-refresh** |
| microdermabrasion.php | 2026-07-03 | **2026-07-06 (LIVE, logg #13)** | 🟠 MODERATE, SCORE 50 färsk, AIQ OK (GOOD→OK-tråden öppen, frågedetalj saknas); per-block-facit 25 jun (5🔴/1🟠/3🔵/2🟢, medel 1,82) | 6 omskrivna block → 🔵-band; block-medel →~1,0 → **sidnivå 🟠→🔵**; AI STYLE ↑, Language ↑ (kongruens/anglicismer), Evidence =, Depth/sökord = | – | omskriven + §7.4b-verifierad (3 agenter) → staging 3 jul (verifierad 200 + ny fras); kortpriser rättade 3 jul em; **LIVE på main 6 juli — väntar LYNX-refresh** |
| hudproblem/bristningar/ | 2026-07-06 | **2026-07-06 (LIVE — gaten passerad på ägarbeslut, logg #13)** | 🟠 MODERATE, SCORE 18 gammal/**63 FÄRSK 6 jul** (ny skala, ren FÖRE-baseline), KW67, CLICKS/WORDS ur nästa dump; block-facit 22 apr: 6🔴/1🟠/5🔵/1🟢 (medel 1,92) | 7 omskrivna block → 🔵-band (bedömare: 2🟢/3🔵/2 🟠-gräns); medel →~0,9 → **sidnivå 🟠→🔵**; AI STYLE ↑, Language ↑, Evidence ↑ (namngivna metoder), Depth/sökord = | – | omskriven + §7.4b-verifierad (3 agenter, 0 allvarliga) → staging 6 jul (verifierad 200 + ny fras); **LIVE på main 6 juli — väntar LYNX-refresh** (§11 6 jul #7) |
| solskadad-hy.php | 2026-07-06 | **2026-07-06 (LIVE, logg #13)** | 🟠 MODERATE; block-facit 23 apr: 6🔴/1🟠/3🔵/1🟢 (medel 2,09); SCORE – (omanalys-kön) | 7 omskrivna block → 🔵-band; medel →~1,0 → **sidnivå 🟠→🔵**; AI STYLE ↑, Evidence ↑ (namngivna metoder) | – | omskriven + workflow-verifierad (8 granskare, tier 7/7 grönt inkl. 2 HUMAN); ✅ **MÄTT 8 juli: 🟠→🔵 SLIGHT** (FÖRE-medel 2,09 = mitt i gråzonen 1,9–2,4, pred 🔵 ✓). Kvar: färsk SCORE (–) |
| rhinophyma-rosacea.php | 2026-07-06 | **2026-07-06 (LIVE, logg #13)** | 🟠 MODERATE; block-facit 22 apr: 8🔴/2🟠/5🔵/1🟢 (medel 2,06); **SCORE 74 FÄRSK (6 juli = ren FÖRE-baseline nya skalan) · AI STYLE-FÖRE 70** | 10 omskrivna block → 🔵-band; **sidnivå 🟠→🔵**; AI STYLE ↑ — **det rena FÖRE→EFTER-testet av de-AI→AI STYLE** | AI Copy **"08 Jul" = V2 ✓** · SCORE-vyn **fortfarande PRE-V2** (8/7 18:13) | ✅ **MÄTT 8 juli, BÅDA NIVÅERNA.** Badge 🟠→🔵. **Komplett EFTER-facit** (18:11): 0🔴/2🟠/12🔵/2🟢, medel 2,06→**1,00** ⇒ §1.4-prediktionen träffade på block- OCH sidnivå. 11/16 block rörda, **5 orörda höll exakt tier** (determinism #5). 🚨 **AI STYLE-testet ÖPPET:** SCORE-popupen 18:13 replikerade alla 13 delvärden ⇒ crawlen är gammal (`lynx-score` slutsats E, mätregel 6). **Vänta på att en delsiffra rör sig — be inte om omkörning.** **Micro-fix-kandidat med färskt facit:** block #2 + #4 (definitionsprosa, enda kvarvarande 🟠) |
| pigmentflackar.php | 2026-07-06 | **2026-07-06 (LIVE, logg #13)** | 🟠 MODERATE, KW244 (största MODERATE); block-facit 22 apr: 8🔴/4🟠/5🔵/1🟢 (medel 2,06); **SCORE 73 FÄRSK (7 juli; CQ 84 / EEAT 60) · AI STYLE-FÖRE 55** (näst lägst på sajten) | 12 omskrivna block → 🔵-band; **sidnivå 🟠→🔵**; jämför AI STYLE mot 55-baselinen | AI Copy-vyn "06 Jul" = PRE-V2-text (logg #14) | **V2 OMÄTT.** 8 juli: sidan SAKNAS HELT i AICOPY-vyn (ej i någon grupp) = pågående omanalys, tom badge — tredje gången mönstret upprepas. **Frånvaro ≠ SLIGHT, attribuera inget.** EFTER väntar att raden kommer tillbaka |
| microneedling.php | – | – | 🔵 SLIGHT; block-facit 22 apr: 4🔴/2🟠/7🔵/3🟢 (n=16, medel 1,44); **FÄRSK FÖRE 8 juli 10:55: VALUE 66 · SCORE 60 · GAPS 0⚡/1💡 · AIQ OK · P.PRICE HIGHEST · KW 63** (WORDS/CLICKS ej synliga — §10.0 p3 ouppfylld) | 6 block (4🔴+2🟠) → 🔵-band; **sidnivå kvar 🔵** = SCORE-vinst, ej flagg-vinst (§1.4) | 8 juli 10:55 | **EJ OMSKRIVEN — återrullad 2× (2 juli ägarbeslut, 8 juli §7.4b underkände).** REWRITE-SPEC + sex verifierade fällor i `lynx-examples` |
| acne-ansikte.php INTRO-EXPERIMENT | 2026-07-06 | **2026-07-06 (LIVE — gaten passerad på ägarbeslut, logg #13)** | intro-blocket 🟠 (EFTER-facit 5 jul); sidbadge 🔵 | intro 🟠→🔵 (importans-wrapper bort + Nedan-skylt) — **dömer §2-intro-hypotesen**; sidbadge kvar 🔵 | – | enblocks-fix → staging 6 jul (verifierad 200 + ny fras); renaste experimentet hittills — 1 block ändrat på mätt sida |

När en rad refreshats: mät (§10 steg 2–3), logga EFTER i §11 + lynx-data.php, förfina modellen (steg 4), backporta (steg 5), töm raden.

---
