<?php exit; /* intern LYNX-arbetsfil – ej webb-serverad, läs i editor/git */ ?>
# LYNX Arbetslogg — ARKIV (avslutade & mätta §11-poster)

> Hit flyttas §11-poster från `lynx-logg.php` när de är stängda: antingen ratificerade i regler/ersatta av nyare poster, eller (för sid-poster) när deras §11.1-rad är MÄTT (arkiv-policy, lynx-logg §11, beslutad 2026-07-02). Kvar i lynx-logg blir en enrads-referens per arkiverad post. Ordning: senaste överst. *(Filnamnen rättade 7 juli — §11 flyttade från playbooken till lynx-logg vid splitten 6 juli.)*

### 2026-07-01 — Beslut: kör 1 Claude i taget (parallellt övergivet)
**Gjort:** efter dagens parallell-test (planerare + ipl-rosacea-exekutor i samma arbetsträd) beslutade ägaren att **köra en instans i taget**. Skrev om **§0.1** (parallellt → 1 i taget; motivering: delade processfiler §11/§12/lynx-data/lynx-examples/§8–§9 krockar oavsett sid-isolering) och **§12** (parallell-lås → in-progress-markör; check-and-ask kvar men vänt: "du ska vara ensam — upptäcker du annat → fråga ägaren"). Tog bort worktree-/parallell-maskineriet + "flytta logg ur filen"-förslaget (onödigt när 1 i taget). TOC + §-referenser (rad 24/26) + §0.2-snutten uppdaterade.
**Not:** dagens parallell-kollision löstes utan dataförlust — exekutorns commits (149de875 + 3aa45a31) ovanpå planerarens (a1c5e471); planeraren committade scoped, exekutorn stagade explicit. Bevis på att det GÅR men är onödigt kört.

### 2026-07-01 — Plan-review medan exekutor kör (planerare/exekutor-split)
**Kontext:** ägaren kör en **parallell exekutor-terminal på `ipl-rosacea.php`** och bad planeraren se över plan + modeller. Vi trodde LYNX-setupen klar (igår lunch) men den utvecklas vidare → planen är iterativ (nu inskrivet i START HÄR).
**Gjort (låg risk, ägar-riktat):** (1) START HÄR: iterativ-plan-princip + **facit-flöde** (ägaren klistrar in facit → SPARA först i lynx-examples/lynx-data → agera sen) — en lucka ägaren påpekade. (2) §7 steg 2: save-first inskrivet. (3) §12: koordinerings-gap dokumenterat (ipl-rosacea claimades aldrig → claim-tabellen ej självhävdande).
**Föreslaget (väntar grönt ljus, ej gjort):** (a) hårda självkörbara DoD-grindar för AUTONOMA exekutorer — §13.O:s "visa ägaren varje steg" håller inte utan mänsklig blick, ersätt med kvittens i §11 (punkt-count före/efter, grep-bevis på målfraser, `php -l`, staging-200+ny-fras-grep); (b) flytta logg/claim ur den delade filen (merge-konflikt-risk när flera exekutorer kör); (c) standing dispatch-instruktion ägaren klistrar in när en exekutor startas; (d) frys modellbygge tills första LYNX-refreshen mätts; (e) dela playbook i exekutor-kontrakt + planerar-bilaga.
**Modell-status (viktigast):** **noll efter-mätningar än** — §1.1–§1.4 + §1.2 är alla baseline-reverse-engineerade hypoteser, §10-mät-loopen har aldrig körts. 7 sidor väntar på main-push + refresh. Skala inte exekvering på oäkta validering; acne.php = det avgörande A/B-testet.
*(Uppföljning 2 jul: (a) blev §13.E autonom-kvittens, (c) blev §0.2, (b) löstes via 1-i-taget + arkiv-policy, (d) gäller fortfarande, (e) avslogs — se process-review-posten i playbooken.)*

### 2026-07-01 — `ytliga-blodkarl.php` — försök #1 RULLAT TILLBAKA (tog bort för mycket)
**Vad hände:** Påbörjade ett block-svep och skrev om hela stycken (tog bort flera stycken, slog ihop meningar) i Vad/Varför/Vem — ägaren stoppade direkt: "för stora förändringar". `git checkout -- ytliga-blodkarl.php` återställde sidan till original; inget kvar i arbetsträdet på sidan (bara playbook). **Rotorsak:** tolkade "svep alla block" (§13.D) som licens att skriva om varje block i ett svep, i stället för små, målinriktade steg. **Kollade acne-ansikte (som ägaren bad om):** listorna där är faktiskt intakta live — 20 `<li>`, alla besvär-etiketter kvar (Panna/Kinder/Haka/Näsa/Käklinje/Hals, Hormoner/Stress/Preventivmedel/Yttre m.fl.); förra listförlusten fångades före commit. **Åtgärd:** §13.O + START HÄR-bullet omskrivna till den enkla principen (ta inte bort substans, längden fri, steg för steg). En först tillagd "RÖR-INTE-TEST"-mikroregel togs bort igen som för instängande + otydlig (§0/§5 — vi rutar inte in oss). Baseline (§11-tabellen) oförändrad — sidan aldrig deployad. **Nästa gång:** små målinriktade steg mot just de LYNX-AI-tells vi kartlagt (§1.1); visa ägaren varje steg; skydda sökord (§6).

### 2026-06-30 — Playbook-städning (avlägsna över-specificering)
**Gjort:** (1) Tog bort §6-regeln "komma efter sökfras matchar exakt-frasen sämre" — falsk SEO-grund + fastlåsande; ersatt med rytm-hänvisning (§3) + "behåll frasen i texten". (2) La in §0-vakt: bara generella principer hör hemma i filen, engångsiakttagelser är omdöme i stunden. (3) Slog ihop §3:s tre komma-punkter till en, med "enklaste fixen = stryk onödigt komma, omformulera bara vid behov". (4) Rättade motsägelsen "flaggade block" vs "alla block" på flera ställen (§0/§7/§13.D): **hela sidan är arbetslistan, inte LYNX:s flagg-lista** — det var den motsägelsen som lät en tidigare session fastna i "får bara röra flaggade block". (5) Skärpte uppdraget överst: mål = LYNX **helt grönt/korrekt**, varje textblock minst SLIGHT/HUMAN (rättade vilseledande "SIGNIFICANT → MODERATE"). **Varför:** ägaren var nöjd med acne-ansikte och fixen var bara att stryka extra komman utan omformulering — regeln var en överreaktion på ett engångsfall. Princip: vi rutar inte in oss (§5). Minnesfil [[comma-ai-tell]] uppdaterad i linje med detta.

### 2026-06-30 — `acne-ansikte.php` (SIGNIFICANT) — OMSKRIVEN, väntar LYNX-refresh
**Gjort:** Skrev om de **7 flaggade blocken** (banner + Vad/Varför/Orsaker/När/Var = SIGNIFICANT, Hur = MODERATE) → SLIGHT-mål, varierade öppningar, ingen upprepad ", och"-fog, befintliga claims/sökord bevarade. Regler reviderade: organism-namn/ingredienser factual OK (§5), komma-efter-sökfras mjukad till riktlinje (§6), "heuristiker inte stela lagar" (§5). **Cutibacterium acnes STANNAR** (godkänt befintligt — bakteriens namn). LYNX-vyn (3 nya bilder 30 jun) = **samma 10 block**, inga gömda extra. Logga före/efter i lynx-examples.php när LYNX uppdaterats.
**Status:** hela sidan omskriven och klar — se posten "2026-06-30 — acne-ansikte — omskriven (hela sidan klar)" i playbooken.
**Tidigare:** Provomskrivningarna nedan **rullades tillbaka till original** eftersom vi finslipade formel/ramar under tiden (täthet = substans inte kortare §13.N · sökordsbevarande §6 · helt block-svep §13.D). Görs om i ETT rent svep med färdig playbook. LYNX-baseline ovan gäller fortfarande. Att ta med i omskrivningen (lärdomar + checklista):
- Täthet = SUBSTANS, inte kortare text (§13.N). Bevara alla målfraser (§6).
- Block att svepa: banner-description (rad 27), alla ProblemTrivia `content` (rad 62, 70, 82, 101, 117, 141) **och** deras `extended_content`, avslutande CTA (rad 149).
- `extended_content` är bold-label-listor (rad 84–92, 103–109, 119–133, 143–147) → gör om till bunden prosa (§13.D).
- **Behåll** *Cutibacterium acnes* (rad ~72) — godkänt befintligt. Pris → "Från 1595 kr" (rad 220). Konkret image_alt (rad 21). CTA utan "…, så går vi igenom…".
- `$seo_keywords` (rad 10) lämnas orört (sökordslagring).
