<?php exit; /* intern LYNX-arbetsfil – ej webb-serverad, läs i editor/git */ ?>
# LYNX LOGG — arbetslogg (händelsehistorik, senaste först)
> Vad vi gjort + varför, per session. Referens/historik — läs vid behov (t.ex. "vad beslutades om X?"). Äldre poster arkiveras till `lynx-log-arkiv.php`. State/nästa-steg bor i `lynx-START.php`, inte här.

## 11. Arbetslogg (vad vi gjort + varför)
Korrelera mot LYNX-refresh. Senaste först. Spara alltid **LYNX-baseline** (FÖRE-värden) per sida så vi kan utvärdera vad ändringen gjorde. Logga även en **prediktion** per omskrivning (vilka SCORE-komponenter vi tror rör sig + varför, §10 steg 1) så vi kan mäta modellens träffsäkerhet när EFTER-värden kommer. All rå LYNX-data sparas i KOLUMNFILERNA (filkarta överst i **`includes/lynx/lynx-data.php`**) — vår manuella "export" eftersom LYNX saknar exportfunktion. Uppdatera vid varje refresh.

**Arkiv-policy (beslutad 2026-07-02):** när en §11.1-rad är MÄTT och stängd (EFTER loggat, modellen förfinad, backport listad) flyttas radens §11-poster till **`includes/lynx/lynx-log-arkiv.php`** — kvar här blir en enrads-referens. Arkivera ALDRIG före mätning (FÖRE-baseline + prediktioner behövs i mät-loopen). Syfte: playbooken läses top-to-bottom varje session och ska hållas läsbar.

### LYNX-baseline — de 4 SIGNIFICANT-sidorna (2026-06-30, före ändring)
| Sida | VALUE | PAGE TYPE | SCORE | GAPS ⚡/💡 | AI COPY | AI QUESTIONS | P. PRICE | KW |
|------|-------|-----------|-------|-----------|---------|--------------|----------|----|
| acne-ansikte.php | 32 | – | – | –/– | SIGNIFICANT | OK | – | 57 |
| ytliga-blodkarl.php | 42 | – | 22 | 2/2 | SIGNIFICANT | OK | – | 172 |
| behandla-pigmentflackar.php | 14 | – | – | –/– | SIGNIFICANT | GOOD | – | 16 |
| hudproblem/hudforandringar/ | 10 | – | 17 | 3/2 | SIGNIFICANT | OK | – | 8 |

### 2026-07-07 #14 — pigmentflackar + rhinophyma re-scannade: BÅDA läste PRE-WAVE-2-texten (V2 omätt) · determinism-replikation #3+#4 · crawlen DATERAD via git · AI STYLE-FÖRE-baselines satta
**Inkommet (11 skärmdumpar 12:15–12:28; allt sparat FÖRST per §0):** pigmentflackar-raden tillbaka i AICOPY-vyn (VALUE 32) + SCORE-popup (73 · CQ 84 · EEAT 60 · AI STYLE 55) + full AI Copy-vy (18 block) · rhinophyma SCORE-popup + full AI Copy-vy (16 block) · hudforandringar-popup (17, "79 days ago", oförändrad) → `lynx-score.php`/`lynx-examples.php`/`lynx-data.php` (snapshot 7 jul). Stänger §9-beställningen "pigmentflackar-raden + AI Copy-vy". Ägarfrågan "skiljer de sig från förra? hur står sig våra bedömningar?" → svar: NEJ resp. UTMÄRKT (fynd 1–3).
**Huvudfynd 1 — båda AI Copy-re-scannerna ("Last update: 06 Jul") läste GAMLA texten, och crawlen är DATERAD:** blocken innehåller 2 jul-språkfixarna ("genetisk", "Detta tillstånd", "naturligt åldrande", "AcneSpecialisten" — live från 2 jul 16:09 via PR #238) men INTE V2-rewriterna (main-merge 1683f85d 6 jul 16:08); grep bekräftar att de scannade 🔴-blocken inte finns i filerna → **crawlfönster 2 jul 16:09–6 jul 16:08 (produktion före wave 2); "LYNX ser bara live" håller; V2-omskrivningarna är fortfarande OMÄTTA.** Prediktionerna 🟠→🔵 står kvar öppna i §11.1.
**Huvudfynd 2 — determinism-replikation #3+#4:** pigmentflackar 18/18 + rhinophyma 16/16 block fick EXAKT samma tier som de gamla faciten (2,5 månader mellan scans) — inkl. 4 typo-fixade block (2 per sida) som behöll sina tiers ⇒ **per-block-betyg är deterministiska; rena typo-fixar flyttar inte betyg; betygsflytt = substansändring.** Bekräftar mätprincipen (lynx-score #0): "Last update" efter vår push ≠ EFTER.
**Huvudfynd 3 — SCORE:** pigmentflackar 73 = medel(84,60) ✓ (prediktor-formeln 14/14) · EEAT-klampen 60 ✓ · Evidence 68 lägsta suben ✓ · rhinophyma-popupen "just now" = IDENTISK replika av 6 jul (74/85/60/70) = SCORE-determinism på oförändrad crawl. **AI STYLE-FÖRE-baselines på färska skalan: pigmentflackar 55 (näst lägst på sajten — första synliga korrelationen AI STYLE ↔ flagg-tyngd) · rhinophyma 70.** Jämför vid nästa refresh.
**Huvudfynd 4 (12:36–12:37-dumparna, 4 st till) — 🎯 behandla-pigmentflackar badge SIGNIFICANT → SLIGHT = EFTER-MÄTNING #3:** badgen var kvar 🔴 i 6 jul-dumpen ("OFÖRÄNDRAD") och är nu 🔵 (VAL 10 · AIQ GOOD · KW13) — observerad delta på vår text (live 1 jul) ⇒ attribuerbar; tvåstegs-hopp 🔴→🔵 förbi 🟠, starkaste badge-flytten hittills. §11.1-raden uppdaterad. Metoden nu 3/3 på mätta omskrivna sidor (acne-ansikte, om-oss, behandla-pigment). **Övriga diffar:** ipl-rosacea GAPS 0/0→3⚡/1💡 (2 jul-"rensningen" ej permanent — konkurrent-relativa tolkningen stärkt; gap-texterna mottagna 12:42 → lynx-gaps) · acne-rygg SCORE 0→69 (0/blank var pågående omanalys/indexering som satte sig själv — **ägarbesked 7 jul: "trasig" är överdrift, blank/0 = LYNX uppdaterar/indexerar**; terminologin rättad i lynx-score/rewrite/START, "be om omkörning" struken ur Fas 3b-raden) · hudbehandlingar/ipl badge kvar 🟠 (crawl-lag) · nya färska SCORE: laser-mot-hudproblem 60, behandla-stora-porer 63 · ambient KW-drift nedåt på orörda sidor (blodprickar 175→171 m.fl.) = ej attribuerbar.
**Huvudfynd 5 (12:41–12:42-dumparna, 7 st till) — behandla-pigmentflackar KOMPLETT per-block-EFTER ("Last update: 07 Jul", färsk crawl av vår text):** 25 apr 8🔴/1🟥/3🔵/1🟢 (medel 2,38) → **7 jul 2🔴/2🟠/8🔵/1🟢 (medel 1,38; §1.4-pred 🔵 = badge ✓)**. 5 av 9 flaggade block nådde 🔵 — men kemisk-kortet 🔴 OFÖRÄNDRAT, micro-kortet 🟥→🔴, $about-2 + IPL-kortet stannade 🟠 ⇒ **sidnivåmålet nått, blockmålet inte helt; micro-fix-kandidat 4 block (frysningen hävd — sidan är mätt).** Backport-lärdomar (lynx-examples EFTER-sektionen): behandlingskortens vinnar-recept = mekanism-verb + konkret trade-off-svans (laser/CryoPen 🔴→🔵); processabstraktion ("främjar cellförnyelse") ≠ mekanism; payoff-parafraser ×3 + vilket-kedjor håller kvar 🔴; konsult-block kräver KONKRETA vi-handlingar ("går igenom dina behov" 🟠 vs "vi tar före-bilder" 🔵 — inom samma sida). Visar även att LYNX crawlar sida-för-sida (denna 7 jul; pigment/rhino ≤6 jul) → wave 2-EFTER kommer löpande. ipl-rosaceas SCORE-popup ("23 hours ago") = identisk med sparad 6 jul-data ✓.
**Kringdata (§0 skärmbilds-principen):** homepage SCORE 28(gammal)→65 UTAN att vi rört den → gammal→färsk-skala-hopp är GLOBALA; aldrig jämföra gammal-FÖRE mot färsk-EFTER (gäller även bristningar 18→63). 4 wave 2-sidor (ipl, oonskat-har, microdermabrasion, solskadad-hy) har SCORE "–" = troligen omanalys-kön → bevakas i lynx-data. /behandlingar.php (redirect, KW 0) har egen SLIGHT-badge — därför syns den i AICOPY-vyn (12:15-frågetecknet löst).
**Åtgärd/status:** ingen sidändring (V2 är redan vår bästa gissning tills EFTER-facit kommer). §9-bevakningen "pigmentflackar borta ur AICOPY-filtret" STÄNGD (löst: omanalys, ägarens metodprincip bekräftad). Nästa aktiva arbete oförändrat: microneedling.php (Fas 3b, block-plan i #2 2 jul em). *(Ägaren aviserade även byte till ultracode-effort för kommande sessioner.)*

### 2026-07-06 #13 — WAVE 2 PUSHAD TILL MAIN + VERIFIERAD LIVE PÅ PRODUKTION → HELA FLAGG-UPPDRAGET LIVE
Ägaren pushade staging→main (origin/main 1683f85d; `origin/main..staging` tomt, alla innehållssidor mergade rent). **Verifierade alla 20 ändrade innehållssidor live på acnespecialisten.se (PRODUKTION, ej staging):** samtliga HTTP 200 + **0 PHP-fel/warning**; nytt innehåll bekräftat med distinkta fraser så vi vet att det inte är cachat-gammalt — pigmentflackar "bruna fläckar på kroppen" + melanom-säkerhetsraden, solskadad "det är den överproduktionen som syns", microdermabrasion 2595/6995/9995 + diamantspets, milier 495 kr (ej 295), fragor-svar/gratis Google Meet-only (FaceTime borta), acne-ansikte "men den går att behandla", **hudforandringar UTAN `$types_url`-warning = d3ce9162-fixen bekräftad på RIKTIG produktion** (warningen syntes bara live), microneedling "marknaden" (ej "markanden"). Deploy ren.
**Status:** hela ursprungliga LYNX-flagg-listan (4 SIGNIFICANT + 10 MODERATE = 14 sidor) nu OMSKRIVEN + LIVE. §10.0 GSC-gaten passerades medvetet på ägarbeslut (main-push = ägarens, §13.A). **Kvar på dessa = PASSIV mät-uppföljning, ej blockerande (sker under/efter semester):** LYNX-refresh per §11.1 (FÖRE→EFTER — endast 2/14 re-mätta hittills: acne-ansikte 🔴→🔵 SLIGHT, om-oss 0 flagg; övriga 12 förutspått 🟠→🔵) + GSC-ranking-koll. **Nästa AKTIVA arbete (ägaren "gå vidare till andra sidor"):** Tier 1-SLIGHT (rosacea/perioral-dermatit, facit saknas) + Fas 3b (microneedling de-AI/portomning/acne-rygg/seborroisk-keratos, facit finns §9).

### 2026-07-06 #12 — FÖRE-SEMESTER-KONTROLL av alla ändrade sidor (ägar-beställd: "lämna sidan i rätt skick") → ALLT GRÖNT
Kontrollpass över de **20 ändrade innehållssidorna** (diff `main..staging`, exkl. `includes/lynx/`-arbetsfilerna). Syfte: verifiera att det vi gjort FUNGERAR + STÄMMER med riktlinjerna innan 3 v semester. Metod = mekanisk regression + §7.6 live + §6 fras-koll + §3 copy-paste-rest (INTE ny djup-§7.4b — den kördes redan per sida vid rewrite).
**Spår A — FUNGERAR (§13.C/§7.6, via staging-URL:er):** samtliga 20 renderar HTTP 200 + full HTML, **0 PHP-fel/warning/500/blankt.** Verifierade: pigmentflackar, rhinophyma-rosacea, solskadad-hy, bristningar, mogen-hy, oonskat-har, microdermabrasion, ipl, om-oss, hudforandringar (**ingen `$types_url`-warning → d3ce9162-fixen bekräftad live**), ipl-rosacea, acne-ansikte (intro-fixen "men den går att behandla" live), ytliga-blodkarl, behandla-pigmentflackar, acne, microneedling. Småfixar bekräftade: milier **495 kr** (inget gammalt 295), milierbehandling 495 (diff), fragor-svar + gratis-hudkonsultation = **endast Google Meet, FaceTime borta**, microneedlings 5 typos rättade.
**Spår B — RIKTLINJER:** (1) mekanisk svep på ADDED lines: **0 em-streck, 0 AI-vokab (§5), 0 summerings-tics** införda. (2) **§6 fras-koll (FÖRE→EFTER-grep av varje fler-ords-`$seo_keywords`-fras):** enda tappen = små de-dubbleringar ur BORTTAGNA marknads-/fyllnadsblock (ipl "ipl behandling" 12→9, solskadad "solskadad hud" 21→18, behandla-pigment "behandla pigmentfläckar" 6→4, m.fl.) — **head-termerna kvar i `$seo_title` + H1 + robust brödtext; 0 rankande fras tappad** (precis den de-dubblering §6 tillåter). (3) **§3 copy-paste-rest:** `$specialist_url_title` ämnesrätt på alla omskrivna sidor; pigmentflackars Åldersfläckar-kort länkar nu rätt (`/aldersflackar.php`, ead4451d landade); "din bokade tid" korrekt grammatik.
**Utestående (ägar-beslut, ej blocker):** de verifierade sidorna på staging (6 Fas 3 + pigmentflackar + småfixar) väntar **main-push bakom §10.0 GSC-gaten** — beslut om att pusha före/efter semester ligger hos ägaren. Dokumenterad §9-rest (ej introducerad av oss): "Akne Specialiserade Hudterapeuter"-särskrivningen (sajtbred sweep, timing-beslut).

### 2026-07-06 #11 — `pigmentflackar.php` OMSKRIVEN (MODERATE-vågen #10, SISTA) → HELA FLAGG-LISTAN KLAR + process-läxa om att kapa
**pigmentflackar (facit 2 jul, KW244 = största MODERATE):** skrev om 8🔴+4🟠. Orsaks-dubbletten (upprepad i 4 block) DIFFERENTIERAD: Varför äger mekanismen, Baserat-på-orsak/område = kategori-ingresser till bild-listorna, När-söka-artikeln slutar upprepa orsaker. Demografiska skal → konkreta öppningar (Vem öppnar med hormoner ej hudton — ägar-feedback), marknads-/importans-fyllnad → mekanism, 3× identisk sälj-boilerplate i extended → 3 OLIKA (metoder / solens roll / plats-hänsyn). Melanom-säkerhetsrad återinförd icke-diagnostiskt ("fläck som ändrar färg/form/storlek → läkare"). Buggfixar: FAQ-rubrik "ärr av finnar"→pigmentfläckar, relaterade-korts url_title/alt (leverfläck-stavning), IPL-kort-syftningsfel, "Det bör noteras"→"Observera", laser-kort de-AI:at, "Baserat på Färg"→gemena.
**⚠️ PROCESS-LÄXA (ägaren stoppade mig):** V1 kapade sidan −456 ord (−11%) genom att stryka extended-sälj-stycken + slå ihop → ägaren: "känns som vi tar bort ganska mycket info?". **Rätt insikt: pigmentflackar = PRIMÄRSIDA (§13.N) → håll full längd via SUBSTANS, kapa inte.** Ägarbeslut: "börja om från början". V2 återställd från HEAD + omgjord disciplinerat: byt fyllnad mot mekanism, håll längd, variera dubbletter istället för att stryka. V2 = −6,6% (mest avdubblering + fyllnad; §7.4b-diff bekräftade 0 UNIKT resonemang tappat; sökfraser bevarade — "bruna fläckar på kroppen" tappades vid en språkfix och återinfördes). **Ägar-kriterium ratificerat: ordminskning OK så länge inget resonemang/sökord/sökfras tappas.**
**§7.4b (workflow, 2 omgångar):** V1-verifiering (4 granskare) → 4 allvarliga (Vem-extended orsaks-upprepning, FAQ-rubrik-ärr, CTA-boilerplate ×3, alt-språkfel) + juridik (melanom-säkerhet borttagen — återinförd). V2-verifiering (3 granskare) → 0 resonemang tappat; upptäckte att JAG infört behandlings-idé-upprepning i 6 block → de-dubblerad till 1. **Kvar för städpass:** FAQ-sektionen (AI-holdout, ej facit-flaggad), typtitel-versalisering, ärr-boilerplate-sweep (§9).
**MILSTOLPE:** hela den ursprungliga LYNX-flagg-listan (4 SIGNIFICANT + 10 MODERATE = 14 sidor) är nu omskriven. 8 live på main (2 mätta → SLIGHT), 6 på staging (väntar main-push). Nästa: LYNX-refresh-mätning per §11.1 + Tier 1-SLIGHT (rosacea/perioral-dermatit, facit saknas).

### 2026-07-06 #10 — FILSTRUKTUR SPLITTRAD (ägarbeslut "optimerat för AI — ladda bara det du behöver")
Gamla monolitiska `lynx-copy-playbook.php` (776 rader, skummades) delad per arbetsläge: **`lynx-START`** (nav/LÄGE/router/regler/backlog §8-9/claims §12), **`lynx-rewrite`** (hantverk: §1.1/1.3/1.4 + §2-§7 + §13), **`lynx-models`** (§1.2 SCORE + §1.5 AIQ + §10 mät + §11.1 bevakning), **`lynx-logg`** (denna, §11). Playbook-filen = kort vägvisar-stub. Radbalans verifierad (773 rader → 4 filer, 0 tappade/dubblerade; varje §-sektion i exakt 1 fil). Filkartan i `lynx-data` uppdaterad; "läs top-to-bottom"-formuleringar → "läs START + router". **Princip: data ≠ tolkning ≠ logg ≠ hantverk — separata filer; en session laddar bara sitt läge.** (SCORE-tolkningen bor tills vidare kvar i `lynx-score` för att inte splittra den från sin rådata; flaggat för ev. flytt till models.)

### 2026-07-06 #9 — ONLINE-VERIFIERING av modellslutsatserna (5 research-agenter + syntes; ägar-beställd "kolla upp online")
Verifierade LYNX/SCORE/E-E-A-T-slutsatserna mot publik SEO-kunskap (full data i `lynx-score.php` "EXTERN VERIFIERING"-blocket). **Bekräftat:** LYNX = bespoke (ingen publik motsvarighet; delaxlar = kända byggstenar); de-AI-metodiken VALIDERAD av 2 oberoende (AI-tells + Googles people-first); Ahrefs ~600k sidor = ingen negativ AI↔ranking. **Korrigerat:** (1) EEAT-60 = troligt hårdkodat golv/artefakt, INTE sidtyps-auktoritet (auktoritet är off-page/sajt-nivå; /varumarken/-lyftet = rikare off-page-signaler); (2) SCORE=medel(CQ,EEAT) nedgraderad från "bergsäker" till overifierbar prediktor (ej styrbar — EEAT-badge summerar inte ens sina egna subs); (3) YMYL: "utan läkare=lägre" → ÄMNESMATCHAD expertis (hudterapeut ÄR expert; Experience egen signal) → §5 i lynx-rewrite; (4) **RAMEN: spaken är SUBSTANS, AI COPY-flaggan är PROXY — Google straffar ej AI-text i sig** → §1 i lynx-rewrite; (5) em-streck aldrig ensam-flagga (bunt). de-AI-REGLERNA oförändrade i sak.

### 2026-07-06 #8 — Fas 3 #8+#9: `solskadad-hy.php` + `rhinophyma-rosacea.php` OMSKRIVNA + SCORE-MODELLEN LÖST
**solskadad-hy (MODERATE-vågen #8):** 6🔴+1🟠 de-AI:ade (UV→melanin-mekanism, demografiskt skal bort, 30-års-pivot); workflow-verifierad (8 granskare, tier 7/7 grönt inkl. 2 HUMAN) → staging. **rhinophyma-rosacea (#9):** 8🔴+2🟠 (konsult-boilerplate ×3 → konkret, hela FAQ:n de-AI:ad, orsak-motsägelse harmoniserad); workflow + juridik-agent (0 allvarliga, alla gränsfall hedgade) → staging. Båda staging-verifierade (HTTP 200 + nya fraser). **SCORE-modellen löst via 13 färska nedbrytningar** (rådata+härledning i `lynx-score.php`): Overall≈medel(CQ-badge,EEAT-badge) 13/13; AI STYLE ute ur Overall; EEAT-badge=60 på nästan allt (bara /varumarken/ 78-88); SCORE-tak ~75-77 på våra sidtyper → **jaga ej SCORE, AI COPY+AIQ är spaken.** **pigmentflackar-mysteriet löst** (ägarbesked: blank = pågående omanalys i steg, ej tier-flytt). Ägar-mätprincip: attribution kräver observerad delta, ej deploy-timing. **Boilerplate-fynd:** "Akne Specialiserade Hudterapeuter" (title-attr) läcker på 27 filer, 4 ämnesfel (aldersflackar/atrofiska-arr/melasma/milier) — loggat som eget §9-spår, ägarbeslut om sweep-timing väntar.

### 2026-07-06 #7 — `hudproblem/bristningar/` OMSKRIVEN (MODERATE-vågen #7) + lärdoms-justeringar acne-ansikte & mogen-hy
**bristningar (facit 22 apr, §7 full process):** skrev om 6🔴+1🟠: **Vad** (lång definition → stramad kausal vandring, alla poänger kvar inkl. färgresa/räfflad yta), **Varför** (definitionsdubbletten → orsaks-ingång "Huden klarar att tänjas, men bara i en viss takt"; **differentierings-beslutet taget autonomt** — AskUserQuestion ställd men obesvarad → valde rekommenderade "behåll båda, differentiera", inom §13.D då endast IHOPSLAGNING krävde ägarbeslut; dubblett-aliaset "även kända som striae" struket), **Vem** (demografiskt skal → gravida/tonåringar leder, "vem som helst" sist), **Var** (cirkulär → buken/brösten leder, "var som helst" sist; foster-detaljen dedupad mot Vem), **artikel 1 p1** (skal → ofarliga+självkänsla+krämer/oljor-konkretion), **artikel 1 p2** (🟠: "tveka inte"-boilerplate bort, "varken för tidigt eller för sent"-trösten RAK per §4.2 — bedömar-/kritiker-konflikt löst till substansens fördel), **artikel 2 p2** (marknads-stapel + "självklara valet" #2 → namngivna metoder CO2-laser/Dermapen/kemisk peeling = Evidence-spak). Lätt hand: laser-kortet (acne.php-🔴-mönstret "avancerad… effektiv lösning" → mekanism-öppning), Behandla-steget ("effektiva" + "snabbt och säkert"-löftet bort per §5-juridik), konsultation "hy"→"hud", 3 extended-block (koherensfelet "Denna störning", translationese "för bristningar att dyka upp"/"källa till självmedvetenhet"→"besväras", kan-staplar, Oxford-komma, felkomma, genetik-dubbletten mot Varför-listan trimmad, ofarliga-summeringen ×4→×3), FAQ (svars-först på riskfaktorfrågan §4.2 + 3 språkfel), ikonen "Aldre"→"Äldre", h2 "Våra hudterapeut"→"hudterapeuter". Meta-description "det"→"dem" i SEPARAT commit (§13.H).
**§7.4b (3 agenter):** blind bedömare: 2🟢/3🔵 + 2 🟠-gränsfall (artikelblocken, konf 60–65 → ordnivå-skärpningar; frihets-CTA:n BEHÅLLEN — kritikern hyllade samma mening som §4.2-ton). Diff-granskare: **0 ALLVARLIGA**, 9 gränsfall → alla åtgärdade (claim-mjukningar "hör till de vanligaste"/"påverkar", Alma Hybrid-parentesen → generisk "CO2-laser" då Fraction CO2 också listas). Helhetskritiker: extended-/FAQ-fynden (fixade); resultat-widgeten visar akne-/rosacea-/ärrbilder under "resultat för bristningar" = ägar-fråga (widget-data, rörs ej §6).
**acne-ansikte (mätt sida, upplåst) — ENBLOCKS-EXPERIMENT:** intro-🟠 fixad: importans-wrappern bort ("…självkänslan, men den går att behandla") + Här→Nedan-skylt; "Slutligen"-tic i Plötslig-extended. Prediktion: intro 🟠→🔵 vid nästa refresh — dömer §2-intro-hypotesen.
**mogen-hy (staging — LYNX har aldrig sett versionen):** 3× "Slutligen" + "Emellertid" + dubbla importans-wrappers + "hjälpa individer"→du-form i extended-block; hedgar återställda ×2 efter diff-granskning. **§13.D-läxa: obetygsatt block ≠ granskningsfritt — extended-blocken missades i rewriten för att facit inte betygsatt dem.**
**§13.E-kvittens:** sökord: bristningar 253→241 (mättad, −12 = avfluffade dubbletter), striae 4→3 (medveten dubblett-strykning, alias kvar ×2), stretchmarks 2→2, "akne i ansiktet" 20→20, "mogen hy" 113→112 (mättad); 0 råa apostrofer; 0 em-/en-streck (rad 84-strecket FIXAT); punkt-count FÖRE=EFTER med 4 motiverade dubblett-trimmar (rad 85-summeringen ×4→×3, "tveka inte", laser-kortets marknadsmening, mor/syster-exemplet); staging verifierad HTTP 200 + nya fraser på ALLA 3 sidor (3:e pollen).
**Prediktion (§10 steg 1):** bristningar block-medel FÖRE 1,92 (n=13) → EFTER ~0,8–1,0 → **sidnivå 🟠→🔵 SLIGHT** (§1.4-estimat: 3 fixar krävdes, 7 gjorda). SCORE: färsk FÖRE-baseline 63 (ny skala) → AI STYLE ↑, Language ↑, Evidence ↑ (namngivna metoder), Depth/sökord =.
**Ägar-frågorna STÄNGDA samma dag (besked 6 jul):** (1) resultat-widgeten är MEDVETEN — ärren är de närmaste resultatbevisen vi har (bristningar är en ärrtyp); flagga inte igen. (2) Alma Hybrid och Fraction CO2 = båda CO2-lasrar men OLIKA maskiner, båda används mot bristningar. **SLUTLIGT ägarbeslut (6 jul, tredje vändan): prosan hålls GENERISK** — "CO2-laser, microneedling och kemisk peeling" utan maskinnamn, för konsekvens (vi namnger inte Dermapen för microneedling i prosa); varumärkes-widgeten på sidan bär maskinnamnen. Evidence-trade-off medveten: maskinnamn i prosa är en §1.2-spak (ipl-rosaceas maskin-block = 🟢-facit) — återbesöks BARA om blockets refresh-betyg visar att det behövs, då med ägarfråga först.

### 2026-07-06 #6 — SEO-VAKT + BANNER-SANERING (ägarbeslut: "målet är fixa LYNX utan att orsaka skada — justera; och fixa väggen")
**Bakgrund (kritisk granskning, punkt 1+6):** (a) mätloopen tittade bara på LYNX-proxyt, inte affären, och 6 jul-scanen visade att omskrivna sidor tappat KW mer än orörda (behandla-pigment −19 %, acne-ansikte −9 %, ytliga −8 % vs orörda ±0–4 % — ej konklusivt men fel riktning); (b) LÄGE-bannern hade vuxit till en ~2 500-teckens prosavägg som riskerar skumläsning.
**NYTT §10.0 SEO-VAKT (absolut):** (1) **GSC-gate före varje main-push** — nästa våg (mogen-hy/oonskat-har/microdermabrasion) hålls på staging tills ägarens GSC-koll på de 8 live-sidorna är grön; skada → §13.F-rollback + push-paus. (2) KW-vakt per scan med tröskel >10–15 % vs stillastående sajtmedian → utred vilka fraser som föll (grep §6-målfraser först). (3) CLICKS + WORDS obligatoriska i §7-baseline. (4) §13.G omskriven: kohort-regeln (död bokstav — 8 sidor live i blandade vågor) ersatt med "vågor + GSC-gate mellan vågorna". §7 steg 7 fick gate-markering; §9 fick GSC-beställningen (⛔-rad) + ytliga-nedbrytningen prioriterad i §1.2-beställningen (post-rewrite SCORE 74 = AI STYLE-spakens A/B-test).
**LÄGE-bannern sanerad:** prosavägg → 8-raders punktlista (mål/mätt/refresh-status/live+staging/nästa/beställningar/varningar) + **banner-regel**: bara statusbyten uppdateras i LÄGE, detaljer bor i §8/§9/§11/§11.1. Allt struket ur bannern verifierades finnas i sin källsektion före strykning.
**Öppen risk-not (ärlighet):** KW-mönstret kan vara brus/säsong — GSC-kollen avgör. Tills den är gjord fortsätter Fas 3-rewrites till STAGING som vanligt (inget stopp för själva skrivarbetet, bara för main-push).

### 2026-07-06 #5 — EXTERN BEST-PRACTICE-IMPORT (ägar-beställd: "ton, hur vi pratar om oss, kolla online, SEO i åtanke")
**Research:** Google Search Central (people-first/E-E-A-T-självskattning), Konsumentverket (skönhetsingrepp-regler + prisinformationslagen 7a §), KO:s före/efter-granskningar (19 kliniker fällda för vilseledande bilder; regeringsuppdrag juni 2026 = SKÄRPNING PÅ VÄG), klarspråkspraxis (du-tilltal, aktiva verb, svars-först). Avstämt mot §2–§6: det mesta var redan täckt (du-tilltal, aktiva verb, gloss, av-skamning, ärlighet, verifierbara siffror, silo/intent) — importen fyller LUCKORNA:
**NYTT §5 ⚖️ Juridik-block (absoluta krav — största gapet):** (1) aldrig riskfritt-intryck (utelämnad riskinfo = vilseledande; KO-praxis); (2) före/efter-bilder får inte vilseleda — gäller även texten runt resultat-widgets; (3) 18-årsgräns injektioner → injektionscopy silo-separerad från tonårs-/elevsidor; (4) priser = bokningssystemets, paket-"Spara" aldrig framställt som rea, överstruket/kampanj kräver 30-dagars lägsta pris (7a § PIL); (5) roaccutan.php-guard (konsumentreklam för receptläkemedel förbjuden — redaktionell + pivot).
**NYTT §4.2 (praxis, ej facit):** skamfritt säljande som princip (sälj på frihet, aldrig skam/rädsla/brådska; problematisera inte normal hud) · svars-först i FAQ (första meningen = svaret — förstärker §1.5 H2 + snippet-praxis) · författarskaps-trade-offen dokumenterad (klinik-E-E-A-T i stället för bylines: SHR/30 år/maskiner/widgets — aldrig påhittade personer) · riskinfo-är-copy-vänlig-principen (konkret imperativ = både lagkrav och LYNX-🔵). §3-checklistan fick riskfritt-/skam-frågan.
**Medvetet EJ importerat:** amerikansk brand-etik-vokabulär rakt av (våra validerade formuleringar som "reparera skadad hud" är facit-🔵 och behålls); "resultat varierar"-disclaimers som hedge-fraser (lagkravet uppfylls med konkret kontext i stället — §1.1-kompatibelt); byline-krav (medvetet vägval emot, se §4.2).
**Käll-URL:er:** developers.google.com/search/docs/fundamentals/creating-helpful-content · konsumentverket.se/marknadsratt-foretag/skonhetsingrepp-och-kosmetiska-produkter-regler-for-foretag · konsumentverket.se/for-foretag/prissattning-och-ta-betalt/prisinformationslagen · konsumentverket.se/pressmeddelande/fore-och-efterbilder-vilseleder-om-plastikkirurgi · regeringen.se/pressmeddelanden/2026/06/konsumentverket-foreslar-atgarder-mot-marknadsforing-av-skonhetsingrepp.

### 2026-07-06 #4 — HELPLANS-GRANSKNING (ägar-beställd: "best practice, mer naturlig mänsklig formulering, annat?")
**Äkta motsägelser mot facit — FIXADE:** (1) **§4.1 Reassurance-beat-keepern rekommenderade ordagrant den fras som fällde acne-ansiktes intro** ("Det viktiga att komma ihåg är att huden kan behandlas" = §1.1-importans-filler). Omskriven: säg trösten RAKT ("Akne i ansiktet går att behandla") — innehållet är keepern, inslagningen är tellen. (2) **CTA-guidningen drog åt två håll:** §3/§4 krävde "resa"-form medan §13.N sa "skriv rakt" — och facit visar rak kort CTA = 🔵 (om-oss). Harmoniserat i §3 + §4: namngiven vinst krävs, "resa"-metaforen är valfri variation. (3) **§2 skylt-observation tillagd:** kort rumslig skylt ("Nedan tittar vi närmare…") satt i 🟢-block, "Här går vi igenom [X] och [Y]"-katalogform i 🟠-introt — föredra den korta rumsliga i intron.
**Stale state — SYNKAT (samma felklass som 2 jul-fyndet):** mogen-hy låg kvar som ÖPPEN rad i Fas 3b trots omskriven 2 jul (dubblettrad, struken med förklaring) · §9.1 Tier 3 sa "ipl-rosacea → staging" (är LIVE) och listade oonskat-har/mogen-hy/microdermabrasion som ogjorda (alla → staging) · §8-raderna fick MÄTT-status (acne-ansikte, om-oss) · §10:s "bröt 39-taket"-rad fick gamla-skalan-brasklapp · §7 steg 1 fick "notera analysdatum per vy".
**Vakter tillagda:** pigmentflackar PAUSAD-markering på alla tre ställen (§9 Fas 3-raden, §9.1 Tier 1 #2, ny §9-bevakningsrad) så ingen session startar KW244-sidan innan mysteriet är löst; §8.1-beslutslucka för om-oss noterad i §9 (beslut väntar 4:e gap-punkten + badge).
**Granskat utan åtgärd:** §5/§6 (inga motsägelser; ramarna håller mot all ny facit-data) · §1.3-rubriken (EFTER-datan stödjer) · §13 (konsekvent) · §4-öppningsbanken (alla mallar konsistenta med §1.1 nyckel 5 — empati-mallarna används i BLOCK, inte intron; §2-varningen täcker) · widget-/Fas 2-besluten (oförändrade).

### 2026-07-06 #3 — MODELLSYNK efter EFTER-mätningarna (ägar-beställd: "kan vi uppdatera våra modeller?")
**Uppgraderat till belagt (≥2 sidor, §1.3-regeln):** (1) **§1.1 nyckel 1 = kausal + replikerad** — 10 omskrivna flaggade block → 9 st 🔵/🟢, 1 st 🟠; EFTER-bevis-noten i §1.1 utbyggd. (2) **Stabilitet: orörda block behåller exakt tier över refresh** (~10 block, 2 sidor) → gamla facit gäller för orörda block (kösidorna behöver INTE nya facit), betygsflytt attribuerbar till textändring — inskrivet i §1.1 + §11.1-mätregeln. (3) **Vyerna refreshar oberoende** (om-oss: färsk AI Copy + april-SCORE; ytliga: tvärtom) → "kolla datum PER VY" tillagt i §11.1-mätregeln + §1.2 punkt 8. (4) **§1.2:** gamla formeln 7/7; AI STYLE-spannet 25↔30 → **20↔30** (om-oss 20 = ny lägsta; ⚠️-raden + spak-kartan synkade).
**Registrerat som HYPOTES (1 sida — ej regel, §0-disciplinen):** intro-/bannerblock-varningen i §2 — acne-ansiktes intro enda missen (🟠): empati-mening + importans-fras + meta-skylt ackumulerar trots konkret krok, medan ren skylt nådde 🟢. Operativ tumregel tills mer data: i intro-block låt krok + skylt bära, importans-fraser bort, empati-lagret till senare block. Testas mot mogen-hy-/oonskat-har-introna vid deras refresh.
**Medvetet OEJ ändrat:** §1.4-gråzonen (inga nya gränsfall — båda mätta sidorna långt under 1,5); §1.3-rubriken (EFTER-datan motsäger inget; bedömar-predikterna träffade); §1.5 (ingen ny AIQ-data). om-oss räknas in i §1.4-statistiken först vid badge-bekräftelse.

### 2026-07-06 #2 — ANDRA EFTER-MÄTNINGEN: om-oss 0 flaggade block (refresh 5 jul) + första om-oss-SCORE-nedbrytningen + pigmentflackar-mysteriet skärpt
**Inkommet (5 dumpar 08:11, save-first → lynx-data leverans 2 + lynx-examples + lynx-score):** alfabetisk Pages-vy (m→p), om-oss SCORE- + GAPS-popup, om-oss AI Copy-vy ("Last update: 05 Jul, 2026").
**Mätning:** om-oss per-block FÖRE 3🔴/2🟠/6🔵/1🟢 → EFTER **0🔴/0🟠/10🔵/1🟢** (synliga; medel ~0,91). Alla tre 🔴 (SHR/erfarenhet/kliniker) → 🔵 + O04 🟠→🔵 = prediktionen träffade; orörda 🔵/🟢 stabila (replikerat från acne-ansikte). **Badge ej direkt synlig i dumpen** (popup skymde kolumnen) men borta ur MODERATE-gruppen + 0 flaggade block → SLIGHT implicerat; **badge-raden beställd som formalitet.** O01-bannern + FAQ-betygen syns inte — be om resten. **O08-läxan bekräftad baklänges:** samma 3 namngivna kliniker som 22 apr fälldes av längd+marknad räddar nu blocket när marknaden är borta (§1.1 nyckel 1, tredje kausala belägget).
**Metodfynd — vyerna refreshar OBEROENDE:** om-oss AI Copy-vy = färsk (5 jul) men SCORE-analysen = "Analyzed 79 days ago" (april). Ytliga-blodkärl har omvända läget (färsk SCORE 74, stale badge) → **Pages-radens kolumner kan ha olika ålder; kolla alltid analysdatum per vy innan FÖRE→EFTER-slutsats** (svarar på gårdagens öppna fråga 3 i princip — datum per sida kvarstår att se).
**Första om-oss-SCORE-nedbrytningen (gammal skala, → lynx-score):** Overall 17 = CQ 57 × EEAT 59 × **AI STYLE 20** / 3640 = 18,5 ≈ ✓ → **multiplikativa formeln 7/7.** AI STYLE 20 = LÄGSTA uppmätta (spannet nu 20–30).
**⚠️ pigmentflackar-mysteriet SKÄRPT:** saknas ÄVEN i alfabetiska vyn (hålet mellan permanent-harborttagning och pormaskar) → verkar ha åkt UR AICOPY-filtret helt (tömd badge/pågående omanalys?), inte bara bytt grupp. **Beställt: URL-sök i Pages + AI Copy-vyn** — KW 244-sidan, styr Fas 3-prio; rör inte pigmentflackar-planeringen förrän detta är löst.
**GAPS-popup om-oss:** samma 3 punkter som 2 jul (redan i lynx-gaps, oförändrade).

### 2026-07-06 — 🎉 FÖRSTA EFTER-MÄTNINGEN: acne-ansikte 🔴 SIGNIFICANT → 🔵 SLIGHT (LYNX-refresh 5 jul, rullande/partiell)
**Inkommet (5 dumpar 07:51, save-first → snapshot i `lynx-data.php` + EFTER-facit i `lynx-examples.php`):** AICOPY-filtrerad Pages-vy + per-block AI Copy-vy för acne-ansikte ("Last update: 05 Jul, 2026").
**Mätning (§10 steg 2–3):** acne-ansikte **SIGNIFICANT → SLIGHT (badge-flytt 2 steg)** · per-block synligt: FÖRE 6🔴/1🟠/2🔵/1🟢 (medel 2,2) → EFTER **0🔴/1🟠/6🔵/2🟢** (medel 0,89) · VAL 32→28 · KW 57→52 · AIQ OK oförändrad · SCORE fortfarande "–". Prediktionen (block-gissningar 🔴/🟠→🔵) TRÄFFADE. **§1.4-medel EFTER-validerad första gången** (0,89 < 1,5 → 🔵 ✓, preliminär tills ev. FAQ-block levererats). **§1.1 nyckel 1 nu KAUSALT belagd:** alla mekanism-omskrivna block gick 🔴→🔵, områdes-blocket 🔴→🟢 — vi ändrade öppningen, betyget flyttade.
**Kvarvarande flagga (micro-fix-kandidat — sidan är MÄTT och får röras igen):** intro-blocket 🔴→🟠, inte 🔵: följer §2-formeln men "För många påverkar den både huden och självkänslan" + "Det viktiga att komma ihåg är att den går att behandla" + "Här går vi igenom"-skylt = ackumulering (§1.3-gradienten ✓). Jfr 🟢-blocket "Nedan tittar vi närmare på varje område" — skylt fäller inte ensam, det är empati-/importans-meningarna före. **Backport-hypotes (§10 steg 5, EJ regel än — 1 sida):** granska intro-/bannerblocken på övriga omskrivna sidor efter samma empati-/importans-mitt när deras refresh kommit.
**Refreshen är RULLANDE:** ytliga-blodkarl SCORE 22→**74** FÄRSK men badge kvar 🔴 (AI Copy-vyn troligen ej omkörd — datum beställt) · ipl-rosacea SCORE 39→**60** dito (badge kvar 🟠) · hudforandringar + behandla-pigment helt orefreshade. **Bonus: bristningar 18→63 + rhinophyma 10→74 = FÄRSKA nya-skalan-FÖRE-baselines för Fas 3-kön** (ej omskrivna = ren omskalning; endast Overall, inga breakdowns → §1.2-testprotokollet fortfarande öppet).
**Öppna frågor (ägaren):** (1) **om-oss + pigmentflackar saknas i dumpens MODERATE-grupp** (alfabetiskt hål mellan mogen-hy och rhinophyma) — tier-flytt eller skuren bild? Skicka raderna. (2) acne-ansikte: fanns fler block under omdömena (FAQ-svar)? Skicka resten för komplett §1.4-poäng. (3) AI Copy-vyns "Last update"-datum för ytliga-blodkarl/hudforandringar/behandla-pigment — är deras SIGNIFICANT stale eller äkta EFTER-kvarstående?
**KW-drift sajtbred** (homepage −11, ytliga −9, acne-ansikte −5, solskadad +2) — även på orörda sidor → ej attribuerbar; bevaka (§13.F), ingen åtgärd.

### 2026-07-03 #2 — `microdermabrasion.php` OMSKRIVEN (MODERATE-vågen #6) — facit-guidad de-AI, §7.4b-verifierad; pris + verktyg rättade efter ägar-facit
**Gjort (facit 25 jun, §7 full process):** skrev om 5🔴+1🟠: **Vad-är-texten** (🔴: marknads-öppning→"hudslipning som föryngrar huden genom att kickstarta dess egen förnyelse" + mekanism; cirkulär summeringssvans bort efter bedömar-fynd), **process p1** (🔴: "noggrant utformad"-marknad + importans-svans→konkret steg-öppning "Behandlingen börjar med en grundlig rengöring"; sökordet återinfört i brödtexten efter diff-granskning), **process p3** (🔴: passiv→aktiv vi, "maximera" bort; serum-syftet återinfört efter diff-granskning), **förberedelse** (🔴: importans-öppning + konsult-boilerplate + trygghets-svans→konkreta vi-handlingar; "erbjuder vi" ÅTERSTÄLLT efter diff-fynd — "börjar vi med" var skärpt processlöfte; ogrundad "hud i bästa skick"-kausalitet ersatt med "hur du förbereder din hud", grundat i går-igenom-allt-claimet), **eftervård p1** (🔴: dubbel importans→imperativ + tidsfönster; "bästa möjliga resultat"-svans→"Hur väl du följer eftervården påverkar också hur bra slutresultatet blir"), **eftervård p2** (🟠: resa/strålande-svansen struken = facit-flaggad fluff; kontakt-CTA:n kvar). Lätt hand (obetygsatta block): $model-kortet ("denna teknik"→vi-röst, "uppmuntrar"-anglicism bort), FAQ1 kongruens ("effektivt"→"effektiv"), FAQ2 ("rekommenderas sessioner"-passiv→"rekommenderar vi behandlingar", "dramatiska"/"progressiv"-anglicismer bort), FAQ4 ("skräddarsys"→"anpassas", §5), FAQ5 ("utan aggressivitet"→"utan att vara aggressiv" — facit-🔵 rad, endast språk), alt/title-typon "Microdermabrasiona ansiktsbehandlingar"→"Microdermabrasion-ansiktsbehandling".
**§7.4b-verifiering (3 agenter):** (i) blind bedömare: block 2/3/6 = 🔵 direkt; block 1/4/5 🟠-gränsfall (konfidens 55) → svans-trimmar på ordnivå (ej omskrivning — §13.O-disciplin). (ii) adversariell diff-granskare: 0 allvarliga, 6 gränsfall → ALLA åtgärdade ("föryngra" åter, "ansiktsbehandling" åter i alt, serum-syftet åter, "erbjuder" åter, hudskick-kausaliteten grundad, huvudsökordet åter i process-brödtext). (iii) helhetskritiker: språkfynd fixade (ovan); process p2 + FAQ5-antitesen lämnade (facit-🔵); specialists alt-variation + results-widget = sajtmönster, lämnade.
**Pris + verktyg (helhetskritiker-fynd, LÖSTA 3 jul em):** kortets prislista var fel — rättad till bokningssystemets 2595/6995/9995 kr (Spara 790/2980 kr; ägar-skärmbild = facit), så båda prislistorna + "Från 2595 kr" stämmer nu överens. "diamantborste"→"diamantspets" i $model-kortet (uppslag: diamantspets är den etablerade termen — diamantklätt munstycke; "borste" förekommer inte i branschen). oonskat-har-frågan om "underarmar" stängd: ägarbesked = nedre delen av armarna, korrekt svenska, ingen ändring.
**§1.5-not:** AIQ GOOD→OK-bevakningen (§9) fortfarande öppen — AI Overview-frågedetaljen för sidan ALDRIG levererad; be ägaren (vilken fråga tappade GOOD?).
**§13.E-kvittens:** sökord grep: microdermabrasion 64→62 (ordet åter i process-brödtexten), mikrodermabrasion 1→1, hudslipning 3→4, exfoliering 2→2, diamantspets 1→1, hyaluronsyra 1→1, föryngrar åter (0→1), ansiktsbehandling åter (2); punkt-count FÖRE=EFTER (1 medveten trim: resa/strålande-svansen = facit-flaggad fluff i 🟠-blocket); 0 råa apostrofer/backslash; 0 em-/tankstreck; diff rör bara microdermabrasion.php (+ playbook).
**Prediktion (§10 steg 1):** block-medel FÖRE 1,82 (5🔴/1🟠/3🔵/2🟢, n=11) → EFTER förväntat ~0,9–1,1 → **sidnivå 🟠→🔵 SLIGHT (§1.4-estimat: 2 fixar krävdes, 6 gjorda)**. SCORE: AI STYLE ↑, Language ↑ (kongruens/anglicism-fixar), Evidence = (kortpriserna rättade till bokningssystemets), Depth/E-E-A-T/sökord =.

### 2026-07-03 — `hudproblem/oonskat-har/` OMSKRIVEN (MODERATE-vågen #5) — facit-guidad de-AI, §7.4b-verifierad
**Gjort (facit 29 apr, §7 full process):** skrev om 5🔴+2🟠: **Vad-content** (🟠: stramad + hirsutism-motsägelsen rättad — "Den överdrivna formen kallas kliniskt för hirsutism"; termen likställs inte längre med normal hårväxt), **Varför-content** (🔴: "en mängd olika skäl"→"framför allt av två skäl: hormoner och gener" + mekanism; "nödvändigtvis" ÅTERINFÖRD efter diff-granskning), **Vem-content** (🔴: demografiskt skal→genetik-hedge-öppning i husröst, "spelar en avgörande roll" bort, av-skamning flyttad till slutet "drabba alla, oavsett kön och ålder"), **Var-content** (🟠: ansiktszonerna leder, "var som helst"-poängen flyttad sist som brygga), **artikel 1 p1+p2** (🔴×2: rakning/vaxning-konkretion leder; importans/antites/marknads-svans bort; rak CTA "Börja med en kostnadsfri konsultation" per §13.N), **artikel 2** (🔴: "pålitlig partner när det kommer till"/toppmodern bort → namngivna lasrar Splendor X + Soprano Ice = Evidence-spak). Lätt hand: FAQ-typo "önsksvärt", FAQ3 "viktigt att konsultera med"→"rådgör med", 3 Oxford-komman (Varför-ext, FAQ4, FAQ5), "Denna X"-parallellism ×2 + translationese ("tjänar biologiska syften"→"fyller en biologisk funktion", "för estetiska skäl"→"av"), titel rad 92 "effektiva laser"→"effektiv", 3 trasiga alt/title-sammansättningar ("oönskat hårhantering/hårbehandling"→"behandling av oönskat hår").
**§7.4b-verifiering (3 agenter):** (i) blind bedömare: Varför + Var = 🔵 direkt; Vad + artikel1-p2 predikterades 🔴 → åtgärdade (Vad stramad, p2 fick konkret CTA-pivot); svansar på a1p1/a2 trimmade. (ii) adversariell diff-granskare: 0 allvarliga, 7 gränsfall → 3 åtgärdade ("nödvändigtvis" åter, "vissa steroider" åter, "ofta i samband med"→"Det händer till exempel i samband med"), resten skippade motiverat (nedan). (iii) helhetskritiker: äkta språkfynd fixade (ovan); banner-/laser-korts-/konsult-korts-kritik SKIPPAD — facit=🔵 trumfar agenttyckande (§13.D).
**Medvetna trimmar (§13.D-motiverade):** Varför-ext summeringssvans ("mängden, texturen och färgen varierar…") struken = 4:e förekomsten av variations-poängen på sidan (Vad äger den; var importans-framad); "ger ett bestående resultat" (a1p1) = inom-blocks-dubblett av "tar bort håret permanent"; "på det sätt som passar dig bäst" (a2) = §5 individualiserings-fluff.
**Skippat (motiverat):** "vanligt estetiskt bekymmer" (normalisering täcks av av-skamningen); "två skäl"-insnävningen OK ("framför allt" + extended listar mediciner/sjukdomar/kosmetika); pre-existerande dubbletter över extended-blocken (graviditet/klimakteriet, mediciner ×3, subjektivitet, zonlistor) lämnade per §13.O (sveprisk); FAQ4/FAQ5-spänningen (formellt korrekt).
**"underarmar"-frågan (granskar-misstanke om felöversatt "underarms"=armhålor — STÄNGD 3 jul em):** ägarbesked = underarmar är nedre delen av armarna, korrekt svenska. Ingen ändring.
**§1.5-not (§7.4a):** AI Overview-frågelista för oonskat-har SAKNAS i lynx-questions (aldrig levererad) — be ägaren om den vid nästa dump-runda; FAQ-svaren fick ändå språkfixar.
**§13.E-kvittens:** sökord grep: oönskat hår 52→50 (mättad sida, alla målfraser kvar), oönskad hårväxt 3→2, hårborttagning 21→21, laserhårborttagning 4→4, hirsutism 1→1, permanent 13→13, PCOS 2→2; punkt-count per block FÖRE=EFTER (3 medvetna trimmar motiverade ovan); 0 råa apostrofer/backslash; 0 em-/tankstreck; diff rör bara index.php (+ playbook).
**Prediktion (§10 steg 1):** block-medel FÖRE 1,77 (5🔴/2🟠/4🔵/2🟢, n=13) → EFTER förväntat ~0,9–1,1 → **sidnivå 🟠→🔵 SLIGHT (AI COPY-flagg-vinst; §1.4-estimatet krävde 2 fixar, 7 gjorda)**. SCORE: AI STYLE ↑, Language ↑ (typo-/grammatikfixar), Evidence ↑ (namngivna lasrar i artikel 2), Depth/E-E-A-T/sökord =.

### 2026-07-02 kväll #8 — Lynx-filerna flyttade till `includes/lynx/` (ägarbeslut) + mogen-hy staging-verifierad
Alla 7 lynx-filer flyttade med `git mv` till **`includes/lynx/`** (fortfarande under includes, ägarens önskan när filerna blev många); interna sökvägsreferenser uppdaterade (bara playbook + examples hade fullständiga sökvägar; korta filnamnsreferenser fungerar oförändrat då filerna är samlokaliserade). Inga kodfiler refererar lynx-filerna. **mogen-hy staging-verifierad** per §7.6/§13.E: HTTP 200 + ny fras i svaret (3:e pollen, ~1 min deploy-lag) + "mogen hy" ×77 renderat → §12-claimen tömd, §9-checkboxen ikryssad.

### 2026-07-02 em #7 — `mogen-hy.php` OMSKRIVEN (MODERATE-vågen #4) + språkfel-svep på 4 kösidor + transkriptionsrättelser
**mogen-hy (facit-guidad, §7 full process):** skrev om de 5🔴+1🟠 (Vad/Varför/Vem/Var-content + artikel 1 p1/p2) → mekanism-/konkret-ledda, kapade retorisk fråga, demografiskt skal, "När vi talar om"-scensättning, konsult-boilerplate + pep-svansar. Lätt hand på 🔵: 2 typos fixade ("elasticitet.Hos", "huvårdsmål"). Obetygsatta buggar fixade (§13.D-helhetsläsning): trasig mening "Hos får du"→"Hos oss får du" (Identifiera-kortet), en-dash i Var-extended, "allmänna hälsa"→"allmän hälsa", grammatik "en genetiska anlag"→"ett genetiskt anlag". **Ägarbeslut under arbetet:** §1.5-gapet "Vad betyder hy?" (score 24) lämnas MEDVETET — ordförklaring hör inte hemma i termen-FAQ:n ("ingen frågar vad hy betyder"); FAQ-svaret fick i stället varierad öppning + kolon→"Tecknen inkluderar" (undvek parallellism mot Vad-blocket).
**§7.4b-verifiering (2 agenter):** (i) blind bedömare: omskrivna block = 3×SLIGHT (60/75/70) + 3×MODERATE (60/55/60) — alla i målband, ingen SIGNIFICANT kvar. (ii) adversariell diff-granskare: **5 äkta fynd, ALLA åtgärdade** — återställde "vill helt enkelt förbättra hudens utseende"-skälet + "aldrig för sent"-halvan; strök opåstådd gener=när/yttre=hur-snabbt-dikotomi (nu "Generna styr mycket av när… Yttre faktorer som sol och livsstil påverkar också hur tidigt och hur tydligt…"); "syns först"→"syns tydligast" + "ligger inte långt efter"→"är också utsatta" (opåstådd tidsordning); "för många påverkar"→"för vissa kan de påverka" (skärpt claim). Gränsfall åtgärdade: torrhets-dubblett struken, "Här kommer"→"Här uppstår". Skippat (motiverat): "det är just detta som syns"-payoff behålls (§4-signaturdrag, facit-🔵 på acne.php).
**§13.E-kvittens:** sökord grep-verifierade (mogen hy 113, rynkor 27, fina linjer 19, åldersfläckar 6, hudens åldrande 7); punkt-count per block FÖRE=EFTER (2 medvetna dubblett-strykningar återställda/motiverade ovan); 0 råa apostrofer/backslash; 0 tank-/em-streck i filen; diff rör bara mogen-hy.php.
**Prediktion (§10 steg 1):** block-medel FÖRE 1,57 (5🔴/1🟠/5🔵/3🟢) → EFTER förväntat ~0,9–1,1 → **sidnivå 🟠→🔵 SLIGHT (AI COPY-flagg-vinst, vågens billigaste)**. SCORE: AI STYLE ↑, Language ↑ (5 språkfixar), Depth/E-E-A-T/sökord =.
**Språkfel-svep 4 kösidor (ägarbesked: "fixa felen nu, AI-uppgiften imorgon"):** rhinophyma ("genetiskto"→"genetisk", "Denna tillstånd"→"Detta") · oonskat-har (4 fel: trasig hirsutism-mening, östrogen-meningen, "området mellan näsan"→"runt näsan", verblös partner-mening + "din individuella hår- och hudtyp") · pigmentflackar ("AcneSpecialistem"→"AcneSpecialisten", "naturlig åldrande"→"naturligt", "behov.Det"→mellanslag) · microneedling ("markanden"→"marknaden", FAQ-typon "micronnedling" som BRÖT sökordsfrasen, "slussas in kanalerna"→"in i kanalerna", "våra…behandling"→"vår", "utseendet"→"utseende"). **Endast språk — ingen de-AI (görs imorgon, attribuerbart per sida).**
**Transkriptionsrättelser i lynx-examples (datahygien):** 3 tidigare noterade "fel" fanns INTE i filerna (solskadad "kan också avgörande" = felläst, texten korrekt; rhinophyma Näsa-"grammatikhaveriet" = felläst, meningen hel; oonskat "hårfollikelarna" = redan rättstavat) — facit-tabellerna korrigerade. **Lärdom: skärmdumps-transkription av brödtext är opålitlig på detaljnivå — verifiera språkfel mot FILEN innan de läggs i rewrite-ammo.**

### 2026-07-02 em #6 — Filstruktur per kolumn (ägar-beställd) + acne-ansikte-frågelistan + homepage-AIQ-beslutet
**Filrefaktor (ägaren: "en fil för varje kolumn så att hela projektet inte blir för stort och att vi kan läsa in de sektioner som behövs"):** skapade **`lynx-questions.php`** (AIQ-frågelistor, 7 sidor), **`lynx-score.php`** (alla SCORE-nedbrytningar, färska + gamla skalan), **`lynx-gaps.php`** (gap-texter; besluten kvar i §8.1); `lynx-data.php` = NAV-FIL med filkarta + Pages-inventeringar/sidregister/kolumn-definitioner/beställningssedel; `lynx-examples.php` = AI COPY-kolumnens fil (oförändrat innehåll). Flyttade sektioner ersatta med pekare; operativa referenser i playbooken synkade (§0, facit-flödet, §7.2, §1.2, §1.5, §11-intro, LÄGE). Äldre §11-poster pekar på gamla platser = historik, filkartan reder ut.
**acne-ansikte AI Overview-lista mottagen (15:12, 27+ frågor → lynx-questions):** ON-TOPIC i kontrast till homepage (H7-kontrastpar!) — zon-frågorna ÄR sidans ämne. Topp-gap: **käklinje-klustret ~56 samlade poäng på POOR/–** trots att sidan har käklinje-sektion → H2 (svaret finns inte i varför-/vad-betyder-form). Fas 2-kandidat #1 (§9) — men FRYST tills mätningen är klar (§13.G). Magnesium-frågan POOR = samma off-topic som mogen-hy (H6 ✓ andra belägget).
**Homepage-AIQ-beslut (ägaren + H7 eniga):** startsidan ska INTE besvara silo-frågorna i sin lista — den äger varumärkes-/förtroendefrågorna + ev. remiss-familjen; silosidorna äger resten. VERY POOR-frågorna (pris/hållbarhet) = billiga FAQ-vinster på respektive SILOSIDA i Fas 2.

### 2026-07-02 em #5 — Officiella kolumn-definitioner mottagna (11 tooltips) → gissningar ersatta
**Inkommet (11 dumpar 15:00, save-first → tabell i lynx-data):** LYNX egna tooltip-texter för VALUE, PAGE TYPE, GAPS, AI COPY, AI QUESTIONS, P.PRICE, EG SCORE, KW, WORDS, CLICKS, STATUS (SCORE-tooltippen saknades — beställd). **Modellkonsekvenser:** (1) **AI COPY sidnivå = "Estimated level of AI-generated content on this page"** — helsides-skattning av kontinuerlig nivå, EJ definierad som aggregat av block-betyg → §1.4:s medel/median = proxys; gråzonen är strukturell, inte databrist (inskrivet i §1.4). (2) **AI QUESTIONS "based on Google SERP"** — §1.5-modellens SERP-bas BEKRÄFTAD; skalan har även Very Poor/Very Good. (3) **GAPS = "compared to top-ranking competitors"** — konkurrent-relativa → GAPS-förändringar får inte attribueras till oss utan gap-texterna (bevakningstråden uppdaterad). (4) **P.PRICE = uppfattat prisläge vs marknaden** ("Lower = cheaper") → ipl-rosacea HIGHEST = uppfattas dyrast i segmentet (ägar-diskussion; §13.I uppdaterad). (5) **EG SCORE** = ny engagemangs-kolumn (visits/time/interactions), hittills tom — bevaka. (6) VALUE = internt relativt; KW = keywords med sidan som landing page; CLICKS = GSC-klick.

### 2026-07-02 em #4 — MODELLANALYS (ägar-beställd före sidarbetet): §1.4 korrigerad, §1.2 stärkt, §1.3 out-of-sample-validerad
**Uppdrag:** "kör en analys av våra modeller och se om den nya informationen lärt oss något." Full analys i `lynx-examples.php` (sektion "MODELLANALYS 2026-07-02"). Fyra resultat:
**(A) §1.4 KORRIGERAD — dagens "medel 11/11" höll inte:** omräkningen av de 6 äldre sidorna (öppen §9-TODO, nu gjord) fällde medel på 3 (acne.php 1,75→pred 🟠, badge 🔵 · behandla-pigment 2,3→🟠, badge 🔴 · hudforandringar 2,08→🟠, badge 🔴). Ställning: **medel 14/17 = median 14/17 på DISJUNKTA missmängder** — 1 jul-sessionen (förkastade snittet) och 2 jul-sessionen (uppgraderade till snittet) hade båda rätt på sin data och generaliserade för snabbt. **Killer: hudforandringar 2,08→🔴 vs solskadad 2,09→🟠** ⇒ badgen ej ren funktion av tier-mixen; alternativ (typvärde, andels-tröskel, ordviktning, exkl. omdömen, ceiling) testade och fällda. §1.4 nedgraderad till arbetsmodell med **gråzon 1,9–2,4**; block-fix-räkningar = estimat; avgörande test BESTÄLLT (§9: färsk same-scan badge + komplett blocklista inkl. FAQ-svar).
**(B) §1.2 stärkt:** bristningar-breakdownen (78 dgr gammal) passar multiplikativa formeln exakt (52×50×25/3640 = 17,9 ≈ 18) → **6/6 på gamla analyser**, medan färska passar medel(CQ,EEAT) → versionsbytes-hypotesen stärkt. Testprotokollet står.
**(C) §1.3 v5 out-of-sample-validerad (blindtest 5):** 20 block ur de 6 nya MODERATE-faciten, 1 färsk bedömare, facit dolt → **55 % exakt / 90 % ±1 / binärt 15/20** — generaliserar (semi-holdout-farhågan 38 % motbevisad). 2-stegsmissar = undergissad marknad/passiv på behandlingsblock, båda konfidens ≤55 → <65-flaggan fångar. Ingen regeländring.
**(D) §1.1-minimalpar (starkaste nyckel 3/5-belägget):** "självklara valet"-blocket i tre versioner — ytliga (utan siffra, lång) 🔴 · rhinophyma (utan siffra, kort) 🟠 · bristningar (med "30 års expertis" + fråge-öppning) 🔵. Nästan identisk öppning, siffran/konkretionen flyttar två steg.
**Bonus (ägar-uppgift):** felaktigt pris 295 kr → 495 kr för enstaka milier-borttagning fixat på milier.php + milierbehandling.php (grep över hela sajten: övriga 295 kr-träffar = vaxning ×3, elevbehandlingar brynform+färg, CryoPen-återbesök på hudforandringar — bedömda utanför scope "milier och andra extraktioner"; CryoPen-priset + milier-paketpriset 1295 kr flaggade till ägaren för verifiering).

### 2026-07-02 em #3 — MODERATE-vågen facit-KOMPLETT (pigmentflackar + oonskat-har) + homepage-/redirect-frågorna lösta
**Inkommet (zoom-dump 14:20 + 9 dumpar 14:22, save-first):** (1) **Homepage-frågan LÖST:** `/` finns i LYNX (VAL 41 · SCORE 28 · GAPS 0/0 · **AI COPY SLIGHT — ej flaggad** · AIQ POOR · KW 298); `/behandlingar.php` = **redirect till /hudbehandlingar/** (ägarbesked; KW 0 → ingen åtgärd, redirect-rad i registret). §9-tråden stängd, §9.1 Tier 1 uppdaterad (homepage-vinst = SCORE+AIQ, ej flagg). (2) **Per-block-facit pigmentflackar.php** (22 apr; 8🔴/4🟠/5🔵/1🟢, n=18, medel 2,06→🟠 ✓) + **hudproblem/oonskat-har/** (29 apr; 5🔴/2🟠/4🔵/2🟢, n=13, medel 1,77→🟠 ✓) → lynx-examples. **MODERATE-vågen har nu facit för ALLA 7 sidor.** §1.4-medel nu **11/11** (median 14/17). Rewrite-ammo: pigmentflackar-typon "AcneSpecialistem" + 3× upprepad orsaks-definition; oonskat-har har 4 trasiga meningar live (mest trasig svenska hittills). Kort-mönstret bekräftat 3:e gången: behandlingskortets ÖPPNING avgör (mekanism 🔵 vs marknad 🔴). Först 🟢 HUMAN på FAQ-rad (oonskat-har).

### 2026-07-02 em #2 — STOR-leverans: 4 MODERATE-facit + HELSAJTS-inventering + sidregister; §1.4 → MEDEL; microneedling påbörjad→ÅTERRULLAD
**Microneedling (Fas 3b):** rewriten påbörjades men ÅTERRULLADES på ägarbeslut (statistiken skulle sammanställas först; `git checkout`, claim tömd). **Bevarad block-plan (återanvänd vid omstart):** (1) banner: tankstreck→komma + NY kur-mening för §8.1-gapet ("Bäst resultat ger en microneedling kur på 3 eller 5 behandlingar, eftersom kollagenet byggs upp gradvis mellan behandlingarna"); (2) desc-p1 🔴: mekanism-öppning, behåll 16-nålar/tusentals-kanaler/serum/alla-hudtyper, döda ", vilket möjliggör"; (3) desc-p2 🔵 lätt hand: "inklusive men inte begränsat till"→"till exempel" (translationese); (4) prep-p1 🔴: konsult-boilerplate→konkreta vi-handlingar; (5) prep-p2 🟠: aktiv imperativ ("Kom inte solbränd..."), importans+svans bort; (6) process-p2 🔴: "speciellt utformade"/"maximera"/strålande-svans bort, grammatikfel "slussas in kanalerna" rättas, rodnad-är-normalt behålls; (7) aftercare-p1 🔴: importans-öppningen (ren meta) bort, imperativ, 24-timmar/smink/smutsiga-händer kvar; (8) aftercare-p2 🟠: "undvika"→"Undvik", "bastu, och"→"bastu och", "av yttersta vikt"/"rekommenderas att" bort, SPF/milda-produkter/fuktbalans kvar; (9) brands: typo "markanden"→"marknaden"; (10) kort-grammatik: "våra resultatinriktade microneedlingbehandling"→"vår...", "bristningarnas utseendet"→"utseende"; (11) FAQ §1.5: topp-frågan "Vad är microneedling bra för?" (score 25, OK) — svaret kompletteras med pigmentfläckar/bristningar/aktiv acne (sidans egna behandlingar); FAQ-typo "micronnedling"→"microneedling" (typon BRYTER sökordsfrasen "microneedling resultat"). Aftercare-p3 🔵 med "microneedling kur" lämnas orörd.
**Leverans (21 dumpar, save-first §0):** (1) **Per-block-facit ×4** → lynx-examples: solskadad-hy 6🔴/1🟠/3🔵/1🟢 · rhinophyma 8🔴/2🟠/5🔵/1🟢 (2 live-grammatikhaverier, bl.a. trasig mening i Näsa-blocket) · microdermabrasion 5🔴/1🟠/3🔵/2🟢 · bristningar 6🔴/1🟠/5🔵/1🟢. MODERATE-vågen har nu facit för 5/7 — SAKNAS: pigmentflackar + oonskat-har. (2) **§1.4 UPPGRADERAD median→MEDEL** (nya datan avgjorde: medel 4/4, median 2/4 — totalt medel 9/9, median 12/15; avrundningsregeln preciserad: standardavrundning, ,5 uppåt). (3) **Helsajts-inventering** (5 dumpar): AICOPY-flaggorna OFÖRÄNDRADE → ingen refresh på de 8 omskrivna än; **sidregister byggt** (ägar-beställt: alla LYNX-sidor ska gås igenom) — i-LYNX-lista + saknas-lista + i-LYNX-men-ej-i-repot i lynx-data; **scope: allt under /studentrabatt/ = drafts, exkluderas** (ägarbesked). (4) Nya bevakningstrådar (§9): homepage-raden/rad 15, powerlite-photonova (i LYNX, ej i repot), hifu (ny, ej i LYNX än), om-oss gap-popupens 4:e punkt. (5) bristningar SCORE 18-breakdown (78 dgr gammal) + om-oss gap-texter (remiss/vårdkö, hudläkar-skillnad, prisinfo) → lynx-data.
**Modell-observationer (nya facit, ej kodifierade — §1.3:s ≥2-sidor-regel):** "det självklara valet"-block MED 30-års-siffra + fråge-öppning = 🔵 (bristningar) vs UTAN siffra = 🟠 (rhinophyma) → siffran/pivoten gör skillnaden (stödjer nyckel 3/5). FAQ-rader kan bära EGNA betyg (🔵 ×3 sidor — första gången). Artefakt-block betygsätts ("0 2" = 🔵 på solskadad).

### 2026-07-02 em — mogen-hy KOMPLETT: facit bekräftat + AI Overview-lista (27 frågor) → §1.4 första missen + medel-hypotes + §1.5 H6
**Inkommet (3 dumpar 13:03, save-first):** (1) **Slutet av blocklistan** (scrollbar i botten — inget saknades): facitet VAR komplett, sista blocket = obetygsatt FAQ-titel. → §1.4-mismatchen STÅR: median 🔵 vs sidnivå 🟠 = modellens FÖRSTA miss (**10/11**). **Medel-hypotes registrerad** (viktat medel avrundat mot värre → 🟠 ✓ på mogen-hy, träffar även de 4 nya facit-sidorna) — omräkning av de 6 äldre = §9-TODO. (2) **AI Overview Ranking mogen-hy (27 frågor)** → lynx-data: första sidan med POOR-frågor (3 st, alla off-topic) och första utan GOOD → **ny §1.5 H6** (POOR = inget svar alls, inte dåligt svar; off-topic-POOR åtgärdas ej — silovakt §5); äkta gap = "Vad betyder hy?" (score 24, OK).

### 2026-07-02 — mogen-hy-facit + AICOPY-Pages-lista mottagen (tredje leveransen idag; ENDAST SPARAD, inget agerat — låg usage i sessionen)
**Inkommet (6 skärmdumpar, save-first §0):** (1) **Per-block-facit /mogen-hy.php** (22 apr-text) → `lynx-examples.php`: synligt 5🔴/1🟠/5🔵/3🟢 (n=14) — **⚠️ möjligen TRUNKERAT** (dumparna slutar mitt i FAQ-listan) → **be ägaren om resten innan §1.4-statistiken röres**; median på synliga block = 🔵 men sidnivå = 🟠 → FÖRSTA möjliga §1.4-mismatchen, PRELIMINÄR tills komplett facit. Rewrite-ammo: 2 grammatikfel + 2 typos live. (2) **Pages-tabell AICOPY-filter (13 rader)** → `lynx-data.php`: ingen refresh på omskrivna sidor (§11.1-bevakningen fortsatt öppen); GAPS rensade på ytliga-blodkarl + ipl-rosacea; microdermabrasion AIQ GOOD→OK. **Åtgärd nästa session:** mogen-hy in i facit-kön (§9), komplett blocklista beställd.

### 2026-07-02 — Konsistens-audit (ägar-beställd, 2 oberoende granskare): 18 fynd → 10 äkta fixade, 8 avfärdade
**Kontext:** ägaren misstänkte interna logiska fel efter många iterationer. Två granskare svepte hela filen med olika linser.
**Status-linsen (8 fynd, 5 äkta):** pigmentflackar KW238→244 (3 ställen; lynx-data = källa) · §9 Fas 1-raden för hudforandringar hade missats i morgonens state-synk ("→ staging" trots LIVE — samma felklass igen!) · §11.1-raden fick debug-rad-not · §8.1 sebo-status uppdaterad (OBS: 2 jul-scanen visar GAPS 0/0 — LYNX flaggar inte längre gap-punkterna; besluten kvarstår frivilliga) · Fas 3 "parallellt"→"löpande" (§0.1-vokabulär).
**Modell-linsen (10 fynd, 5 äkta):** §1.2-brödtexten sa fortfarande "VALIDERAD" + imperativ ("Bryt 39 = höj AI STYLE") trots OMPRÖVAS → rubrik mjukad till 30 jun-modell + HISTORIK-divider infogad över hela brödtexten · "Fyra nycklar" var fem → rättat + nyckel 1 fick tolknings-pekare till nyckel 5 · §1.3 regel 3 sa "SIGNIFICANT." blankt före gradienten → "SIGNIFICANT som default — gradienten avgör" · §1.4 "AI STYLE-taket" → "-komponenten (§1.2 OMPRÖVAS)". Avfärdade: block- vs sidnivå-"paradoxen" (§1.4 förklarar den uttryckligen), tak-vs-spak (olika begrepp), median-flagga vs no-regression-SCORE (olika dimensioner), m.fl.
**Lärdom (generell princip, ej mikroregel):** iterativa påbyggnader lämnar gamla IMPERATIV kvar när nya data underkänner premissen — vid varje modellrevision: greppa filen efter modellens nyckelfraser och tagga/uppdatera ALLA förekomster (samma princip som state-synk-regeln från i morse, nu bevisad två gånger samma dag).

### 2026-07-02 — Blindtest 4 (ägar-beställt test av förbättrade modeller): AI-modellen mätbart bättre + gradienten skärpt
**Upplägg:** 2 färska bedömare med v5+gradient-rubriken; 37 regressions-block (identiska med test 3) + 16 semi-holdout (ociterade block från de 4 nya sidorna). **Resultat: regression 57–62 % exakt (upp från 35–43 % med v4), ±1 89–92 %; 4 av 5 gamla tvåstegsmissar FIXADE** (meta-scaffolding, mild-importans, fluff-svans, kort+marknad; EXTREME-räkningen kvarstår hos 1 av 2). Semi-holdout: 38 % exakt / 88 % ±1. **Ny systematisk miss hittad + fixad direkt:** gradienten förlät fluff så fort konkretion fanns någonstans — facit räknar över HELA blocket → §1.3-gradienten skärpt (staplade öppningsfraser / fluff i båda ändar / lång+svans → 🔴; demografisk skal räddas aldrig). **SCORE-modellen kan inte testas lokalt** (bara LYNX producerar breakdowns) — falsifierbart protokoll registrerat i §1.2, testas mot nästa färska nedbrytningar ägaren skickar. Äkta out-of-sample-validering = första nya facit-sidan. Full data: `lynx-examples.php`.

### 2026-07-02 — AI QUESTIONS-detalj mottagen (4 sidor) → NY §1.5-modell (hypotes)
**Inkommet (4 skärmdumpar, sparade i lynx-data FÖRST):** "AI Overview Ranking" för micro/porto/acne-rygg/sebo — 14 frågor per sida med SCORE-viktning + OPTIMIZED-status (beställningssedel punkt 3 → 🟡). **Ny §1.5** med H1–H5: FAQ-titel räcker inte för GOOD (micro score-25-frågan är sidans FAQ-titel men bara OK); svaret måste matcha frågans form (acne-ryggs hur-varianter GOOD, orsaksfrågor OK); grannfrågor → ägarsida + länk (§5); hemma-frågor = återkommande topp → ärlig "ingen hemmakur" + klinikpivot; YMYL-angränsande kan nå GOOD i kosmetisk ram (sebo cancer-frågan). **Operativ följd: FAQ-svar = trippelspak (AI QUESTIONS + median §1.4 + AI STYLE) → Fas 2:s värde höjs ytterligare; Fas 3b-sidorna har nu sina frågelistor som svars-spec.** TOC kompletterad (§1.3–§1.5 saknades).

### 2026-07-02 — Modellöversyn på POSITIV-datan (ägar-beställd): §1.1 nyckel 5, §1.3-gradient, §1.4 additions-spak
**Kontext:** korpusen var negativ-tung (facit mest från SIGNIFICANT-sidor vi skrev om); de 4 nya faciten är SLIGHT-tunga (23🔵/9🟢 av 53 block) = första systematiska bilden av vad som HÅLLER block gröna.
**Uppdaterat (allt belagt på ≥2 sidor):** (1) **§1.1 nyckel 5:** en enstaka fyllnads-/importansfras fäller inte — ackumuleringen fäller; fyllnadsfras + konkretion direkt i mening 1–2 = 🔵; konkreta processblock tål flera marknadsord (portomning); CTA-pivot-räddningen gäller även behandlingskort (3 sidor); FAQ-svar kan nå 🟢; 🔵↔🟢 = brus utan operativ betydelse. (2) **§1.3 regel 3 → gradient:** importansfras + konkretion direkt = SLIGHT · + svans = MODERATE · + generiskt = SIGNIFICANT ("räkna fyllnad vs konkretion, inte frasen"). (3) **§1.4 additions-spaken:** medianen flyttas även genom att LÄGGA TILL korta konkreta block (FAQ-svar/pris/maskin-rader) → **Fas 2 är också en AI COPY-flagg-spak**, inte bara AI QUESTIONS (§13.N-vakt: äkta innehåll, ej padding). (4) **§1.2 +2 observationer:** konkret procedur-copy skårar högt på nya skalan (sebo CQ85/AI50, porto subs 95–98); möjligt att AI STYLE inte längre ingår i Overall (medel(CQ,EEAT) passar 2/3 exakt) — skulle krympa de-AI:s SCORE-payoff; avgörs med fler breakdowns.
**Ej ändrat:** §1.2-formeln (fortsatt OMPRÖVAS — ingen ny formel på 4 punkter), ±1-bandregeln, facit-först, §13-skydden. Noterat men EJ kodifierat (1 sida): antites i kort konkret block fäller inte (portomning 🟢-blocket).
**Strategisk följd:** rewrite-jobbet på 🔵-sidor (Fas 3b) = kirurgi på 2–4 🔴-block + typos, INTE genomskrivning — sidornas struktur skyddar redan medianen.

### 2026-07-02 — STOR facit-leverans (4 sidor) + färska SCORE-analyser → §1.2 OMPRÖVAS, §1.4 nu 10/10
**Inkommet (15 skärmdumpar; allt sparat i lynx-data + lynx-examples FÖRST per §0):** per-block-facit för **microneedling** (22 apr: 4🔴/2🟠/7🔵/3🟢), **portomning** (24 jun: 2🟠/5🔵/2🟢), **acne-rygg** (25 apr: 3🔴/1🟠/11🔵/1🟢), **seborroisk-keratos** (25 apr: 2🔴/2🟠/5🔵/3🟢) + färska SCORE-nedbrytningar (micro 50, porto 60, sebo **74 med AI STYLE 50**) + acne-rygg SCORE 0 = ALLA komponenter 0 + gap-texter (micro ×2, acne-rygg ×2, exosomer-gapet).
**Modellfynd:** (1) **SCORE 0 = trasig/tom analys** → omkörning krävs innan bedömning. (2) **"39-taket" brutet utan våra ändringar** → ny LYNX-version/skala trolig; 30 jun-baselines EJ jämförbara — mät färsk-mot-färsk (§11.1-varning tillagd). (3) AI STYLE 0 på färska = troligen obereäknad; sebo 50 = första uppmätta >30. (4) Aggregering ändrad/oklar (EEAT-badge 60 ≠ sub-medel; Overall ≈ medel(CQ,EEAT) passar 2,5/3) → **§1.2 markerad OMPRÖVAS; ingen ny formel förrän fler färska breakdowns.** (5) **§1.4 median: 4 nya träffar → 10/10** — vår starkaste modell. *(HISTORIK: 10/11 sedan mogen-hy-missen 2 jul em → medel-hypotes, §1.4.)* (6) §1.1/§1.3-stöd i nya facit: sebo lång-definition-utan-mekanism = 🔴 (ytliga-mönstret ✓); acne-rygg kort+marknad utan pivot = 🔴 (v5 regel 2 ✓); **ny nyans: "flera olika faktorer"-öppning fäller INTE när konkretiseringen kommer direkt i mening 2** (acne-rygg 🔵 — noterad, ej regeländring än, §1.3:s ≥2-sidor-regel).
**Beslut (ägarens, 2 jul):** micro + porto togs först (högst VALUE i default-sortering), acne-rygg + sebo också klara; **denna session = data + modellöversyn, sidfixarna görs i SEPARAT session** → **Fas 3b-kö skapad i §9** (4 sidor med rewrite-ammo: 5 live-typos/grammatikfel + §8.1-gapbeslut). **Exosomer-TODO** tillagd i §9 (gated på klinikens lansering). Fler sidor aviserade från ägaren.

### 2026-07-02 — Optimeringarna genomförda (a–e) + blindtest 3 → §1.3 v5
**Gjort (ägarens grönt ljus på alla fem förslagen):** (a) **§7.4b** adversariell verifiering standardiserad (bantad: 1 bedömare räcker, se nedan); (b) **arkiv-policy** i §11 + `lynx-log-arkiv.php` skapad; 5 ratificerade/ersatta §11-poster arkiverade (~8,5 kB — playbooken krymper vidare mot ~55–60 kB när mätrundan stänger sid-posterna); (c) **facit-kö** inskriven i §9.1; (d) **blindtest 3** kört (nedan); (e) **Fas 2-attribueringsvakt** i §9.
**Blindtest 3 (Fable 5 + v4-rubrik, ofuskat):** 37 block ur korpusen (fulltext ur git pre-rewrite `b017daf2`; 1🟥/13🔴/8🟠/10🔵/5🟢), MEDVETET hårdladdat med kända fällor; 3 oberoende bedömare fick bara rubrik + text. **Resultat: 13–16/37 exakt (35–43 %), 31–33/37 ±1 (84–89 %); bedömarna nästan identiska → hög reproducerbarhet, missarna = systematiska v4-luckor** (alla redan i §1.1 men ej transkriberade till §1.3): meta-scaffolding-öppning, fluff-svans på kort block, kort+marknad utan pivot, mild importans i konkret instruktionsblock (ska INTE lyfta), EXTREME-stuffing ej räknad, kort+siffra/namn→HUMAN saknades. → **§1.3 uppdaterad till v5 = synkad med §1.1** (ingen per-sida-tuning; §1.3:s egen ≥2-sidor-regel uppfylld). Beslutsregeln oförändrad: ±1-band, facit-först, konfidens <65 = hämta facit. Full data: `lynx-examples.php`.

### 2026-07-02 — Process-review (modellbyte till Fable 5) + state-synk: main-pushen var redan gjord
**Kontext:** ägaren bad om en översyn av LYNX-processen efter byte till Fable 5.
**Fynd + fix (gjort):** playbookens state-markörer var osynkade — §11-loggen sa "main pushad + produktion verifierad (1 jul)" medan LÄGE-bannern, §8, §9 och §11.1-tabellraderna fortfarande sa "väntar main-push". Git-verifierat 2 jul: origin/main = PR #236 → **alla 8 sidor LIVE**; enda commit kvar på staging = d3ce9162 (hudforandringar död debug-rad). Synkade LÄGE + §8 + §9 + §11.1-raderna. Rotorsak: sessionen som loggade main-pushen uppdaterade §11 + §11.1-rubriken men inte raderna/bannern. **Princip framåt: när ett tillstånd ändras, greppa filen efter den gamla frasen (t.ex. "väntar main-push") och synka ALLA förekomster** — bannern/tabellen är det en ny session litar på.
**Process-bedömning (Fable 5): inga regeländringar.** Skyddsreglerna (§13) och facit-först behålls — de kodar verkliga incidenter, inte modellsvaghet; flaskhalsen just nu är LYNX-refresh-data, inte modellkapacitet. Rör inte §1.1–§1.4/§1.2 före första mätningen (omätta hypoteser, §10).
**Föreslaget (väntar grönt ljus, ej gjort):** (a) standardisera adversariell workflow-verifiering (ipl-rosacea-upplägget, fångade 4 äkta fynd) som frivilligt §7-steg för autonomt gjorda sidor; (b) arkiv-policy: när en §11.1-rad är MÄTT och stängd flyttas dess §11-poster till en `lynx-log-arkiv.php` (playbooken är ~82 kB och läses top-to-bottom varje session; arkivera först EFTER mätning — FÖRE-data + prediktioner behövs i mät-loopen); (c) facit-kö: ägaren klistrar in per-block-facit för 2–3 Tier 1-sidor i förväg så sessioner inte blockeras på väntan; (d) frivilligt blindtest-rebaseline av §1.3-prediktorn med Fable 5 mot lynx-examples-korpusen (kan skärpa ±1-bandet; facit-först gäller oavsett); (e) attribuerings-disciplin: håll Fas 2-schema borta från de 8 mätsidorna tills refreshen är mätt (§13.G/H).

### 2026-07-01 — Ägaren pushade MAIN → produktion LIVE (mätstart) + produktions-verifiering
**Milstolpe:** ägaren pushade `main` → alla omskrivna sidor är nu LIVE på produktion (`acnespecialisten.se`). **Mätklockan startar nu** (§10 / §11.1) — nästa steg är LYNX-refresh, sen mät FÖRE→EFTER.
**Produktions-verifiering (8 sidor):** 7/8 rena — HTTP 200, renderat, PHP ok, nytt innehåll live (acne, acne-ansikte, ytliga-blodkarl, behandla-pigmentflackar, om-oss, ipl-rosacea, hudbehandlingar/ipl).
**1 bugg fångad + fixad:** `hudproblem/hudforandringar/index.php` läckte en synlig `Warning: Undefined variable $types_url` (rad 777 = död `<!--<?php echo $types_url ?>-->`-debugrad → hela raden borttagen). **Pre-existerande** (git -S visar gammal commit `06d18987`, ej vår de-AI/H1-rewrite). Fix på staging → **väntar ägarens nästa main-push** för att rensa på produktion.

### 2026-07-01 — `ipl-rosacea.php` (MODERATE, Fas 3, KW20, SCORE 39, P.PRICE HIGHEST) — FACIT-GUIDAD de-AI, klar → staging
**Gjort (facit 29 apr, v4 §1.3 + adversariellt workflow-verifierad):** Skrev om de 7 block facit rated 🔴/🟠 (desc-p2 "inte bara X utan Y"+marknadssvans; Inför-p1 konsult-boilerplate; Inför-p2 "det är viktigt att"+lång; Process-p2 passiv/generisk procedur; Process-p3 hedge-stapel+boilerplate-svans; Eftervård-p1 importans-filler; Eftervård-p2 passiv "rekommenderas det att"+lång) → ledde med mekanism/konkret + aktiv imperativ, kapade antites/marknad/importans/passiv. **LÄMNADE de 4 🔵/🟢** (desc-p1, Process-p1, Eftervård-p3, Märken-raden) — facit=OK (§13.D-disciplin). Bevarat: 3 interna länkar (rosacea/rosaceabehandling/ipl-ytliga-blodkarl), alla priser, sökord (rosacea 127, IPL 67, "IPL-behandling mot rosacea" 6, rodnad, blodkärl, ytliga blodkärl, pigment), frysta meta. 0 em-streck/råa apostrofer (§13.C; php-lint saknas lokalt → verifieras på staging).
**Ägar-kalibrering mitt i:** ägaren frågade "rätt mängd eller för mycket?" → visade diff → svar: "rätt mängd, fortsätt". (Denna = executor-terminalen; planner-terminalen körde plan-review parallellt, se nästa post.)
**Workflow-verifiering (15 agenter, adversariell — predikt + diff-check + helhetskritiker):** alla 7 block predikterade **SLIGHT** (mål nått). Fixade 4 äkta fynd: process-p2 "bryts ner" (överdrog vs facit "minskar framträdande") mjukad + "efter din hud"-dubblett (delad med desc-p2) bort + "IPL-enheten" åter; Eftervård-p1 redundant rodnad (täcks av Process-p3) trimmad, svullnad behållen; Eftervård-p2 "regelbundet" åter; Process-p3 IPL-sökord åter. Skippade (motiverat): "tappad eftervårds-instruktion" på Inför/Process = boilerplate som Eftervård-sektionen äger (siloing); vaga svansar täcks av kvarlämnad desc-p1.
**§1.4:** MODERATE-sida, median flyttad → förväntad **sidnivå SLIGHT (AI COPY-flagg-vinst)**. **Prediktion (§10 steg 1):** AI STYLE ↑↑ (öppningar+antites+marknad+passiv = största spaken), Evidence = (namngivna maskiner i orört Märken-block), Depth = (alla poäng kvar), E-E-A-T/sökord =. FÖRE-baseline: SCORE 39 / CQ 68 / Evidence 46 / E-E-A-T 85 / **AI STYLE 25** (topsite-kolumn C, `lynx-data.php`). **A/B-test:** bryter de-AI AI STYLE-taket 25?

### 2026-07-01 — `acne.php` (HUVUDSIDA / husröst-REFERENS, KW116, SCORE 39) — 🔴-block omskrivna, klar → staging
**Gjort (facit-guidad, v4):** Skrev om de **10 🔴 SIGNIFICANT-blocken** (banner-scaffolding "Här förklarar vi"; Vem/Var/ålders-/svårighetsgrad-/område-block = demografisk-skal + importans; laser-marknad "avancerad… effektiv lösning"; artikel-CTA "Du som vill ha det bäst… 30 år" / "Tveka inte" / "Välj innan läkare") → ledde med mekanism/konkret, kapade scaffolding/importans/marknad. **LÄMNADE husröst-referensblocken orörda** (full-mekanism-payoff, "Noduler >5 mm" 🟢, definitionerna, "Akne består av papler…" 🟠, vi-handlingar, FAQ) — de ÄR modellen vi emulerar. Bevarat: sökord + 2 inline-länkar (acne-vulgaris, acne-ansikte) + frysta meta. 0 råa apostrofer. (1 "Tveka inte" kvar i obetygsatt FAQ — lämnad.)
**§1.4:** sidnivå = 🔵 SLIGHT (median), så detta **sänker inte AI COPY-flaggan** men lyfter **SCORE** (mål: AI STYLE 30↑ + Evidence 11↑; Depth 77/E-E-A-T 84 hålls). **Prediktion:** AI STYLE ↑, Evidence ↑, Depth/E-E-A-T/sökord =. FÖRE-SCORE (68 dgr): 39/CQ56/Ev11/AISTYLE30 (= kolumn A, `lynx-data.php`).

### 2026-07-01 — `om-oss.php` (MODERATE, KW3) — OMSKRIVEN AUTONOMT (facit-guidad), klar → staging
**Gjort (facit-guidad v4, medan ägaren borta — utan pauser):** Skrev om de facit-flaggade blocken (O01 intro 🟠, O04 unik-helhet-bullet 🟠, O06 SHR-bullet 🔴, O07 "modern hudvård" 🔴, O08 tre-kliniker 🔴) — ledde konkret, kapade marknad (unik och effektiv/"det självklara valet"/"inte bara X utan Y"/optimala resultat/bästa möjliga). **Responsiva dubbletter (O07/O08 desktop+mobil-varianter) hållna i synk.** **Lämnade 🔵/🟢** (O02/O03 fyrstegs, O05 1994, O09 CTA, omdömen — facit=OK). **Såg över resten (lätt hand):** obetygsatt FAQ Q1 hade "det självklara valet" → lätt-fixad; resten av FAQ lämnad (obetygsad, ej över-rörd autonomt). Bevarat: klinik-namn (Strandvägen/Södermalm/Sundbyberg), inline-länkar (/, /metoden.php), 30 år/1994/SHR/fyrstegsmetod, frysta H1/meta. En-strecket i body bort. 0 råa apostrofer.
**Helhetskoll:** dubblett-varianter synkade, sökordsspridning bevarad. **Prediktion:** 🔴/🟠 → SLIGHT/MODERATE; 🔵/🟢 oförändrade. Första sidan gjord helt autonomt enligt fastställd facit-driven process.

### 2026-07-01 — `hudbehandlingar/ipl/index.php` (MODERATE, Fas 3, KW19) — OMSKRIVEN MED FACIT, klar → staging
**Gjort (facit-guidad, v4 §1.3):** Första sidan omskriven MED per-block-facit (22 apr) i handen. Skrev om de 13 block som var 🔴/🟠 (banner, Vad-är-IPL ×2, Förberedelser ×2, Process ×3, typ-intro, rosacea/melasma-kort, eftervård ×2) — ledde med mekanism/konkret, kapade marknad (bästa/avancerad/garanterar/"effektiv metod"/mångsidig/maximera/"särskilt effektiv"), fixade grammatik ("eller ta bort blodkärlen"→"och kärlen"). **LÄMNADE de 3 🔵/🟢** (ytliga+pigment-kort SLIGHT, eftervård-slutinstruktion HUMAN) + omdömen — facit=OK, v4-disciplin (rör inte det som är bra; undvik v3:s onödiga omskrivning). En "mångsidig" kvar i obetygsatt FAQ-svar (lämnad). Bevarat: sökord (hudföryngring/pigmentfläckar/ytliga blodkärl/rosacea/melasma/melanin/hemoglobin/laser), priser, interna länkar, frysta meta. 0 råa apostrofer.
**Prediktion:** 🔴/🟠 → SLIGHT/MODERATE; 🔵/🟢 oförändrade. Bevis på att facit-i-handen ger precis riktning utan över-omskrivning.

### 2026-07-01 — `hudproblem/hudforandringar/index.php` (hub, KW8) — OMSKRIVEN, klar → staging
**Gjort (AI COPY):** Hub-register (§13.L). Öppningar ledda med konkret (Vad/Varför/Vem/Var + banner + $type-intro), fyra summeringssvansar bort (Vad/Varför/Vem/Var-extended — "Sammanfattningsvis"/"För att sammanfatta"), artikel 1+2 av-marknadsförda (namngav laser/CryoPen). Stavfel rättade: "födelsermäken"→"födelsemärken", "elaktartade"→"elakartade", "behandlingsplans"→"behandlingsplan". Hub-fokus skärpt till **godartade** hudförändringar (gap §8.1 #2). Bevarat: 14 typnamn i typ-listan, interna länkar (blodprickar/seborroisk-keratos), alla FAQ + **ärliga medicinska brasklappar** ("vi diagnostiserar inte" / "kontakta vårdcentral"), mekanism-kort (CryoPen/laser). Sökord grep-verifierade (hudförändringar 86, typnamn intakta). 0 råa apostrofer (§13.C).
**H1-gap (§8.1 #1, §13.H):** banner-H1 "Hudförändringar" → "Ta bort hudförändringar" i SEPARAT commit (så effekten kan attribueras). **Söka-vård-gap (§8.1 #3):** SKIP (medicinskt).
**Prediktion:** SIGNIFICANT→SLIGHT; AI STYLE ↑ (öppningar+svansar), Evidence ↑ (namngivna behandlingar), sökord =.

### 2026-07-01 — `behandla-pigmentflackar.php` (bonus, KW16) — OMSKRIVEN, klar → staging
**Gjort:** Hela sidan de-AI:ad steg för steg (banner + $about + $define + $treat + 5 behandlingskort). Öppningar ledda med mekanism/konkret (banner → namngivna metoder; $about → "bryta ner pigment"; laser-kortet → ljuspulser-mekanism i stället för "mycket effektiv metod"); marknadssvansar bort ($about para 3 "dedikerade team… bästa möjliga vården", fluff-svansar i IPL/laser/CryoPen-korten); marknadsord bort (de mest effektiva, skräddarsydda, avancerad laserteknologi, snabbt och effektivt). Bevarat: metodnamn (IPL/kemisk peeling/laser/microneedling/CryoPen), intern länk ("kemisk peeling stockholm" → /kemisk-peeling.php), priser (5× "Från 1995 kr"), melanin, FAQ (redan konkret/GOOD), frysta meta ($seo_title/$seo_keywords §13.H). Bonussida-disciplin (§13.M): höll long-tail "behandla/ta bort pigmentfläckar", jagade inte huvudtermen. 0 råa apostrofer (§13.C).
**Prediktionsliggare (§10 / modellmål — block-gissning FÖRE refresh, scoras mot LYNX sen):** banner 🔴→🔵 ~80% · $about 🔴→🔵 ~75% · $define 🟠→🔵 ~60% · $treat 🔴→🔵 ~70% · laser-kort 🔴→🔵 ~75% · IPL/kemisk/micro/cryo 🟠→🔵 ~55% · FAQ 🔵 (orört). Sida SIGNIFICANT→SLIGHT förväntat; AI STYLE ↑ + Evidence ↑ (namngivna metoder), sökord =.

### 2026-07-01 — `ytliga-blodkarl.php` — OMSKRIVEN (steg för steg), klar → staging
**Gjort:** Hela sidan svept med den kalibrerade minimal-metoden, block för block med ägar-godkännande: (1) öppningarna ledda med mekanism/konkret (Varför, Vem, Var, Vad-extended, Varför-extended, Vem-extended); (2) tre rena summeringsstycken bort (Varför-/Vem-/Var-extended — microneedling-mönstret); (3) marknadsord bort (effektiv/skräddarsyr/"det självklara valet"/"de mest avancerade"); (4) grammatik (dem→de, "en kosmetisk"→"ett kosmetiskt"); (5) gap-punkter §8.1: rosacea inline-länk, FAQ "förebygga" rättad från åderbråcks-råd → ansiktsrelevant, hemmavård-vinkel + namngivna maskiner (Alma Rejuve Dye-VL/Harmony XL Pro) i artiklarna. Varje mening/poäng bevarad utom rena dubbletter; sökord grep-verifierade (näsan 10, kinderna 7, näsvingarna/näsryggen, rosacea, IPL, brustna/spindelkärl); 0 råa apostrofer (§13.C).
**Prediktion (§10 steg 1):** AI STYLE ↑ (öppningar + borttagna summeringssvansar = §1.1 största spakar), Evidence ↑ (namngivna maskiner), Depth = (poäng kvar), E-E-A-T/sökord =. Förväntad SIGNIFICANT → SLIGHT på de omskrivna blocken. Testar öppnings-spaken från acnebehandling-facit i skarpt läge.
**Process:** kalibrerat efter att försök #1 stoppades — den här gången steg för steg, ett block i taget med godkännande; ägaren nöjd ("detta är bra").
**Följd-fix (facit-driven, 2026-07-01):** LYNX FÖRE-facit (29 apr) visade att Vad-content faktiskt var 🔴 SIGNIFICANT — jag hade under-behandlat den ("bedömde leder redan med mekanism", gav bara komma+länk). Gjorde riktig de-AI: konkret öppning + hedge-svansen ("utesluta eventuella bakomliggande problem") och "variera i storlek och form" bort. Lärdom: definitions-öppning + lång + hedge-svans = 🔴 trots mini-mekanism (§1.1 nyckel 1). Se `lynx-examples.php`.

### 2026-06-30 — `acne-ansikte.php` — omskriven (hela sidan klar), väntar main-push
**Gjort:** Hela sidan omskriven med minimal diff (§13.O): bara tydligaste AI-tells bort (marknadsord avancerad/effektiv/skräddarsydd/speciell/avgörande, boilerplate "du är inte ensam", meta-scaffolding, fyllnadssvansar) + värsta komma-splitsarna. Struktur, summeringar, alla poänger, sökord, claims (**Cutibacterium kvar**), priser och länkar intakta — grep-verifierat. Inget unikt innehåll tappat.
**Prediktion (§10 steg 1):** AI STYLE ↑ (mindre fyllnad/marknadsord + Orsaker-öppningarna ledda med mekanism = §1.1:s största spak), Evidence/Depth = (substans kvar), sökord/E-E-A-T =. Förväntad landning SIGNIFICANT → MODERATE/SLIGHT. Listformatet behållet med flit — mäter om LYNX straffar en ren lista eller bara en utfylld.
**Process-lärdomar (inbakat i playbook):** §13.O minimal-diff (ta bort LITE, iterera, kan även lägga till/rätta); §13.D döm efter sektionens syfte (uppräkning → behåll lista, slå inte ihop poänger); §13.N info ≠ längd, bonussidor får vara kortare; §3 komma stryks rakt av.

### Arkiverade poster → `includes/lynx/lynx-log-arkiv.php` (fulltext där)
- 2026-07-01 Beslut: kör 1 Claude i taget — ratificerat i §0.1/§12.
- 2026-07-01 Plan-review (planerare/exekutor) — facit-flöde/save-first/§0.2-dispatch ratificerade; autonom-kvittens = §13.E; "frys modellbygge tills första mätningen" gäller fortfarande.
- 2026-07-01 ytliga-blodkarl försök #1 rullat tillbaka ("för stora förändringar") — lärdomen kodifierad i §13.O.
- 2026-06-30 Playbook-städning (över-specificering bort) — ratificerat i §0/§3/§5/§6.
- 2026-06-30 acne-ansikte första omskrivningspost + provomskrivnings-checklista — ersatt av "hela sidan klar"-posten ovan.

---

