<?php exit; /* intern LYNX-arbetsfil – ej webb-serverad, läs i editor/git */ ?>
# LYNX MODELS — modeller, mätning & tolkning (läs DENNA vid mät-analys/modellförfining)
> Tolkningen av rådatan: SCORE-modellen (§1.2), AI QUESTIONS-modellen (§1.5), mät-loopen (§10) + SEO-vakten, bevakningslistan (§11.1). Bedömningsmodellen (§1.1/1.3/1.4) som används VID omskrivning bor i `lynx-rewrite.php`. Rådata: `lynx-score.php` (SCORE-nedbrytningar), `lynx-examples.php` (facit), `lynx-questions.php` (AIQ). **SCORE-modellens fullständiga härledning + 6 jul-slutsatserna + online-verifieringen ligger i `lynx-score.php` (flyttas hit vid nästa städning; korsläs tills dess).**

## 1.2 SCORE-modellen — komponenter, sajt-tak & copy-spakar (prediktiv, validera mot refresh)
**✅ LÖST 2026-07-06 (9 färska nedbrytningar — full härledning + data i `lynx-score.php`):** **Overall = medel(CQ-badge, EEAT-badge)** (9/9, flera exakt; AI STYLE ingår EJ). **EEAT-badge klampas till 60 på HÄLSOSIDOR** (vi = hudterapeuter, ej läkare på YMYL → LYNX ger ej hög auktoritet; varumärkes-/produktsidor slipper klampen, når 85–88) → **på VÅRA sidor är EEAT LÅST 60, ej copy-flyttbar.** **CQ-badge ≈ CQ-subs-medel i normalfallet** (7/9; ipl/micro var "ej fullt satt"-anomalier) → Evidence (CQ:s lägsta sub, 70–82) är en ÄKTA men liten spak; Language/Readability/Depth nära tak. **⇒ SCORE-Overall-TAK för våra hälsosidor ≈ 75–77** (medel(~90 CQ, 60 EEAT)); våra bästa omskrivna (74–78) är REDAN vid taket. **Operativ slutsats: SCORE-Overall är nästan uttömt och lågt takat på våra sidtyper — JAGA INTE SCORE med copy; den bevisade vinsten är AI COPY-flaggan (§1.1, kausal) + AIQ (§1.5).** *(Nedan §1.2-text = 30 jun-multiplikativa modellen, gäller BARA gamla analyser >30 dgr; färska följer medel-formeln ovan.)*

**⚠️ HISTORIK — OMPRÖVAS-noteringen (2026-07-02, fyra färska analyser — rådata i lynx-data-snapshot 2 jul, resonemang i §11):** (1) **SCORE 0 = trasig/tom analys**, inte dålig sida (acne-rygg = 0 på ALLA komponenter; seborroisk 0→74 vid omkörning) → re-analysera 0-sidor innan slutsats. (2) **"39-taket" brutet UTAN våra ändringar** (seborroisk 74, portomning 60, microneedling 50) → LYNX verkar ha ny version/skala; **30 jun-baselines EJ jämförbara med färska analyser — mät färsk-mot-färsk.** (3) **AI STYLE 0 på färska analyser = troligen "ej beräknad än"** (AI Copy-vyn äldre datum; seborroisk fick 50 = första uppmätta >30). (4) **Aggregeringen ser ändrad ut:** EEAT-badge 60 ≠ sub-medel 81–85 på färska; Overall ≈ medel(CQ-badge, EEAT-badge) passar micro+porto, nästan sebo. (5) **Positivt riktmärke:** sebo 74 (CQ 85, AI 50) + portos CQ-subs 95–98 visar att konkret procedur-copy skårar högt på nya skalan — samma copy-egenskaper som ger 🔵-block ger högt CQ. (6) **Möjligt att AI STYLE inte längre ingår i Overall** — medel(CQ, EEAT) passar micro (50) + porto (60) exakt, sebo 72,5 vs 74; stämmer det krymper de-AI:s SCORE-payoff och de-AI-värdet ligger i AI COPY-flaggan + CQ. Avgörs med fler färska breakdowns. (7) **Gammal-skala-analyser fortsätter passa multiplikativa formeln — nu 7/7:** bristningar (Analyzed 78 days ago) Overall 18 ≈ CQ 52 × EEAT 50 × AI 25 / 3640 = 17,9 (modellanalysen 2 jul em); om-oss (Analyzed 79 days ago, dump 6 jul) Overall 17 ≈ 57 × 59 × **20** / 3640 = 18,5 — och AI STYLE 20 = lägsta uppmätta (spannet nu 20–30) → versionsbytes-hypotesen stärkt: GAMLA analyser = multiplikativa, FÄRSKA ≈ medel(CQ,EEAT). (8) **Vyerna refreshar OBEROENDE (6 jul):** om-oss AI Copy-vy färsk (5 jul) men SCORE-analys från april; ytliga-blodkärl omvänt (färsk SCORE 74, stale badge) → kolla analysdatum PER VY innan FÖRE→EFTER-slutsats. **Bygg INGEN ny formel förrän fler färska breakdowns finns (§10); multiplikations-modellen nedan beskriver 30 jun-datan och står kvar som historik/hypotes.**
**Falsifierbart testprotokoll (registrerat 2 jul, FÖRE nästa data — §10 steg 1):** för nästa färska breakdowns ägaren skickar predikterar vi: (a) sida med AI STYLE 0 → **Overall = avrundat medel(CQ-badge, EEAT-badge) ±2** (facit hittills: micro 50 vs 50,5 ✓, porto 60 vs 60 ✓); (b) sida med AI STYLE >0 avgör AI-frågan: Overall ≈ medel(CQ,EEAT) → AI ingår EJ i Overall; Overall ≈ medel(CQ,EEAT,AI) → AI ingår (sebo: 74 vs 72,5 vs 65 → lutar EJ); (c) 0-sidor som omanalyseras → kommer tillbaka >0 med fulla komponenter. **Beställning till ägaren: färsk analys på 2–3 sidor, varav minst en där AI STYLE hunnit beräknas.**

*— Allt nedan i §1.2 är 30 jun-analysen. Läs genom ⚠️-linsen ovan: spak-prioriteringar och imperativ härur ("bryt 39", "master-spak", marginalkalkyler) är preliminära tills testprotokollet dömt. —*

SCORE (0–100) ≠ AI COPY-flaggan men lyfts av samma jobb. Komponenter: **CONTENT QUALITY** (Base, Depth, Evidence, Language, Readability) + **E-E-A-T** (Experience, Expertise, Authority, Trust) + **AI STYLE** (Human-like). Alla nedbrytningar (rådata, färska + gamla skalan) i **`lynx-score.php`**.

**Aggregeringsmodell för 30 JUN-DATAN (reverse-engineerad 2026-07-01, passade 5/5 dåvarande datapunkter inom ±1–2 p — OMPRÖVAS, se ⚠️ ovan):** **Overall ≈ CONTENT QUALITY × E-E-A-T × AI STYLE / ~3640** — MULTIPLIKATIVT, inte viktat medel. Bevis: hudforandringars Overall 17 ligger UNDER dess lägsta block (AI 25); ett medel kan aldrig hamna under sitt minsta värde → linjärt uteslutet. CQ = medel av sina 5 subs, E-E-A-T = medel av sina 4. K≈3640 (±5% brus). Fakta om varje komponent + full härledning i `lynx-examples.php`.
**AI STYLE är INTE ett hårt tak (korrigerar tidigare hypotes):** det är en **multiplikativ faktor** (0,25–0,30 skalar ner hela Overall ~70–75%). Motbevis mot cap: ipl-rosacea når 39 med AI STYLE bara 25 (via CQ 68 + E-E-A-T 85). AI STYLE är största spaken enbart för att det är LÄGST som ANDEL på nästan varje sida. **Elasticitet = 1 för alla tre** → generella regeln: höj sidans lägsta-som-andel-block. Överallt = AI STYLE → **de-AI = sajtbred master-spak**; på mål-sidor är E-E-A-T (49–58) näst lägst = andra spaken. 39-taket = produkten av tre medelmåttiga faktorer + ingen sida kombinerar topp-CQ+topp-EEAT+topp-AI. **Bryt 39 = höj AI STYLE** (acne 30→60 → Overall ~78).
**⚠️ Otestad hävstång:** AI STYLE varierar bara 20↔30 i datan (lägsta: om-oss 20, uppmätt 6 jul) → dess uppsida är modell-EXTRAPOLATION, ej empiriskt bevisad. **acne.php-omskrivningen (1 jul) = det avgörande A/B-testet** — mät AI STYLE + Overall vid nästa refresh; håller inte Overall≈CQ·EEAT·AI/3640 → justera modellen (§10).
**acne.php SCORE-fixplan (marginalräknat):** dOverall/dAI = 56·84/3640 = **+1,29 Overall per +1 AI STYLE** (störst; PRIMÄR = de-AI, redan gjort på 🔴-blocken). +1 Evidence = 0,14 Overall (Evidence 11→50 = +5,4) = SEKUNDÄR. Kompoundning: AI 30→50 + Evidence 11→50 → ~74 Overall (≈dubblat). NO-REGRESSION: rör ej Depth 77 / E-E-A-T 84.
**⚠️ Evidence-höjning MÅSTE filtreras genom §5:** OK = verifierbara siffror/tidsramar/priser ("Från X kr", "30 år", antal behandlingar, namngivna maskiner/brands, "12–22% kvinnor/3% män"), "senast uppdaterad"-datum, namngivna specialister (widget) + SHR-cert. INTE OK = medicinska studie-citat/rådgivning, uppfunna siffror, "granskad av hudläkare" (vi är hudterapeuter), garanterade resultat (YMYL). → höj Evidence med KLINIK-fakta, inte medicinska påståenden.

**Prediktiv spak-karta (copy-drag → komponent den flyttar).** Använd för att förutse score-effekt FÖRE refresh (analogt med §1.1 för AI COPY):
| Komponent (baseline→topp) | ↑ av (skriv så här) | ↓ av (undvik) |
|---|---|---|
| **AI STYLE** 20→30 | §2-formel, §4-husröst, §1.1-täthet; konkret öppning, varierad puls, inline-gloss | AI-vokab/em-streck (§5), filler-öppning, staplade hedges, marknads-superlativ |
| **Evidence** 11–46 | siffror, tidsram, namngiven mekanism/organism (factual §5), "Från X kr", 30 år, namngivna maskiner | vaga kvantifierare, superlativ utan tal |
| **Depth** 67–81 | full kausal mekanism-vandring, flera delaspekter, bunden prosa | korta ner, fet-etikett-listor (§13.D/N) |
| **Readability** 40–65 | puls (kort+lång), gloss av fackord, tydlig struktur | enbart långa meningar, staccato |
| **E-E-A-T** 49→85 | förstahands-klinik ("vi tar bilder/rengör"), 30 år, namngivna maskiner/brands | mest strukturellt → **rör inte widgets** (specialister/resultat/recensioner bär detta) |
| **Language** 52→80 | idiomatisk svenska, rätt register | translationese, AI-vokab |

**No-regression (KRITISKT — "utan negativa konsekvenser på annat"):** spakarna är JOINT, inte fristående. Lyft AI STYLE + Evidence **utan att sänka** Depth, E-E-A-T eller sökord/ranking. Vanliga fällor: jaga Human-like genom att korta bort substans → sänker Depth (§13.N); stripa "fackord" → sänker Evidence; skriva om rubriker → tappar sökord (§6). **Regel: varje ändring ska vara ≥0 på alla komponenter och >0 på minst en.** Optimera aldrig en komponent på en annans bekostnad.

*(acne-ansikte + behandla-pigmentflackar har SCORE "–" → kör på AI COPY + formel. Modellen är en hypotes — mät, förfina och backporta enligt §10 när refreshen kommer.)*

---

## 1.5 AI QUESTIONS / AI Overview-modellen (NY 2026-07-02 — hypotes byggd på 5 sidors data; SERP-basen BEKRÄFTAD av officiell tooltip 2 jul 15:00)
**Officiell definition (tooltip):** *"How well this page answers common user questions for the topic based on Google SERP. Levels: Very Poor, Poor, OK, Good, Very Good."* — frågorna kommer alltså från Google SERP (bekräftar modellen nedan); full skala har även Very Poor/Very Good (aldrig sedda hos oss; homepage POOR = näst sämst). LYNX-vyn **"AI Overview Ranking"** per sida listar frågorna sidan borde äga i AI-overviews: **SCORE** = frågans vikt (högst först), **OPTIMIZED** = hur väl sidan besvarar frågan idag (**GOOD** > OK > **POOR**; "–" = ingen status). Sidnivå-kolumnen AIQ aggregerar troligen denna vy. Rådata per sida i **`lynx-questions.php`** (2 jul: micro/porto/acne-rygg/sebo/mogen-hy/homepage/acne-ansikte).

**Hypoteser (H1–H5 — validera mot fler sidor + refresh, §10):**
- **H1 — FAQ-titel räcker inte för GOOD:** micro har frågan "Vad är microneedling bra för?" som egen FAQ-titel (score 25) men får bara OK → GOOD kräver ett RAKT konkret svar, inte att frågan finns som rubrik.
- **H2 — svaret måste matcha frågans FORM:** acne-ryggs alla "hur får man bort"-varianter = GOOD (sidan är en hur-guide med konkreta steg) medan orsaksfrågorna = OK trots orsakssektioner. Hur→steg, varför→mekanism/orsak, kostar→pris med siffra.
- **H3 — grannfrågor besvaras på ÄGARSIDAN:** frågor som "Vilken behandling är bäst mot pigmentfläckar?" (dyker upp på micro) och "Vad är MicroDermabrasion?" tillhör andra sidors silo → kort svar + intern länk, aldrig duplicering (§5).
- **H4 — hemma-frågorna är återkommande topp** (porto "hemma" 13+5, sebo "själv/hemma" 18+4, micro "hemma") → ärligt "ingen hemmakur"-svar + klinikpivot = ytliga-blodkarl-principen (§8.1) som standard-FAQ-vinkel.
- **H5 — YMYL-angränsande frågor kan nå GOOD inom kosmetisk ram:** sebo "Kan seborroisk keratos bli cancer?" = GOOD utan medicinsk rådgivning (godartade-ramen + hänvisning) → §5-ramen hindrar inte GOOD.
- **H7 — frågelistan följer sidans LANDING-KEYWORDS, inte sidans innehåll (NY 2 jul 15:05, homepage = första beviset):** homepage (KW 298, landar brett) får hela sajtens ämnesuniversum i sin lista — portömning, milier-pris, HydraFacial, laser-acneärr osv. — trots att inget av det är startsidans innehåll. Följd: **en bred landningssida ska INTE besvara alla sina listfrågor själv** (ägarens instinkt 2 jul, korrekt per H3/silo §5); frågan ägs av silosidan, startsidan äger bara varumärkes-/förtroendefrågorna ("Är Acnespecialisten bra?" = GOOD ✓) + ev. remiss-familjen (om-oss-gapen). Startsidans POOR-badge är därmed delvis STRUKTURELL. **VERY POOR-data (första någonsin):** alla 5 = pris-/hållbarhetsfrågor ("Vad kostar portömning/milier/hydrafacial?", "Hur länge håller portömning/HydraFacial/infuzion?") → förstärker H2: kostar→siffra-svar saknas; billigaste vinsterna ligger på SILOSIDORNA (FAQ-svar med "Från X kr"), inte på startsidan.
- **H6 — POOR = fråga utan innehåll på sidan, inte dåligt svar (NY 2 jul em, mogen-hy = första POOR-datan):** mogen-hys 3 POOR är alla off-topic för sidans innehåll (magnesium→finnar, koreansk hudvård, förkortningen "HI") → POOR verkar betyda "AI Overview kopplar frågan till sidan men sidan saknar svar helt". Sid-badgen tål enstaka POOR: mogen-hy = OK trots 3 POOR + 0 GOOD (även första sidan utan någon GOOD); homepage är enda sidan med badge POOR. **Åtgärda INTE off-topic-POOR med innehåll som bryter silon (§5/H3)** — magnesium/koreaner hör inte hemma på mogen-hy; däremot är topp-frågan "Vad betyder hy?" (score 24, bara OK) ett äkta svars-gap i frågans form (H2).

**Operativt (koppla in i §7 + Fas 2):** vid rewrite/FAQ-arbete: (1) hämta sidans AI Overview Ranking; (2) topp-SCORE-frågor utan GOOD → ge ett rakt svar i frågans form (FAQ-svar i husröst — kan nå 🟢 per §1.1 nyckel 5 → **trippelvinst: AI QUESTIONS + medel §1.4 + AI STYLE**); (3) grannfrågor → länk till ägarsidan; (4) logga FÖRE-status (GOOD/OK/–) per fråga för mätloopen.

## 10. Justeringsloop & prediktiv mät-loop (efter LYNX-refresh)

### 10.0 ⛔ SEO-VAKT — LYNX-fix får ALDRIG köpas med ranking-/trafiktapp (ägarbeslut 2026-07-06)
Målet (§0) är LYNX grönt **utan skada på övriga signaler**. LYNX KW-kolumn är bara en skugga — **Google Search Console är facit.** Bakgrund: 6 jul-datan visade att omskrivna sidor tappat KW mer än orörda (behandla-pigment −19 %, acne-ansikte −9 %, ytliga −8 % vs orörda ±0–4 %) — inte konklusivt (litet urval, KW-brus, säsong) men tillräckligt för hård vakt:
1. **GSC-GATE före main-push:** inga nya rewrites promotas till main förrän ägaren dragit GSC-data för FÖRRA vågens sidor (klick/visningar/snittposition per sida, ~4 veckor före vs efter deploy) och den visar ingen skada. **Första kollen: de 8 sidorna från PR #236 (live 30 jun–1 jul) — gaten håller mogen-hy/oonskat-har/microdermabrasion på staging tills den är grön.** Ingen skada → pusha nästa våg, upprepa per våg. Skada → §13.F-rollback på drabbad sida + obduktion i §11 + pausa alla main-pushar tills orsaken är förstådd.
2. **KW-vakt per scan:** logga KW per omskriven sida vid varje Pages-dump (lynx-data). **Tröskel: sidan tappar >10–15 % medan sajtmedianen ligger stilla → flagga i §11 och utred VILKA fraser som föll** (grep §6-målfraserna mot sidan: finns frasen kvar i texten är tappet inte textens fel; saknas den = §6-miss → återinför omedelbart; be annars om sidans GSC-frågelista).
3. **CLICKS + WORDS i baseline:** §7 steg 1 loggar även CLICKS (GSC-klick via LYNX) och WORDS per sida — utan FÖRE-värden går trafikskada inte att bevisa eller frikänna.
4. **Attribution per sida i vågor (ersätter kohort-regeln, §13.G):** per-sida-commits + stabila block-betyg (§1.1) ger LYNX-attribution per sida; RANKING-attribution skyddas av att vi pushar i vågor och kör GSC-gaten mellan vågorna.
**Tumregel: ranking-tapp är dyrare än en sen LYNX-fix — vid tvekan, vänta med main-push.**

**Mät-loopen (så modellen i §1.1/§1.2 förbättras, inte bara sidorna).** Data kommer på delay (LYNX skannar live, refreshar långsamt) — därför **prediktera före, mät efter**:
1. **Före** (vid omskrivning): logga i §11 vilka komponenter vi tror rör sig och varför (t.ex. "AI STYLE ↑↑ de-AI; Evidence ↑ 30år+Från-pris+mekanismtal; Depth = hållen; sökord = hållna").
2. **Efter refresh:** logga faktisk delta per komponent (FÖRE→EFTER ur lynx-data.php).
3. **Jämför:** stämde prediktionen? Var missade modellen? Notera prediktionsfelet.
4. **Förfina** §1.1/§1.2 utifrån felet (modellen är hypotes — vi rutar inte in oss, §0/§5).
5. **Backporta:** när modellen blir bättre → lista vad som nu bör fixas på **redan gjorda/gröna sidor** (samma spak som visat sig funka). Lägg i §9 Löpande.

**Per-signal-respons:**
- **Fortf. SIGNIFICANT/MODERATE?** → nästa lager block (extended "Läs mer", MODERATE-block), mer mekanism/gloss/evidens.
- **AI QUESTIONS ej GOOD?** → FAQ-innehåll + FAQPage-schema (§9 Fas 2).
- **PAGE TYPE/P. PRICE "–"?** → generiskt fallback-Product utan Offer; sätt `$rich_product` per sida.
- **SLIGHT + SCORE nära/över 39?** → vi bröt taket; dokumentera VAD som gjorde det och backporta (§10 steg 5). *(OBS: 39-taket avser GAMLA skalan — färska analyser ligger 50–76 utan våra ändringar, §1.2; jämför färsk-mot-färsk.)*
- Uppdatera §9 + denna fil + lynx-data.php när vi lär oss vad som flyttar nålen.

---

## 11.1 Bevakningslista — sidor som väntar på LYNX-refresh (mät-loopen, §10 steg 2)
LYNX skannar bara LIVE och refreshar med delay — **mätklockan startar när ägaren pushar `main`**, inte vid staging. Vi kan inte polla LYNX (ingen export/API); ägaren droppar ny skärmdump när LYNX uppdaterat, då mäter vi delta mot FÖRE-baseline + prediktion. Listan = vad vi väntar på, så inget glöms. **▶ 2026-07-01: ägaren pushade main → mätstart igång för alla rader nedan; produktion verifierad (se §11-loggen överst; hudforandringar-warning fixad, väntar nästa main-push).**
**⚠️ 2026-07-02 — mätregeln skärpt:** LYNX verkar ha ny version/skala (§1.2 OMPRÖVAS: SCORE 0 = trasig analys, 39-taket brutet utan våra ändringar, aggregering ändrad). **Jämför INTE färska analyser rakt av mot FÖRE-baselines från 30 jun** — vid refresh: läs FÖRE-värdet som osäkert, väg per-block-AI COPY (stabil vy) tyngre än SCORE-deltan, och be ägaren köra FÄRSK analys som ny baseline där det går.
**⚠️ Tillägg 2026-07-06 — vyerna refreshar OBEROENDE (belagt):** om-oss hade FÄRSK AI Copy-vy (5 jul) men april-gammal SCORE-analys ("79 days ago"); ytliga-blodkärl omvänt (färsk SCORE 74, stale badge). → **Kolla analysdatum PER VY** (AI Copy-vyns "Last update", SCORE-popupens "Analyzed X ago") innan FÖRE→EFTER-slutsats; en Pages-rads kolumner kan ha olika ålder. **Positiv följd (2 sidor):** orörda block behåller exakt tier över refresh (§1.1) → per-block-jämförelser är brusfria även över LYNX-versionsbytet.
**⚠️⚠️ Tillägg 2026-07-06 em — STEG-VIS UPPDATERING + ATTRIBUTION KRÄVER OBSERVERAD DELTA (ägarprincip, viktigast hittills):** LYNX uppdaterar i STEG, oberoende av våra deploys — en sida/vy/kolumn kan gå BLANK medan den omanalyseras och komma tillbaka med nytt värde (**detta var pigmentflackar-"mysteriet" — sidan var mitt i omanalys, INTE en tier-flytt; §9-tråden löst**). Följd: **en "Analyzed just now" bevisar INTE före eller efter vår ändring** — den kan lika gärna vara gammal text omanalyserad. **Attribuera FÖRE→EFTER ENDAST när vi faktiskt SER två analyser med OLIKA värden** (en gammal + en ny som skiljer). Anta ALDRIG "nästa analys efter min main-push = EFTER min ändring" — vänta på observerad delta. Praktiskt: en färsk analys av en redan-live-omskriven sida (ytliga/ipl/micro) är av VÅR text, men utan matchande färsk-skala-FÖRE kan deltat inte tillskrivas oss. Ren FÖRE→EFTER får vi bara där vi har färsk FÖRE + senare färsk EFTER med annat värde (rhinophyma: färsk FÖRE 74 nu, EFTER när main-push + ny analys visar annan siffra).

| Sida | Staging-push | Main-push (mätstart) | FÖRE-baseline | Prediktion (§10 steg 1) | Senaste LYNX-analys | Status |
|---|---|---|---|---|---|---|
| acne-ansikte.php | 2026-06-30 | **2026-06-30 (LIVE)** | SCORE "–", AI COPY SIGNIFICANT, KW57; block 6🔴/1🟠/2🔵/1🟢 (22 apr) | AI STYLE ↑, Depth/Evidence/sökord = | **05 jul 2026** | ✅ **MÄTT 6 jul: 🔴→🔵 SLIGHT**; block EFTER 0🔴/1🟠/6🔵/2🟢 (synliga), KW 52, AIQ OK, SCORE fortf. "–" (§11-posten 6 jul). Kvar innan raden stängs/arkiveras: FAQ-facitresten + intro-blockets 🟠 (micro-fix-kandidat) |
| ytliga-blodkarl.php | 2026-07-01 | **2026-07-01 (LIVE)** | SCORE 22, AI COPY SIGNIFICANT, KW172 | AI STYLE ↑ (öppningar+summeringar bort), Evidence ↑ (namngivna maskiner), Depth/E-E-A-T/sökord = | SCORE färsk (6 jul-dump); AI Copy-vyn ? | live på main (PR #236); **6 jul: SCORE 22→74 FÄRSK men badge kvar 🔴 — AI Copy-datum beställt; väntar badge-refresh** |
| behandla-pigmentflackar.php | 2026-07-01 | **2026-07-01 (LIVE)** | AI COPY SIGNIFICANT, SCORE –, AIQ GOOD, KW16; block 25 apr: 8🔴/1🟥/3🔵/1🟢 (medel 2,38) | block-gissningar 🔴/🟠→🔵 (öppningar+svansar), Evidence ↑ (metoder), sökord = | **AI Copy-vyn "Last update: 07 Jul"** (färsk crawl av vår text) | ✅ **MÄTT 7 jul: badge 🔴→🔵 SLIGHT + KOMPLETT per-block-EFTER** (2🔴/2🟠/8🔵/1🟢, n=13, medel 2,38→1,38; §1.4 pred 🔵 ✓): 5 av 9 flaggade → 🔵, MEN kemisk-kortet 🔴 kvar, micro-kortet 🟥→🔴, $about-2 + IPL-kortet 🟠 → **micro-fix-kandidat (4 block), frysning hävd**; backport-lärdomar i lynx-examples (EFTER-sektionen). Kvar: färsk SCORE |
| hudforandringar/index.php | 2026-07-01 | **2026-07-01 (LIVE)** | AI COPY SIGNIFICANT, SCORE 17, GAPS 3/2, KW8 | block-gissningar 🔴/🟠→🔵 (öppningar+svansar), Evidence ↑, sökord = | – | de-AI:ad + H1-sökord (sep. commit) → staging; live på main (PR #236), debug-rad-fix d3ce9162 väntar main-push; **väntar LYNX-refresh** |
| hudbehandlingar/ipl/ | 2026-07-01 | **2026-07-01 (LIVE)** | MODERATE, SCORE –, P.PRICE HIGH, KW19; per-block-facit 22 apr | 13× 🔴/🟠→SLIGHT/MOD; 3× 🔵/🟢 orörda | – | facit-guidad de-AI (Fas 3) → staging; live på main (PR #236); **väntar LYNX-refresh** |
| om-oss.php | 2026-07-01 | **2026-07-01 (LIVE)** | MODERATE, VAL 8, SCORE 17, KW3; block 22 apr: 3🔴/2🟠/6🔵/1🟢 | O01/O04 🟠 + O06/O07/O08 🔴 → SLIGHT/MOD; 🔵/🟢 orörda | **05 jul 2026 (AI Copy); SCORE-analys apr (79 dgr)** | ✅ **MÄTT 6 jul: block EFTER 0🔴/0🟠/10🔵/1🟢 (synliga) — alla 🔴→🔵 ✓**; badge ej synlig i dumpen (SLIGHT implicerat — borta ur MODERATE-gruppen); kvar innan stängning: badge-bekräftelse + O01-bannern + FAQ-betygen (§11 6 jul #2) |
| acne.php | 2026-07-01 | **2026-07-01 (LIVE)** | 🔵 SLIGHT sidnivå, SCORE 39 (Depth77/Ev11/**AISTYLE30**), KW116; block-facit 22 apr | AI STYLE ↑ + Evidence ↑ (sidnivå kvar SLIGHT §1.4); Depth/E-E-A-T = | – | 10 🔴-block omskrivna (husröst-ref lämnad) → staging; live på main (PR #236); **väntar LYNX-refresh** |
| ipl-rosacea.php | 2026-07-01 | **2026-07-01 (LIVE)** | MODERATE, SCORE 39 (CQ68/Ev46/EEAT85/**AISTYLE25**), P.PRICE HIGHEST, KW20; per-block-facit 29 apr | 7× 🔴/🟠→SLIGHT (median→SLIGHT §1.4); AI STYLE ↑↑, Depth/Evidence/E-E-A-T/sökord = | SCORE färsk (6 jul-dump); AI Copy-vyn ? | live på main (PR #236); **6 jul: SCORE 39→60 FÄRSK men badge kvar 🟠 — väntar badge-refresh** (kosmetisk title-attr-typo rad 64 `rosaceabehandlingr`→`rosaceabehandling` fixad) |
| mogen-hy.php | 2026-07-02 | *(väntar main-push)* | 🟠 MODERATE, SCORE – (gammal 12?), KW9; per-block-facit 22 apr KOMPLETT (5🔴/1🟠/5🔵/3🟢, medel 1,57); AIQ OK (27-frågelista i lynx-questions) | 6 omskrivna block → 🔵-band (bedömar-predikt 3×SLIGHT+3×MODERATE); block-medel →~1,0 → **sidnivå 🟠→🔵**; AI STYLE ↑, Language ↑ (5 språkfixar), Depth/sökord = | – | omskriven + §7.4b-verifierad (5 fynd åtgärdade) → staging 2 jul em; **väntar ägarens main-push → LYNX-refresh** |
| hudproblem/oonskat-har/ | 2026-07-03 | *(väntar main-push)* | 🟠 MODERATE; per-block-facit 29 apr (5🔴/2🟠/4🔵/2🟢, medel 1,77); AIQ-frågelista SAKNAS (be ägaren) | 7 omskrivna block → 🔵-band; block-medel →~1,0 → **sidnivå 🟠→🔵**; AI STYLE ↑, Language ↑ (typo/grammatik/alt-titles), Evidence ↑ (Splendor X + Soprano Ice namngivna), Depth/sökord = | – | omskriven + §7.4b-verifierad (3 agenter) → staging 3 jul (verifierad 200 + ny fras); **väntar ägarens main-push → LYNX-refresh** |
| microdermabrasion.php | 2026-07-03 | *(väntar main-push)* | 🟠 MODERATE, SCORE 50 färsk, AIQ OK (GOOD→OK-tråden öppen, frågedetalj saknas); per-block-facit 25 jun (5🔴/1🟠/3🔵/2🟢, medel 1,82) | 6 omskrivna block → 🔵-band; block-medel →~1,0 → **sidnivå 🟠→🔵**; AI STYLE ↑, Language ↑ (kongruens/anglicismer), Evidence =, Depth/sökord = | – | omskriven + §7.4b-verifierad (3 agenter) → staging 3 jul (verifierad 200 + ny fras); kortpriser rättade 3 jul em; **väntar main-push → LYNX-refresh** |
| hudproblem/bristningar/ | 2026-07-06 | *(väntar ⛔ §10.0-GSC-gate → main-push)* | 🟠 MODERATE, SCORE 18 gammal/**63 FÄRSK 6 jul** (ny skala, ren FÖRE-baseline), KW67, CLICKS/WORDS ur nästa dump; block-facit 22 apr: 6🔴/1🟠/5🔵/1🟢 (medel 1,92) | 7 omskrivna block → 🔵-band (bedömare: 2🟢/3🔵/2 🟠-gräns); medel →~0,9 → **sidnivå 🟠→🔵**; AI STYLE ↑, Language ↑, Evidence ↑ (namngivna metoder), Depth/sökord = | – | omskriven + §7.4b-verifierad (3 agenter, 0 allvarliga) → staging 6 jul (verifierad 200 + ny fras); **väntar GSC-gate → main-push → refresh** (§11 6 jul #7) |
| acne-ansikte.php INTRO-EXPERIMENT | 2026-07-06 | *(väntar ⛔ §10.0-GSC-gate → main-push)* | intro-blocket 🟠 (EFTER-facit 5 jul); sidbadge 🔵 | intro 🟠→🔵 (importans-wrapper bort + Nedan-skylt) — **dömer §2-intro-hypotesen**; sidbadge kvar 🔵 | – | enblocks-fix → staging 6 jul (verifierad 200 + ny fras); renaste experimentet hittills — 1 block ändrat på mätt sida |

När en rad refreshats: mät (§10 steg 2–3), logga EFTER i §11 + lynx-data.php, förfina modellen (steg 4), backporta (steg 5), töm raden.

---

