name: Deploy Live

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install sass
        run: npm install -g sass

      - name: Compile SCSS
        run: sass --style compressed --no-source-map --quiet .:.

      - name: Install typescript
        run: npm install typescript

      - name: Compile Typescript
        run: tsc
        
      - name: Compress files
        run: zip web.zip * -r -x "*.scss" -x "*.ts" -x "*.DS_Store" -x "Dockerfile" -x ".env" -x "composer.*" -x "package.json" -x "compose.yml" -x ".gitignore" -x "template.php" -x "tsconfig.json"
        
      - name: Transfer zip
        uses: nogsantos/scp-deploy@master
        with:
          src: ./*
          host: ${{ secrets.AS_SSH_HOST }}
          remote: ~/temp.visurus.org
          port: 22
          user: ${{ secrets.AS_SSH_USER }}
          key: ${{ secrets.AS_SSH_KEY }}      

      - name: Uncompress on server
          - run: |
            echo "${{ secrets.AS_SSH_KEY }}" > secret.key
            ssh -i secret.key {{ secreats.AS_SSH_USER}}@${{ SECRETS.AS_SSH_HOST }}
            cd ~/temp.visurus.org
            unzip web.zip
