name: Deploy Main

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install bulma
        run: npm install bulma

      - name: Install sass
        run: npm install -g sass

      - name: Compile SCSS
        run: find . -type f -not -path "./node_modules/*" -not -name "_*.scss" -name "*.scss" -exec sh -c 'sass --style compressed --no-source-map --quiet --no-stop-on-error "$1" "${1%.scss}.css"' _ {} \;

      - name: Install typescript
        run: npm install typescript@latest @types/node@latest

      - name: Compile Typescript
        run: tsc

      - name: Compress files
        run: zip web.zip * .[^.]* -r -x ".htaccess" -x ".devcontainer/*" -x ".git/*" -x ".github/*" -x "*.scss" -x "*.ts" -x "README.md" -x "*.DS_Store" -x "Dockerfile" -x "*/.env" -x "composer.*" -x "package*.json" -x "compose.yml" -x ".gitignore" -x "template.php" -x "tsconfig.json"

      - name: Transfer zip
        uses: nogsantos/scp-deploy@master
        with:
          src: ./web.zip
          host: ${{ secrets.DARUMA_HOST }}
          remote: ~/acnespecialisten.se
          port: 22
          user: ${{ secrets.DARUMA_USER }}
          key: ${{ secrets.DARUMA_KEY }}

      - name: Uncompress on server
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DARUMA_KEY }}" > ~/.ssh/id_rsa
          host='${{ secrets.DARUMA_HOST }}'
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.DARUMA_USER }}@${{ secrets.DARUMA_HOST }} 'cd ~/acnespecialisten.se; unzip -o web.zip; rm web.zip;'
