name: Deploy Live

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install -g sass
        
      - name: Compile SCSS
        run: sass --style compressed --no-source-map .:.
        
      - name: Transfer files
        uses: nogsantos/scp-deploy@master
        with:
          src: ./*
          host: ${{ secrets.AS_SSH_HOST }}
          remote: ~/temp.visurus.org
          port: 22
          user: ${{ secrets.AS_SSH_USER }}
          key: ${{ secrets.AS_SSH_KEY }}      
